package vn.com.msb.homeloan.core.service.mockdata;

import vn.com.msb.homeloan.core.entity.PropertyEntity;
import vn.com.msb.homeloan.core.model.UpdateConfig;

public class PropertiesDataBuild {

  public static PropertyEntity buildPropertyEntity() {
    PropertyEntity propertyEntity = new PropertyEntity();
    propertyEntity.setUuid("0e5a8854-fbe5-4428-977b-04ff40e18dcb");
    propertyEntity.setName("loan-calculation");
    propertyEntity.setCurrentValue("{\n"
        + "    \"data\": {\n"
        + "        \"income\": {\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"value\": \"5000000\",\n"
        + "                    \"message_error\": \"Tổng thu nhập bạn cần có ít nhất là 5 triệu\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"monthly_payment_amount\": {\n"
        + "            \"formula\": \"0.7*income-2000000\",\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"condition\": \"(0.7*income-2000000) < value\",\n"
        + "                    \"message_error\": \"Dư nợ vượt quá khả năng tài chính của bạn\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": false\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"collateral_value\": {\n"
        + "            \"formula\": \"loan_amount/0.8\",\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"value\": \"200000000\",\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"message_error\": \"Giá trị TSBĐ tối thiểu là 200 triệu đồng\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"value\": \"100000000000\",\n"
        + "                    \"type\": \"max\",\n"
        + "                    \"message_error\": \"Giá trị TSBĐ tối đa là 100 tỷ\"\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"loan_time\": {\n"
        + "            \"formulas\": [\n"
        + "                {\n"
        + "                    \"formula\": \"0.7*income-monthly_payment_amount\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"case\",\n"
        + "                    \"condition\": \"value >= 2_000_000 && value < 30_000_000\",\n"
        + "                    \"value\": 240\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"case\",\n"
        + "                    \"condition\": \"value >= 30_000_000\",\n"
        + "                    \"value\": 300\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"value\": 3,\n"
        + "                    \"message_error\": \"Thời hạn vay tối thiểu là 3 tháng\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"condition\": \"value < 84 && debt_method === `GTD`\",\n"
        + "                    \"message_error\": \"Kỳ hạn vay >= 84 tháng với Phương thức trả nợ Gốc tăng dần, lãi theo dư nợ thực tế\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"condition\": \"value < 84 && debt_method === `GGD`\",\n"
        + "                    \"message_error\": \"Kỳ hạn vay >= 84 tháng với Phương thức trả nợ Gốc giảm dần, lãi theo dư nợ thực tế\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"max\",\n"
        + "                    \"value\": 300,\n"
        + "                    \"message_error\": \"Thời hạn vay tối đa là 300 tháng\"\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"loan_amount\": {\n"
        + "            \"formula\": \"(365*(0.7*income-monthly_payment_amount)*loan_time)/(365+loan_time*(0.126*30))\",\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"value\": 100000000,\n"
        + "                    \"message_error\": \"Số tiền cần vay tối thiểu là 100 triệu\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"max\",\n"
        + "                    \"value\": 20000000000,\n"
        + "                    \"message_error\": \"Số tiền cần vay tối đa là 20 tỷ\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"condition\": \"collateral_value*0.8 < value\",\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"message_error\": \"Số tiền cần vay tối đa không vượt quá 80% giá trị TSBĐ\"\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"interest_rate\": {\n"
        + "            \"values\": [\n"
        + "                {\n"
        + "                    \"name\": \"4,99% - 3 tháng đầu\",\n"
        + "                    \"key\": \"499\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"6,99% - 6 tháng đầu\",\n"
        + "                    \"key\": \"699\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"7,99% - 12 tháng đầu\",\n"
        + "                    \"key\": \"799\",\n"
        + "                    \"default\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"8,75% - 18 tháng đầu\",\n"
        + "                    \"key\": \"875\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"9,15% - 24 tháng đầu\",\n"
        + "                    \"key\": \"915\",\n"
        + "                    \"default\": false\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"debt_method\": {\n"
        + "            \"values\": [\n"
        + "                {\n"
        + "                    \"name\": \"Gốc trả đều hàng tháng, lãi giảm dần\",\n"
        + "                    \"key\": \"GTDHH\",\n"
        + "                    \"default\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc trả đều 02 tháng/lần, lãi giảm dần\",\n"
        + "                    \"key\": \"GTD2T\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc trả đều 03 tháng/lần, lãi giảm dần\",\n"
        + "                    \"key\": \"GTD3T\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc tăng dần, lãi theo dư nợ thực tế\",\n"
        + "                    \"key\": \"GTD\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc giảm dần, lãi theo dư nợ thực tế\",\n"
        + "                    \"key\": \"GGD\",\n"
        + "                    \"default\": false\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"status\": 200\n"
        + "    }\n"
        + "}");

    return propertyEntity;
  }

  public static UpdateConfig buildUpdateConfig() {
    UpdateConfig updateConfig = new UpdateConfig();
    updateConfig.setCurrentValue("{\n"
        + "    \"data\": {\n"
        + "        \"income\": {\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"value\": \"5000000\",\n"
        + "                    \"message_error\": \"Tổng thu nhập bạn cần có ít nhất là 5 triệu\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"monthly_payment_amount\": {\n"
        + "            \"formula\": \"0.7*income-2000000\",\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"condition\": \"(0.7*income-2000000) < value\",\n"
        + "                    \"message_error\": \"Dư nợ vượt quá khả năng tài chính của bạn\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": false\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"collateral_value\": {\n"
        + "            \"formula\": \"loan_amount/0.8\",\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"value\": \"200000000\",\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"message_error\": \"Giá trị TSBĐ tối thiểu là 200 triệu đồng\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"value\": \"100000000000\",\n"
        + "                    \"type\": \"max\",\n"
        + "                    \"message_error\": \"Giá trị TSBĐ tối đa là 100 tỷ\"\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"loan_time\": {\n"
        + "            \"formulas\": [\n"
        + "                {\n"
        + "                    \"formula\": \"0.7*income-monthly_payment_amount\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"case\",\n"
        + "                    \"condition\": \"value >= 2_000_000 && value < 30_000_000\",\n"
        + "                    \"value\": 240\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"case\",\n"
        + "                    \"condition\": \"value >= 30_000_000\",\n"
        + "                    \"value\": 300\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"value\": 3,\n"
        + "                    \"message_error\": \"Thời hạn vay tối thiểu là 3 tháng\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"condition\": \"value < 84 && debt_method === `GTD`\",\n"
        + "                    \"message_error\": \"Kỳ hạn vay >= 84 tháng với Phương thức trả nợ Gốc tăng dần, lãi theo dư nợ thực tế\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"condition\": \"value < 84 && debt_method === `GGD`\",\n"
        + "                    \"message_error\": \"Kỳ hạn vay >= 84 tháng với Phương thức trả nợ Gốc giảm dần, lãi theo dư nợ thực tế\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"max\",\n"
        + "                    \"value\": 300,\n"
        + "                    \"message_error\": \"Thời hạn vay tối đa là 300 tháng\"\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"loan_amount\": {\n"
        + "            \"formula\": \"(365*(0.7*income-monthly_payment_amount)*loan_time)/(365+loan_time*(0.126*30))\",\n"
        + "            \"rules\": [\n"
        + "                {\n"
        + "                    \"type\": \"min\",\n"
        + "                    \"value\": 100000000,\n"
        + "                    \"message_error\": \"Số tiền cần vay tối thiểu là 100 triệu\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"required\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"type\": \"max\",\n"
        + "                    \"value\": 20000000000,\n"
        + "                    \"message_error\": \"Số tiền cần vay tối đa là 20 tỷ\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"condition\": \"collateral_value*0.8 < value\",\n"
        + "                    \"type\": \"validate\",\n"
        + "                    \"message_error\": \"Số tiền cần vay tối đa không vượt quá 80% giá trị TSBĐ\"\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"interest_rate\": {\n"
        + "            \"values\": [\n"
        + "                {\n"
        + "                    \"name\": \"4,99% - 3 tháng đầu\",\n"
        + "                    \"key\": \"499\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"6,99% - 6 tháng đầu\",\n"
        + "                    \"key\": \"699\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"7,99% - 12 tháng đầu\",\n"
        + "                    \"key\": \"799\",\n"
        + "                    \"default\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"8,75% - 18 tháng đầu\",\n"
        + "                    \"key\": \"875\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"9,15% - 24 tháng đầu\",\n"
        + "                    \"key\": \"915\",\n"
        + "                    \"default\": false\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"debt_method\": {\n"
        + "            \"values\": [\n"
        + "                {\n"
        + "                    \"name\": \"Gốc trả đều hàng tháng, lãi giảm dần\",\n"
        + "                    \"key\": \"GTDHH\",\n"
        + "                    \"default\": true\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc trả đều 02 tháng/lần, lãi giảm dần\",\n"
        + "                    \"key\": \"GTD2T\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc trả đều 03 tháng/lần, lãi giảm dần\",\n"
        + "                    \"key\": \"GTD3T\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc tăng dần, lãi theo dư nợ thực tế\",\n"
        + "                    \"key\": \"GTD\",\n"
        + "                    \"default\": false\n"
        + "                },\n"
        + "                {\n"
        + "                    \"name\": \"Gốc giảm dần, lãi theo dư nợ thực tế\",\n"
        + "                    \"key\": \"GGD\",\n"
        + "                    \"default\": false\n"
        + "                }\n"
        + "            ]\n"
        + "        },\n"
        + "        \"status\": 200\n"
        + "    }\n"
        + "}");
    updateConfig.setName("loan-calculation");

    return updateConfig;
  }
}
