package vn.com.msb.homeloan.core.constant;

public class PermissionConstants {

  public static final String TEST = "TEST";
  public static final String CJ5_LOAN_APPLICATION_PRE_ZIP_FILE = "CJ5-LOAN_APPLICATION-PRE_ZIP_FILE";
  public static final String CJ5_LOAN_APPLICATION_SEARCH = "CJ5-LOAN_APPLICATION-SEARCH";
  public static final String CJ5_LOAN_APPLICATION_UPDATE_RM_FOR_LOAN = "CJ5-LOAN_APPLICATION-UPDATE_RM_FOR_LOAN";
  public static final String CJ5_LOAN_APPLICATION_CLOSE = "CJ5-LOAN_APPLICATION-CLOSE";
  public static final String CJ5_LOAN_APPLICATION_EXPORT = "CJ5-LOAN_APPLICATION-EXPORT";
  public static final String CJ5_LOAN_APPLICATION_DETAIL = "CJ5-LOAN_APPLICATION-DETAIL";
  public static final String CJ5_LOAN_APPLICATION_EXPORT_PROPOSAL_LETTER = "CJ5-LOAN_APPLICATION-EXPORT_PROPOSAL_LETTER";
  public static final String CJ5_LOAN_APPLICATION_SUBMIT_FEEDBACK = "CJ5-LOAN_APPLICATION-SUBMIT_FEEDBACK";
  public static final String CJ5_LOAN_APPLICATION_ZIP_LOANS = "CJ5-LOAN_APPLICATION-ZIP_LOANS";
  public static final String CJ5_LOAN_APPLICATION_UPDATE_CUSTOMER_INFO = "CJ5-LOAN_APPLICATION-UPDATE_CUSTOMER_INFO";
  public static final String CJ5_LOAN_APPLICATION_REGENERATE_DNVV = "CJ5-LOAN_APPLICATION-REGENERATE_DNVV";
  public static final String CJ5_LOAN_APPLICATION_CUSTOMER_AND_RELATED_PERSON = "CJ5-LOAN_APPLICATION-CUSTOMER_AND_RELATED_PERSON";
  public static final String CJ5_LOAN_APPLICATION_UPDATE_STATUS = "CJ5-LOAN_APPLICATION-UPDATE_STATUS";
  public static final String CJ5_LOAN_APPLICATION_ADD_NEW = "CJ5-LOAN_APPLICATION-ADD_NEW";
  public static final String CJ5_LOAN_APPLICATION_GET_INCOME_INF0 = "CJ5-LOAN_APPLICATION-GET_INCOME_INF0";
  public static final String CJ5_LOAN_APPLICATION_UPDATE_LOAN_INFO = "CJ5-LOAN_APPLICATION-UPDATE_LOAN_INFO";

  public static final String CJ5_BUSINESS_INCOMES_UPDATE = "CJ5-BUSINESS_INCOMES-UPDATE";
  public static final String CJ5_BUSINESS_INCOMES_DELETE_BY_ID = "CJ5-BUSINESS_INCOMES-DELETE_BY_ID";

  public static final String CJ5_CIC_CHECK_TYPE_DEBT = "CJ5-CIC-CHECK_TYPE_DEBT";
  public static final String CJ5_CIC_GET_CIC_INFO = "CJ5-CIC-GET_CIC_INFO";

  public static final String CJ5_COLLATERAL_GET_BY_LOANID = "CJ5-COLLATERAL-GET_BY_LOANID";
  public static final String CJ5_COLLATERAL_SAVES = "CJ5-COLLATERAL-SAVES";
  public static final String CJ5_COLLATERAL_DELETE_BY_ID = "CJ5-COLLATERAL-DELETE_BY_ID";

  public static final String CJ5_COLLATERAL_OWNER_SAVES = "CJ5-COLLATERAL_OWNER-SAVES";
  public static final String CJ5_COLLATERAL_GET_BY_LOAN_ID = "CJ5-COLLATERAL_OWNER-GET_BY_LOAN_ID";
  public static final String CJ5_COLLATERAL_OWNER_DELETE_BY_ID = "CJ5-COLLATERAL_OWNER-DELETE_BY_ID";

  public static final String CJ5_CONTACT_PERSON_UPDATE = "CJ5-CONTACT_PERSON-UPDATE";

  public static final String CJ5_CREDIT_APPRAISAL_SAVE = "CJ5-CREDIT_APPRAISAL-SAVE";
  public static final String CJ5_CREDIT_APPRAISAL_GET_BY_LOANID = "CJ5-CREDIT_APPRAISAL-GET_BY_LOANID";

  public static final String CJ5_CSS_GET_SCORE_RB = "CJ5-CSS-GET_SCORE_RB";
  public static final String CJ5_CSS_GET_CSS_INFO = "CJ5-CSS-GET_CSS_INFO";

  public static final String CJ5_DISTRICT_FIND_BY_PROVINCE = "CJ5-DISTRICT-FIND_BY_PROVINCE";

  public static final String CJ5_LOAN_APPLICATION_COMMENT_SAVE = "CJ5-LOAN_APPLICATION_COMMENT-SAVE";
  public static final String CJ5_LOAN_APPLICATION_COMMENT_UPDATE = "CJ5-LOAN_APPLICATION_COMMENT-UPDATE";
  public static final String CJ5_LOAN_APPLICATION_COMMENT_DELETE = "CJ5-LOAN_APPLICATION_COMMENT-DELETE";
  public static final String CJ5_LOAN_APPLICATION_COMMENT_HISTORY = "CJ5-LOAN_APPLICATION_COMMENT-HISTORY";

  public static final String CJ5_LOAN_PAYER_SAVE = "CJ5-LOAN_PAYER-SAVE";
  public static final String CJ5_LOAN_PAYER_DELETE_BY_ID = "CJ5-LOAN_PAYER-DELETE_BY_ID";

  public static final String CJ5_ASSET_EVALUATE_SAVE = "CJ5-ASSET_EVALUATE-SAVE";

  public static final String CJ5_LOAN_UPLOAD_PRE_DOWNLOAD_FILE = "CJ5-LOAN_UPLOAD-PRE_DOWNLOAD_FILE";
  public static final String CJ5_LOAN_UPLOAD_PRE_UPLOAD_FILE = "CJ5-LOAN_UPLOAD-PRE_UPLOAD_FILE";
  public static final String CJ5_LOAN_UPLOAD_UPDATE_STATUS = "CJ5-LOAN_UPLOAD-UPDATE_STATUS";
  public static final String CJ5_LOAN_UPLOAD_DELETE_FILE = "CJ5-LOAN_UPLOAD-DELETE_FILE";
  public static final String CJ5_LOAN_UPLOAD_GET_FILE_CONFIG_CATEGORIES = "CJ5-LOAN_UPLOAD-GET_FILE_CONFIG_CATEGORIES";
  public static final String CJ5_LOAN_UPLOAD_VALIDATE_UPLOAD_FILE = "CJ5-LOAN_UPLOAD-VALIDATE_UPLOAD_FILE";

  public static final String CJ5_MARRIED_PERSON_SAVE = "CJ5-MARRIED_PERSON-SAVE";

  public static final String CJ5_OP_RISK_CHECK_P = "CJ5-OP_RISK-CHECK_P";
  public static final String CJ5_OP_RISK_GET_OP_RISK_INFO = "CJ5-OP_RISK-GET_OP_RISK_INFO";

  public static final String CJ5_ORGANIZATION_GET_BY_TYPE = "CJ5-ORGANIZATION-GET_BY_TYPE";
  public static final String CJ5_ORGANIZATION_GET_BY_AREA = "CJ5-ORGANIZATION-GET_BY_AREA";

  public static final String CJ5_OTHER_EVALUATE_SAVE = "CJ5-OTHER_EVALUATE-SAVE";
  public static final String CJ5_OTHER_EVALUATE_DELETE_BY_ID = "CJ5-OTHER_EVALUATE-DELETE_BY_ID";

  public static final String CJ5_OTHER_INCOMES_SAVE = "CJ5-OTHER_INCOMES-SAVE";
  public static final String CJ5_OTHER_INCOMES_DELETE_BY_ID = "CJ5-OTHER_INCOMES-DELETE_BY_ID";

  public static final String CJ5_ID_CARD_PLACES = "CJ5-ID_CARD-PLACES";

  public static final String CJ5_PROVINCE_FIND_ALL = "CJ5-PROVINCE-FIND_ALL";

  public static final String CJ5_SALARY_INCOMES_SAVE = "CJ5-SALARY_INCOMES-SAVE";
  public static final String CJ5_SALARY_INCOMES_DELETE_BY_ID = "CJ5-SALARY_INCOMES-DELETE_BY_ID";

  public static final String CJ5_TAB_ACTION_GET_BY_LOANID = "CJ5-TAB_ACTION-GET_BY_LOANID";

  public static final String CJ5_UPLOAD_FILE_COMMENT_SAVE = "CJ5-UPLOAD_FILE_COMMENT-SAVE";
  public static final String CJ5_UPLOAD_FILE_COMMENT_UPDATE = "CJ5-UPLOAD_FILE_COMMENT-UPDATE";
  public static final String CJ5_UPLOAD_FILE_COMMENT_DELETE = "CJ5-UPLOAD_FILE_COMMENT-DELETE";
  public static final String CJ5_UPLOAD_FILE_COMMENT_HISTORY = "CJ5-UPLOAD_FILE_COMMENT-HISTORY";

  public static final String CJ5_UPLOAD_FILE_STATUS_SAVE = "CJ5-UPLOAD_FILE_STATUS-SAVE";
  public static final String CJ5_UPLOAD_FILE_STATUS_CHECK_ENOUGH = "CJ5-UPLOAD_FILE_STATUS-CHECK_ENOUGH";

  public static final String CJ5_CMS_USER_FIND_ALL = "CJ5-CMS_USER-FIND_ALL";
  public static final String CJ5_CMS_USER_CREATE = "CJ5-CMS_USER-CREATE";
  public static final String CJ5_CMS_USER_SEARCH = "CJ5-CMS_USER-SEARCH";
  public static final String CJ5_CMS_USER_IMPORT = "CJ5-CMS_USER-IMPORT";

  public static final String CJ5_WARD_FIND_BY_DISTRICT_CODE = "CJ5-WARD-FIND_BY_DISTRICT_CODE";

  public static final String CJ5_CREDIT_INSTITUTION_FIND_ALL = "CJ5-CREDIT_INSTITUTION-FIND_ALL";
}
