create TABLE IF NOT EXISTS `card_policy`
(
    `created_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP,
    `code`       VARCHAR(30) NOT NULL,
    `name`  VARCHAR(250) NOT NULL,
    PRIMARY KEY (`code`)
);

insert into card_policy(code, name) values('card_policy_1', 'QT 1 chạm - M-First DIAMOND');
insert into card_policy(code, name) values('card_policy_2', 'QT 1 chạm - M-First GOLD');
insert into card_policy(code, name) values('card_policy_3', 'QT 1 chạm - M-First PLATINUM');
insert into card_policy(code, name) values('card_policy_4', 'ACB-Card');
insert into card_policy(code, name) values('card_policy_5', 'Apax English- Group 1');
insert into card_policy(code, name) values('card_policy_6', 'Apax English- Group 2');
insert into card_policy(code, name) values('card_policy_7', 'Apax English- Group 3');
insert into card_policy(code, name) values('card_policy_8', 'PD theo QTXH chu truong-R1');
insert into card_policy(code, name) values('card_policy_9', 'PD theo QTXH chu truong -R2');
insert into card_policy(code, name) values('card_policy_10', 'PD theo QTXH chu truong -R3');
insert into card_policy(code, name) values('card_policy_11', 'PD theo QTXH chu truong -R4');
insert into card_policy(code, name) values('card_policy_12', 'PD theo QTXH chu truong -R5');
insert into card_policy(code, name) values('card_policy_13', 'CITI-Card');
insert into card_policy(code, name) values('card_policy_14', 'CHAIN-DAPHACO');
insert into card_policy(code, name) values('card_policy_15', 'CHAIN-DKSH');
insert into card_policy(code, name) values('card_policy_16', 'EX.CARD - KH MF Doi tac than thiet va Trai nghiem – The');
insert into card_policy(code, name) values('card_policy_17', 'EX.FD - KH MF Doi tac than thiet va Trai nghiem – So tiet kiem');
insert into card_policy(code, name) values('card_policy_18', 'EX.INS - KH MF Doi tac than thiet va Trai nghiem – Bao hiem');
insert into card_policy(code, name) values('card_policy_19', 'EX.INV - KH MF Doi tac than thiet va Trai nghiem – Dau tu');
insert into card_policy(code, name) values('card_policy_20', 'DIA.FA - KH MF Hoi vien gia dinh hang Diamond');
insert into card_policy(code, name) values('card_policy_21', 'GOL.FA - KH MF Hoi vien gia dinh hang Gold');
insert into card_policy(code, name) values('card_policy_22', 'PLA.FA - KH MF Hoi vien gia dinh hang Platinum');
insert into card_policy(code, name) values('card_policy_23', 'HSBC-Card');
insert into card_policy(code, name) values('card_policy_24', 'Insurance-Credit Card');
insert into card_policy(code, name) values('card_policy_25', 'LOAN 1 - The chap');
insert into card_policy(code, name) values('card_policy_26', 'LOAN 1 - Tin chap');
insert into card_policy(code, name) values('card_policy_27', 'LOAN 2 - The chap');
insert into card_policy(code, name) values('card_policy_28', 'LOAN 2 - Tin chap');
insert into card_policy(code, name) values('card_policy_29', 'PDT Lotte');
insert into card_policy(code, name) values('card_policy_30', 'M-BUSINESS');
insert into card_policy(code, name) values('card_policy_31', 'MP062');
insert into card_policy(code, name) values('card_policy_32', 'KH M Payroll hien huu CVP');
insert into card_policy(code, name) values('card_policy_33', 'MPAYROLL');
insert into card_policy(code, name) values('card_policy_34', 'MPAYROLL-UP');
insert into card_policy(code, name) values('card_policy_35', 'Thong thuong - A');
insert into card_policy(code, name) values('card_policy_36', 'Thong thuong - B');
insert into card_policy(code, name) values('card_policy_37', 'Thong thuong - C+');
insert into card_policy(code, name) values('card_policy_38', 'Thong thuong - C+040');
insert into card_policy(code, name) values('card_policy_39', 'Thong thuong - GE');
insert into card_policy(code, name) values('card_policy_40', 'Chu the uy tin');
insert into card_policy(code, name) values('card_policy_41', 'DIA.PDT - KH MF Hoi vien chinh thuc hang Diamond');
insert into card_policy(code, name) values('card_policy_42', 'GOL.PDT - KH MF Hoi vien chinh thuc hang Gold');
insert into card_policy(code, name) values('card_policy_43', 'PLA.PDT - KH MF Hoi vien chinh thuc hang Platinum');
insert into card_policy(code, name) values('card_policy_44', 'Quan he tien gui 3 thang');
insert into card_policy(code, name) values('card_policy_45', 'Quan he tien gui 6 thang');
insert into card_policy(code, name) values('card_policy_46', 'PDT chuc danh - C+');
insert into card_policy(code, name) values('card_policy_47', 'PDT chuc danh - C+040');
insert into card_policy(code, name) values('card_policy_48', 'FCB - Thong thuong');
insert into card_policy(code, name) values('card_policy_49', 'FCB - In the truoc');
insert into card_policy(code, name) values('card_policy_50', 'PDT chuc danh - A');
insert into card_policy(code, name) values('card_policy_51', 'PDT chuc danh - B');
insert into card_policy(code, name) values('card_policy_52', 'PDT chuc danh - GE');
insert into card_policy(code, name) values('card_policy_53', 'PDT chuc danh - OTHER');
insert into card_policy(code, name) values('card_policy_54', 'PRE-FLYVIP');
insert into card_policy(code, name) values('card_policy_55', 'M - HOUSING');
insert into card_policy(code, name) values('card_policy_56', 'Sacombank-Card');
insert into card_policy(code, name) values('card_policy_57', 'Salary-AA1');
insert into card_policy(code, name) values('card_policy_58', 'Salary-AA2');
insert into card_policy(code, name) values('card_policy_59', 'Salary-BB1');
insert into card_policy(code, name) values('card_policy_60', 'Salary-BB2');
insert into card_policy(code, name) values('card_policy_61', 'Salary-CC1');
insert into card_policy(code, name) values('card_policy_62', 'Salary-CC2');
insert into card_policy(code, name) values('card_policy_63', 'Salary-GE1');
insert into card_policy(code, name) values('card_policy_64', 'Salary-GE2');
insert into card_policy(code, name) values('card_policy_65', 'SBO online – CHỦ DN KD online');
insert into card_policy(code, name) values('card_policy_66', 'The cam co so tiet kiem');
insert into card_policy(code, name) values('card_policy_67', 'SEGMENT 01');
insert into card_policy(code, name) values('card_policy_68', 'SEGMENT 02');
insert into card_policy(code, name) values('card_policy_69', 'SEGMENT 03');
insert into card_policy(code, name) values('card_policy_70', 'SHINHAN-Card');
insert into card_policy(code, name) values('card_policy_71', 'Lanh dao doanh nghiep SME');
insert into card_policy(code, name) values('card_policy_72', 'DIA.SPE.PDT - KH MF Hoi vien dac biet hang Diamond');
insert into card_policy(code, name) values('card_policy_73', 'GOL.SPE - KH MF Hoi vien dac biet hang Gold');
insert into card_policy(code, name) values('card_policy_74', 'PLA.SPE - KH MF Hoi vien dac biet hang Platinum');
insert into card_policy(code, name) values('card_policy_75', 'CBNV tham dinh phe duyet');
insert into card_policy(code, name) values('card_policy_76', 'Can bo nhan vien');
insert into card_policy(code, name) values('card_policy_77', 'TCB-Card');
insert into card_policy(code, name) values('card_policy_78', 'Du an TNR');
insert into card_policy(code, name) values('card_policy_79', 'VCB-Card');
insert into card_policy(code, name) values('card_policy_80', 'Khach hang VIP');
insert into card_policy(code, name) values('card_policy_81', 'VLCs- Leaders');
insert into card_policy(code, name) values('card_policy_82', 'VLCs- Staffs');
insert into card_policy(code, name) values('card_policy_83', 'VLCs- Parents');
insert into card_policy(code, name) values('card_policy_84', 'VLCs- Post graduates');
insert into card_policy(code, name) values('card_policy_85', 'CHAIN-VMD');
insert into card_policy(code, name) values('card_policy_86', 'PDT Vpoint');
insert into card_policy(code, name) values('card_policy_87', 'PDT Vpoint VNPT');
insert into card_policy(code, name) values('card_policy_88', 'Thẻ tín dụng giáo dục  – Lãnh đạo chủ chốt');
insert into card_policy(code, name) values('card_policy_89', 'Thẻ tín dụng giáo dục  – CBNV Giảng viên');
insert into card_policy(code, name) values('card_policy_90', 'Thẻ tín dụng giáo dục - Phụ huynh học sinh sinh viên');
insert into card_policy(code, name) values('card_policy_91', 'Thẻ tín dụng giáo dục - Sinh viên sau đại học');
insert into card_policy(code, name) values('card_policy_92', 'SBO-Card');
insert into card_policy(code, name) values('card_policy_93', 'Bamboo-Gold');
insert into card_policy(code, name) values('card_policy_94', 'Bamboo-Diamond');
insert into card_policy(code, name) values('card_policy_95', 'Bamboo-First');
insert into card_policy(code, name) values('card_policy_96', 'Insurance-Credit Card - First Year');
insert into card_policy(code, name) values('card_policy_97', 'Insurance-Credit Card');
insert into card_policy(code, name) values('card_policy_98', 'Thẻ tín dụng đối tác – phụ huynh');
insert into card_policy(code, name) values('card_policy_99', 'Thẻ tín dụng đối tác - học viên');
insert into card_policy(code, name) values('card_policy_100', 'Salary-PDT');
insert into card_policy(code, name) values('card_policy_101', 'EX.AUM – KH MF Doi tac than thiet va Trai nghiem – Tong tai san');
insert into card_policy(code, name) values('card_policy_102', 'DF-HSBC-Card');
insert into card_policy(code, name) values('card_policy_103', 'DF-Citibank-Card');
insert into card_policy(code, name) values('card_policy_104', 'DF-Shinhan bank-Card');
insert into card_policy(code, name) values('card_policy_105', 'DF-Vietcombank-Card');
insert into card_policy(code, name) values('card_policy_106', 'DF-Techcombank-Card');
insert into card_policy(code, name) values('card_policy_107', 'DF-Sacombank-Card');
insert into card_policy(code, name) values('card_policy_108', 'DF-ACB-Card');
insert into card_policy(code, name) values('card_policy_109', 'DF-Insurance-Credit Card by MSB');
insert into card_policy(code, name) values('card_policy_110', 'DF-Insurance-Credit Card non MSB');
insert into card_policy(code, name) values('card_policy_111', 'DF-Salary');
insert into card_policy(code, name) values('card_policy_112', 'MF.VIP – KH VIP');
insert into card_policy(code, name) values('card_policy_113', 'DF-Hocvien-NH Credit card online');
insert into card_policy(code, name) values('card_policy_114', 'DF-Phuhuynh-NH Credit card online');
insert into card_policy(code, name) values('card_policy_115', 'PD theo QTXH chu truong - Một chạm');
insert into card_policy(code, name) values('card_policy_116', 'Thẻ tín dụng Nguyễn Hoàng – Một chạm');
insert into card_policy(code, name) values('card_policy_117', 'Thẻ tín dụng đối tác Nguyễn Hoàng theo diện VIP -Một chạm');
insert into card_policy(code, name) values('card_policy_118', 'Thẻ tín dụng đối tác Giao duc.vn – Phụ huynh');
insert into card_policy(code, name) values('card_policy_119', 'Thẻ tín dụng đối tác Giao duc.vn – Học viên');
insert into card_policy(code, name) values('card_policy_120', 'Thẻ tín dụng đối tác Nguyễn Hoàng – Phụ huynh');
insert into card_policy(code, name) values('card_policy_121', 'Thẻ tín dụng đối tác Nguyễn Hoàng – Học viên');
insert into card_policy(code, name) values('card_policy_122', 'Thẻ tín dụng cấp kèm khoản vay kinh doanh QĐ.RB.008');
insert into card_policy(code, name) values('card_policy_123', 'Thẻ tín dụng đối tác Công ty CP Global – Phụ huynh');
insert into card_policy(code, name) values('card_policy_124', 'Thẻ tín dụng đối tác Công ty CP Global – Học viên');
insert into card_policy(code, name) values('card_policy_125', 'Salary-CC3');
insert into card_policy(code, name) values('card_policy_126', 'Thẻ tín dụng cho KH staff-linked');