update district set mvalue_code = '20', mvalue_name= 'Ba Đình' where code = '001';
update district set mvalue_code = '25', mvalue_name= 'Hoàn Kiếm' where code = '002';
update district set mvalue_code = '28', mvalue_name= 'Tây Hồ' where code = '003';
update district set mvalue_code = '27', mvalue_name= 'Long Biên' where code = '004';
update district set mvalue_code = '21', mvalue_name= 'Cầu Giấy' where code = '005';
update district set mvalue_code = '22', mvalue_name= 'Đống Đa' where code = '006';
update district set mvalue_code = '24', mvalue_name= 'Hai Bà Trưng' where code = '007';
update district set mvalue_code = '26', mvalue_name= 'Hoàng Mai' where code = '008';
update district set mvalue_code = '29', mvalue_name= 'Thanh Xuân' where code = '009';
update district set mvalue_code = '13', mvalue_name= 'Sóc Sơn' where code = '016';
update district set mvalue_code = '5', mvalue_name= 'Đông Anh' where code = '017';
update district set mvalue_code = '6', mvalue_name= 'Gia Lâm' where code = '018';
update district set mvalue_code = '707', mvalue_name= 'Nam Từ Liêm' where code = '019';
update district set mvalue_code = '16', mvalue_name= 'Thanh Trì' where code = '020';
update district set mvalue_code = '717', mvalue_name= 'Bắc Từ Liêm' where code = '021';
update district set mvalue_code = '272', mvalue_name= 'Hà Giang' where code = '024';
update district set mvalue_code = '264', mvalue_name= 'Đồng Văn' where code = '026';
update district set mvalue_code = '266', mvalue_name= 'Mèo Vạc' where code = '027';
update district set mvalue_code = '271', mvalue_name= 'Yên Minh' where code = '028';
update district set mvalue_code = '267', mvalue_name= 'Quản Bạ' where code = '029';
update district set mvalue_code = '269', mvalue_name= 'Vị Xuyên' where code = '030';
update district set mvalue_code = '262', mvalue_name= 'Bắc Mê' where code = '031';
update district set mvalue_code = '265', mvalue_name= 'Hoàng Su Phì' where code = '032';
update district set mvalue_code = '270', mvalue_name= 'Xín Mần' where code = '033';
update district set mvalue_code = '263', mvalue_name= 'Bắc Quang' where code = '034';
update district set mvalue_code = '268', mvalue_name= 'Quang Bình' where code = '035';
update district set mvalue_code = '182', mvalue_name= 'Cao Bằng' where code = '040';
update district set mvalue_code = '181', mvalue_name= 'Huyện Bảo Lâm' where code = '042';
update district set mvalue_code = '170', mvalue_name= 'Bảo Lạc' where code = '043';
update district set mvalue_code = '172', mvalue_name= 'Hà Quảng' where code = '045';
update district set mvalue_code = '180', mvalue_name= 'Trùng Khánh' where code = '047';
update district set mvalue_code = '171', mvalue_name= 'Hạ Lang' where code = '048';
update district set mvalue_code = '176', mvalue_name= 'Quảng Uyên' where code = '049';
update district set mvalue_code = '173', mvalue_name= 'Hoà An' where code = '051';
update district set mvalue_code = '174', mvalue_name= 'Nguyên Bình' where code = '052';
update district set mvalue_code = '177', mvalue_name= 'Thạch An' where code = '053';
update district set mvalue_code = '81', mvalue_name= 'Bắc Kạn' where code = '058';
update district set mvalue_code = '80', mvalue_name= 'Pác Nặm' where code = '060';
update district set mvalue_code = '74', mvalue_name= 'Ba Bể' where code = '061';
update district set mvalue_code = '79', mvalue_name= 'Ngân Sơn' where code = '062';
update district set mvalue_code = '75', mvalue_name= 'Bạch Thông' where code = '063';
update district set mvalue_code = '76', mvalue_name= 'Chợ Đồn' where code = '064';
update district set mvalue_code = '77', mvalue_name= 'Huyện Chợ Mới' where code = '065';
update district set mvalue_code = '78', mvalue_name= 'Na Rì' where code = '066';
update district set mvalue_code = '667', mvalue_name= 'Tuyên Quang' where code = '070';
update district set mvalue_code = '750', mvalue_name= 'Lâm Bình' where code = '071';
update district set mvalue_code = '764', mvalue_name= 'Na Hang' where code = '072';
update district set mvalue_code = '662', mvalue_name= 'Chiêm Hóa' where code = '073';
update district set mvalue_code = '663', mvalue_name= 'Hàm Yên' where code = '074';
update district set mvalue_code = '666', mvalue_name= 'Yên Sơn' where code = '075';
update district set mvalue_code = '665', mvalue_name= 'Sơn Dương' where code = '076';
update district set mvalue_code = '416', mvalue_name= 'Lào Cai' where code = '080';
update district set mvalue_code = '411', mvalue_name= 'Bát Xát' where code = '082';
update district set mvalue_code = '412', mvalue_name= 'Mường Khương' where code = '083';
update district set mvalue_code = '414', mvalue_name= 'Si Ma Cai' where code = '084';
update district set mvalue_code = '408', mvalue_name= 'Bắc Hà' where code = '085';
update district set mvalue_code = '409', mvalue_name= 'Bảo Thắng' where code = '086';
update district set mvalue_code = '410', mvalue_name= 'Bảo Yên' where code = '087';
update district set mvalue_code = '413', mvalue_name= 'Sa Pa' where code = '088';
update district set mvalue_code = '415', mvalue_name= 'Văn Bàn' where code = '089';
update district set mvalue_code = '221', mvalue_name= 'Điện Biên Phủ' where code = '094';
update district set mvalue_code = '222', mvalue_name= 'Mường Lay' where code = '095';
update district set mvalue_code = '218', mvalue_name= 'Mường Nhé' where code = '096';
update district set mvalue_code = '217', mvalue_name= 'Mường Chà' where code = '097';
update district set mvalue_code = '219', mvalue_name= 'Tủa Chùa' where code = '098';
update district set mvalue_code = '220', mvalue_name= 'Tuần Giáo' where code = '099';
update district set mvalue_code = '214', mvalue_name= 'Điện Biên' where code = '100';
update district set mvalue_code = '215', mvalue_name= 'Điện Biên Đông' where code = '101';
update district set mvalue_code = '216', mvalue_name= 'Mường ảng' where code = '102';
update district set mvalue_code = '753', mvalue_name= 'Nậm Pồ' where code = '103';
update district set mvalue_code = '384', mvalue_name= 'Lai Châu' where code = '105';
update district set mvalue_code = '381', mvalue_name= 'Tam Đường' where code = '106';
update district set mvalue_code = '378', mvalue_name= 'Mường Tè' where code = '107';
update district set mvalue_code = '380', mvalue_name= 'Sìn Hồ' where code = '108';
update district set mvalue_code = '379', mvalue_name= 'Phong Thổ' where code = '109';
update district set mvalue_code = '383', mvalue_name= 'Than Uyên' where code = '110';
update district set mvalue_code = '382', mvalue_name= 'Tân Uyên' where code = '111';
update district set mvalue_code = '752', mvalue_name= 'Nậm Nhùn' where code = '112';
update district set mvalue_code = '581', mvalue_name= 'Sơn La' where code = '116';
update district set mvalue_code = '576', mvalue_name= 'Quỳnh Nhai' where code = '118';
update district set mvalue_code = '579', mvalue_name= 'Thuận Châu' where code = '119';
update district set mvalue_code = '574', mvalue_name= 'Mường La' where code = '120';
update district set mvalue_code = '571', mvalue_name= 'Bắc Yên' where code = '121';
update district set mvalue_code = '575', mvalue_name= 'Phù Yên' where code = '122';
update district set mvalue_code = '573', mvalue_name= 'Mộc Châu' where code = '123';
update district set mvalue_code = '580', mvalue_name= 'Yên Châu' where code = '124';
update district set mvalue_code = '572', mvalue_name= 'Mai Sơn' where code = '125';
update district set mvalue_code = '577', mvalue_name= 'Sông Mã' where code = '126';
update district set mvalue_code = '578', mvalue_name= 'Sốp Cộp' where code = '127';
update district set mvalue_code = '757', mvalue_name= 'Vân Hồ' where code = '128';
update district set mvalue_code = '692', mvalue_name= 'Yên Bái' where code = '132';
update district set mvalue_code = '693', mvalue_name= 'Nghĩa Lộ' where code = '133';
update district set mvalue_code = '685', mvalue_name= 'Lục Yên' where code = '135';
update district set mvalue_code = '690', mvalue_name= 'Văn Yên' where code = '136';
update district set mvalue_code = '686', mvalue_name= 'Mù Cang Chải' where code = '137';
update district set mvalue_code = '688', mvalue_name= 'Trấn Yên' where code = '138';
update district set mvalue_code = '687', mvalue_name= 'Trạm Tấu' where code = '139';
update district set mvalue_code = '689', mvalue_name= 'Văn Chấn' where code = '140';
update district set mvalue_code = '691', mvalue_name= 'Yên Bình' where code = '141';
update district set mvalue_code = '335', mvalue_name= 'Thành phố Hòa Bình' where code = '148';
update district set mvalue_code = '326', mvalue_name= 'Đà Bắc' where code = '150';
update district set mvalue_code = '331', mvalue_name= 'Lương Sơn' where code = '152';
update district set mvalue_code = '327', mvalue_name= 'Kim Bôi' where code = '153';
update district set mvalue_code = '325', mvalue_name= 'Cao Phong' where code = '154';
update district set mvalue_code = '333', mvalue_name= 'Tân Lạc' where code = '155';
update district set mvalue_code = '332', mvalue_name= 'Mai Châu' where code = '156';
update district set mvalue_code = '329', mvalue_name= 'Lạc Sơn' where code = '157';
update district set mvalue_code = '334', mvalue_name= 'Yên Thủy' where code = '158';
update district set mvalue_code = '330', mvalue_name= 'Lạc Thủy' where code = '159';
update district set mvalue_code = '606', mvalue_name= 'Thái Nguyên' where code = '164';
update district set mvalue_code = '607', mvalue_name= 'Sông Công' where code = '165';
update district set mvalue_code = '600', mvalue_name= 'Định Hóa' where code = '167';
update district set mvalue_code = '604', mvalue_name= 'Phú Lương' where code = '168';
update district set mvalue_code = '601', mvalue_name= 'Đồng Hỷ' where code = '169';
update district set mvalue_code = '605', mvalue_name= 'Võ Nhai' where code = '170';
update district set mvalue_code = '599', mvalue_name= 'Đại Từ' where code = '171';
update district set mvalue_code = '602', mvalue_name= 'Phổ Yên' where code = '172';
update district set mvalue_code = '603', mvalue_name= 'Phú Bình' where code = '173';
update district set mvalue_code = '407', mvalue_name= 'Lạng Sơn' where code = '178';
update district set mvalue_code = '404', mvalue_name= 'Tràng Định' where code = '180';
update district set mvalue_code = '398', mvalue_name= 'Bình Gia' where code = '181';
update district set mvalue_code = '405', mvalue_name= 'Văn Lãng' where code = '182';
update district set mvalue_code = '399', mvalue_name= 'Cao Lộc' where code = '183';
update district set mvalue_code = '406', mvalue_name= 'Văn Quan' where code = '184';
update district set mvalue_code = '397', mvalue_name= 'Bắc Sơn' where code = '185';
update district set mvalue_code = '402', mvalue_name= 'Hữu Lũng' where code = '186';
update district set mvalue_code = '400', mvalue_name= 'Chi Lăng' where code = '187';
update district set mvalue_code = '403', mvalue_name= 'Lộc Bình' where code = '188';
update district set mvalue_code = '401', mvalue_name= 'Đình Lập' where code = '189';
update district set mvalue_code = '547', mvalue_name= 'Hạ Long' where code = '193';
update district set mvalue_code = '548', mvalue_name= 'Móng Cái' where code = '194';
update district set mvalue_code = '549', mvalue_name= 'Cẩm Phả' where code = '195';
update district set mvalue_code = '550', mvalue_name= 'Uông Bí' where code = '196';
update district set mvalue_code = '538', mvalue_name= 'Bình Liêu' where code = '198';
update district set mvalue_code = '544', mvalue_name= 'Tiên Yên' where code = '199';
update district set mvalue_code = '540', mvalue_name= 'Đầm Hà' where code = '200';
update district set mvalue_code = '542', mvalue_name= 'Hải Hà' where code = '201';
update district set mvalue_code = '537', mvalue_name= 'Ba Chẽ' where code = '202';
update district set mvalue_code = '545', mvalue_name= 'Vân Đồn' where code = '203';
update district set mvalue_code = '541', mvalue_name= 'Đông Triều' where code = '205';
update district set mvalue_code = '756', mvalue_name= 'Quảng Yên' where code = '206';
update district set mvalue_code = '539', mvalue_name= 'Cô Tô' where code = '207';
update district set mvalue_code = '91', mvalue_name= 'Bắc Giang' where code = '213';
update district set mvalue_code = '90', mvalue_name= 'Yên Thế' where code = '215';
update district set mvalue_code = '87', mvalue_name= 'Tân Yên' where code = '216';
update district set mvalue_code = '83', mvalue_name= 'Lạng Giang' where code = '217';
update district set mvalue_code = '84', mvalue_name= 'Lục Nam' where code = '218';
update district set mvalue_code = '85', mvalue_name= 'Lục Ngạn' where code = '219';
update district set mvalue_code = '86', mvalue_name= 'Sơn Động' where code = '220';
update district set mvalue_code = '89', mvalue_name= 'Yên Dũng' where code = '221';
update district set mvalue_code = '88', mvalue_name= 'Việt Yên' where code = '222';
update district set mvalue_code = '82', mvalue_name= 'Hiệp Hòa' where code = '223';
update district set mvalue_code = '487', mvalue_name= 'Việt Trì' where code = '227';
update district set mvalue_code = '488', mvalue_name= 'Phú Thọ' where code = '228';
update district set mvalue_code = '477', mvalue_name= 'Đoan Hùng' where code = '230';
update district set mvalue_code = '478', mvalue_name= 'Hạ Hoà' where code = '231';
update district set mvalue_code = '483', mvalue_name= 'Thanh Ba' where code = '232';
update district set mvalue_code = '480', mvalue_name= 'Phù Ninh' where code = '233';
update district set mvalue_code = '486', mvalue_name= 'Yên Lập' where code = '234';
update district set mvalue_code = '476', mvalue_name= 'Cẩm Khê' where code = '235';
update district set mvalue_code = '481', mvalue_name= 'Tam Nông' where code = '236';
update district set mvalue_code = '479', mvalue_name= 'Lâm Thao' where code = '237';
update district set mvalue_code = '484', mvalue_name= 'Thanh Sơn' where code = '238';
update district set mvalue_code = '485', mvalue_name= 'Thanh Thuỷ' where code = '239';
update district set mvalue_code = '482', mvalue_name= 'Tân Sơn' where code = '240';
update district set mvalue_code = '683', mvalue_name= 'Vĩnh Yên' where code = '243';
update district set mvalue_code = '684', mvalue_name= 'Phúc Yên' where code = '244';
update district set mvalue_code = '677', mvalue_name= 'Lập Thạch' where code = '246';
update district set mvalue_code = '680', mvalue_name= 'Tam Dương' where code = '247';
update district set mvalue_code = '679', mvalue_name= 'Tam Đảo' where code = '248';
update district set mvalue_code = '676', mvalue_name= 'Bình Xuyên' where code = '249';
update district set mvalue_code = '8', mvalue_name= 'Mê Linh' where code = '250';
update district set mvalue_code = '682', mvalue_name= 'Yên Lạc' where code = '251';
update district set mvalue_code = '681', mvalue_name= 'Vĩnh Tường' where code = '252';
update district set mvalue_code = '678', mvalue_name= 'Sông Lô' where code = '253';
update district set mvalue_code = '105', mvalue_name= 'Bắc Ninh' where code = '256';
update district set mvalue_code = '104', mvalue_name= 'Yên Phong' where code = '258';
update district set mvalue_code = '101', mvalue_name= 'Quế Võ' where code = '259';
update district set mvalue_code = '103', mvalue_name= 'Tiên Du' where code = '260';
update district set mvalue_code = '106', mvalue_name= 'Từ Sơn' where code = '261';
update district set mvalue_code = '102', mvalue_name= 'Thuận Thành' where code = '262';
update district set mvalue_code = '99', mvalue_name= 'Gia Bình' where code = '263';
update district set mvalue_code = '100', mvalue_name= 'Lương Tài' where code = '264';
update district set mvalue_code = '23', mvalue_name= 'Hà Đông' where code = '268';
update district set mvalue_code = '30', mvalue_name= 'Thị xã Sơn Tây' where code = '269';
update district set mvalue_code = '2', mvalue_name= 'Ba Vì' where code = '271';
update district set mvalue_code = '11', mvalue_name= 'Phúc Thọ' where code = '272';
update district set mvalue_code = '4', mvalue_name= 'Đan Phượng' where code = '273';
update district set mvalue_code = '7', mvalue_name= 'Hoài Đức' where code = '274';
update district set mvalue_code = '12', mvalue_name= 'Quốc Oai' where code = '275';
update district set mvalue_code = '14', mvalue_name= 'Thạch Thất' where code = '276';
update district set mvalue_code = '3', mvalue_name= 'Chương Mỹ' where code = '277';
update district set mvalue_code = '15', mvalue_name= 'Thanh Oai' where code = '278';
update district set mvalue_code = '17', mvalue_name= 'Thường Tín' where code = '279';
update district set mvalue_code = '10', mvalue_name= 'Phú Xuyên' where code = '280';
update district set mvalue_code = '19', mvalue_name= 'Ứng Hòa' where code = '281';
update district set mvalue_code = '751', mvalue_name= 'Mỹ Đức' where code = '282';
update district set mvalue_code = '302', mvalue_name= 'Hải Dương' where code = '288';
update district set mvalue_code = '293', mvalue_name= 'Chí Linh' where code = '290';
update district set mvalue_code = '297', mvalue_name= 'Nam Sách' where code = '291';
update district set mvalue_code = '296', mvalue_name= 'Kinh Môn' where code = '292';
update district set mvalue_code = '295', mvalue_name= 'Kim Thành' where code = '293';
update district set mvalue_code = '299', mvalue_name= 'Thanh Hà' where code = '294';
update district set mvalue_code = '292', mvalue_name= 'Cẩm Giàng' where code = '295';
update district set mvalue_code = '291', mvalue_name= 'Bình Giang' where code = '296';
update district set mvalue_code = '294', mvalue_name= 'Gia Lộc' where code = '297';
update district set mvalue_code = '301', mvalue_name= 'Tứ Kỳ' where code = '298';
update district set mvalue_code = '298', mvalue_name= 'Ninh Giang' where code = '299';
update district set mvalue_code = '300', mvalue_name= 'Thanh Miện' where code = '300';
update district set mvalue_code = '314', mvalue_name= 'Hồng Bàng' where code = '303';
update district set mvalue_code = '317', mvalue_name= 'Ngô Quyền' where code = '304';
update district set mvalue_code = '316', mvalue_name= 'Lê Chân' where code = '305';
update district set mvalue_code = '313', mvalue_name= 'Hải An' where code = '306';
update district set mvalue_code = '315', mvalue_name= 'Kiến An' where code = '307';
update district set mvalue_code = '311', mvalue_name= 'Đồ Sơn' where code = '308';
update district set mvalue_code = '718', mvalue_name= 'Dương Kinh' where code = '309';
update district set mvalue_code = '308', mvalue_name= 'Thuỷ Nguyên' where code = '311';
update district set mvalue_code = '303', mvalue_name= 'An Dương' where code = '312';
update district set mvalue_code = '304', mvalue_name= 'Huyện An Lão' where code = '313';
update district set mvalue_code = '307', mvalue_name= 'Kiến Thuỵ' where code = '314';
update district set mvalue_code = '309', mvalue_name= 'Tiên Lãng' where code = '315';
update district set mvalue_code = '310', mvalue_name= 'Vĩnh Bảo' where code = '316';
update district set mvalue_code = '306', mvalue_name= 'Cát Hải' where code = '317';
update district set mvalue_code = '305', mvalue_name= 'Bạch Long Vĩ' where code = '318';
update district set mvalue_code = '345', mvalue_name= 'Hưng Yên' where code = '323';
update district set mvalue_code = '343', mvalue_name= 'Văn Lâm' where code = '325';
update district set mvalue_code = '342', mvalue_name= 'Văn Giang' where code = '326';
update district set mvalue_code = '344', mvalue_name= 'Yên Mỹ' where code = '327';
update district set mvalue_code = '339', mvalue_name= 'Mỹ Hào' where code = '328';
update district set mvalue_code = '336', mvalue_name= 'Ân Thi' where code = '329';
update district set mvalue_code = '337', mvalue_name= 'Khoái Châu' where code = '330';
update district set mvalue_code = '338', mvalue_name= 'Kim Động' where code = '331';
update district set mvalue_code = '341', mvalue_name= 'Tiên Lữ' where code = '332';
update district set mvalue_code = '340', mvalue_name= 'Phù Cừ' where code = '333';
update district set mvalue_code = '598', mvalue_name= 'Thái Bình' where code = '336';
update district set mvalue_code = '594', mvalue_name= 'Quỳnh Phụ' where code = '338';
update district set mvalue_code = '592', mvalue_name= 'Hưng Hà' where code = '339';
update district set mvalue_code = '591', mvalue_name= 'Đông Hưng' where code = '340';
update district set mvalue_code = '595', mvalue_name= 'Thái Thụy' where code = '341';
update district set mvalue_code = '596', mvalue_name= 'Tiền Hải' where code = '342';
update district set mvalue_code = '593', mvalue_name= 'Kiến Xương' where code = '343';
update district set mvalue_code = '597', mvalue_name= 'Vũ Thư' where code = '344';
update district set mvalue_code = '278', mvalue_name= 'Phủ Lý' where code = '347';
update district set mvalue_code = '274', mvalue_name= 'Duy Tiên' where code = '349';
update district set mvalue_code = '275', mvalue_name= 'Kim Bảng' where code = '350';
update district set mvalue_code = '277', mvalue_name= 'Thanh Liêm' where code = '351';
update district set mvalue_code = '273', mvalue_name= 'Bình Lục' where code = '352';
update district set mvalue_code = '276', mvalue_name= 'Lý Nhân' where code = '353';
update district set mvalue_code = '440', mvalue_name= 'Nam Định' where code = '356';
update district set mvalue_code = '433', mvalue_name= 'Mỹ Lộc' where code = '358';
update district set mvalue_code = '437', mvalue_name= 'Vụ Bản' where code = '359';
update district set mvalue_code = '439', mvalue_name= 'Ý Yên' where code = '360';
update district set mvalue_code = '435', mvalue_name= 'Nghĩa Hưng' where code = '361';
update district set mvalue_code = '434', mvalue_name= 'Nam Trực' where code = '362';
update district set mvalue_code = '436', mvalue_name= 'Trực Ninh' where code = '363';
update district set mvalue_code = '438', mvalue_name= 'Xuân Trường' where code = '364';
update district set mvalue_code = '431', mvalue_name= 'Giao Thủy' where code = '365';
update district set mvalue_code = '432', mvalue_name= 'Hải Hậu' where code = '366';
update district set mvalue_code = '467', mvalue_name= 'Ninh Bình' where code = '369';
update district set mvalue_code = '468', mvalue_name= 'Tam Điệp' where code = '370';
update district set mvalue_code = '464', mvalue_name= 'Nho Quan' where code = '372';
update district set mvalue_code = '461', mvalue_name= 'Gia Viễn' where code = '373';
update district set mvalue_code = '462', mvalue_name= 'Hoa Lư' where code = '374';
update district set mvalue_code = '465', mvalue_name= 'Yên Khánh' where code = '375';
update district set mvalue_code = '463', mvalue_name= 'Kim Sơn' where code = '376';
update district set mvalue_code = '466', mvalue_name= 'Yên Mô' where code = '377';
update district set mvalue_code = '632', mvalue_name= 'Thanh Hóa' where code = '380';
update district set mvalue_code = '633', mvalue_name= 'Bỉm Sơn' where code = '381';
update district set mvalue_code = '634', mvalue_name= 'Sầm Sơn' where code = '382';
update district set mvalue_code = '615', mvalue_name= 'Mường Lát' where code = '384';
update district set mvalue_code = '621', mvalue_name= 'Quan Hóa' where code = '385';
update district set mvalue_code = '608', mvalue_name= 'Bá Thước' where code = '386';
update district set mvalue_code = '622', mvalue_name= 'Quan Sơn' where code = '387';
update district set mvalue_code = '614', mvalue_name= 'Lang Chánh' where code = '388';
update district set mvalue_code = '617', mvalue_name= 'Ngọc Lặc' where code = '389';
update district set mvalue_code = '609', mvalue_name= 'Cẩm Thủy' where code = '390';
update district set mvalue_code = '624', mvalue_name= 'Thạch Thành' where code = '391';
update district set mvalue_code = '611', mvalue_name= 'Hà Trung' where code = '392';
update district set mvalue_code = '630', mvalue_name= 'Vĩnh Lộc' where code = '393';
update district set mvalue_code = '631', mvalue_name= 'Yên Định' where code = '394';
update district set mvalue_code = '626', mvalue_name= 'Thọ Xuân' where code = '395';
update district set mvalue_code = '627', mvalue_name= 'Thường Xuân' where code = '396';
update district set mvalue_code = '629', mvalue_name= 'Triệu Sơn' where code = '397';
update district set mvalue_code = '805', mvalue_name= 'Thiệu Hóa' where code = '398';
update district set mvalue_code = '613', mvalue_name= 'Hoằng Hóa' where code = '399';
update district set mvalue_code = '612', mvalue_name= 'Hậu Lộc' where code = '400';
update district set mvalue_code = '616', mvalue_name= 'Nga Sơn' where code = '401';
update district set mvalue_code = '619', mvalue_name= 'Như Xuân' where code = '402';
update district set mvalue_code = '618', mvalue_name= 'Như Thanh' where code = '403';
update district set mvalue_code = '620', mvalue_name= 'Nông Cống' where code = '404';
update district set mvalue_code = '610', mvalue_name= 'Đông Sơn' where code = '405';
update district set mvalue_code = '623', mvalue_name= 'Quảng Xương' where code = '406';
update district set mvalue_code = '628', mvalue_name= 'Tĩnh Gia' where code = '407';
update district set mvalue_code = '458', mvalue_name= 'Vinh' where code = '412';
update district set mvalue_code = '459', mvalue_name= 'Cửa Lò' where code = '413';
update district set mvalue_code = '460', mvalue_name= 'Thái Hoà' where code = '414';
update district set mvalue_code = '450', mvalue_name= 'Quế Phong' where code = '415';
update district set mvalue_code = '451', mvalue_name= 'Quỳ Châu' where code = '416';
update district set mvalue_code = '328', mvalue_name= 'Kỳ Sơn' where code = '417';
update district set mvalue_code = '456', mvalue_name= 'Tương Dương' where code = '418';
update district set mvalue_code = '449', mvalue_name= 'Nghĩa Đàn' where code = '419';
update district set mvalue_code = '452', mvalue_name= 'Quỳ Hợp' where code = '420';
update district set mvalue_code = '453', mvalue_name= 'Quỳnh Lưu' where code = '421';
update district set mvalue_code = '442', mvalue_name= 'Con Cuông' where code = '422';
update district set mvalue_code = '454', mvalue_name= 'Tân Kỳ' where code = '423';
update district set mvalue_code = '441', mvalue_name= 'Anh Sơn' where code = '424';
update district set mvalue_code = '443', mvalue_name= 'Diễn Châu' where code = '425';
update district set mvalue_code = '457', mvalue_name= 'Yên Thành' where code = '426';
update district set mvalue_code = '444', mvalue_name= 'Đô Lương' where code = '427';
update district set mvalue_code = '455', mvalue_name= 'Thanh Chương' where code = '428';
update district set mvalue_code = '448', mvalue_name= 'Nghi Lộc' where code = '429';
update district set mvalue_code = '447', mvalue_name= 'Nam Đàn' where code = '430';
update district set mvalue_code = '445', mvalue_name= 'Hưng Nguyên' where code = '431';
update district set mvalue_code = '784', mvalue_name= 'Thị xã Hoàng Mai' where code = '432';
update district set mvalue_code = '289', mvalue_name= 'Hà Tĩnh' where code = '436';
update district set mvalue_code = '290', mvalue_name= 'Hồng Lĩnh' where code = '437';
update district set mvalue_code = '283', mvalue_name= 'Hương Sơn' where code = '439';
update district set mvalue_code = '281', mvalue_name= 'Đức Thọ' where code = '440';
update district set mvalue_code = '288', mvalue_name= 'Vũ Quang' where code = '441';
update district set mvalue_code = '286', mvalue_name= 'Nghi Xuân' where code = '442';
update district set mvalue_code = '280', mvalue_name= 'Can Lộc' where code = '443';
update district set mvalue_code = '282', mvalue_name= 'Hương Khê' where code = '444';
update district set mvalue_code = '287', mvalue_name= 'Thạch Hà' where code = '445';
update district set mvalue_code = '279', mvalue_name= 'Cẩm Xuyên' where code = '446';
update district set mvalue_code = '284', mvalue_name= 'Kỳ Anh' where code = '447';
update district set mvalue_code = '285', mvalue_name= 'Lộc Hà' where code = '448';
update district set mvalue_code = '284', mvalue_name= 'Kỳ Anh' where code = '449';
update district set mvalue_code = '504', mvalue_name= 'Đồng Hới' where code = '450';
update district set mvalue_code = '500', mvalue_name= 'Minh Hóa' where code = '452';
update district set mvalue_code = '503', mvalue_name= 'Tuyên Hóa' where code = '453';
update district set mvalue_code = '502', mvalue_name= 'Quảng Trạch' where code = '454';
update district set mvalue_code = '498', mvalue_name= 'Bố Trạch' where code = '455';
update district set mvalue_code = '501', mvalue_name= 'Quảng Ninh' where code = '456';
update district set mvalue_code = '499', mvalue_name= 'Lệ Thủy' where code = '457';
update district set mvalue_code = '744', mvalue_name= 'Ba Đồn' where code = '458';
update district set mvalue_code = '559', mvalue_name= 'Đông Hà' where code = '461';
update district set mvalue_code = '560', mvalue_name= 'Quảng Trị' where code = '462';
update district set mvalue_code = '558', mvalue_name= 'Vĩnh Linh' where code = '464';
update district set mvalue_code = '556', mvalue_name= 'Hướng Hóa' where code = '465';
update district set mvalue_code = '554', mvalue_name= 'Gio Linh' where code = '466';
update district set mvalue_code = '552', mvalue_name= 'Đa Krông' where code = '467';
update district set mvalue_code = '551', mvalue_name= 'Cam Lộ' where code = '468';
update district set mvalue_code = '557', mvalue_name= 'Triệu Phong' where code = '469';
update district set mvalue_code = '555', mvalue_name= 'Hải Lăng' where code = '470';
update district set mvalue_code = '553', mvalue_name= 'Cồn Cỏ' where code = '471';
update district set mvalue_code = '643', mvalue_name= 'Huế' where code = '474';
update district set mvalue_code = '639', mvalue_name= 'Huyện Phong Điền' where code = '476';
update district set mvalue_code = '642', mvalue_name= 'Quảng Điền' where code = '477';
update district set mvalue_code = '641', mvalue_name= 'Phú Vang' where code = '478';
update district set mvalue_code = '636', mvalue_name= 'Hương Thủy' where code = '479';
update district set mvalue_code = '637', mvalue_name= 'Hương Trà' where code = '480';
update district set mvalue_code = '635', mvalue_name= 'A Lưới' where code = '481';
update district set mvalue_code = '640', mvalue_name= 'Phú Lộc' where code = '482';
update district set mvalue_code = '638', mvalue_name= 'Nam Đông' where code = '483';
update district set mvalue_code = '187', mvalue_name= 'Liên Chiểu' where code = '490';
update district set mvalue_code = '190', mvalue_name= 'Thanh Khê' where code = '491';
update district set mvalue_code = '186', mvalue_name= 'Hải Châu' where code = '492';
update district set mvalue_code = '189', mvalue_name= 'Sơn Trà' where code = '493';
update district set mvalue_code = '188', mvalue_name= 'Ngũ Hành Sơn' where code = '494';
update district set mvalue_code = '185', mvalue_name= 'Cẩm Lệ' where code = '495';
update district set mvalue_code = '183', mvalue_name= 'Hoà Vang' where code = '497';
update district set mvalue_code = '184', mvalue_name= 'Hoàng Sa' where code = '498';
update district set mvalue_code = '522', mvalue_name= 'Tam Kỳ' where code = '502';
update district set mvalue_code = '521', mvalue_name= 'Hội An' where code = '503';
update district set mvalue_code = '518', mvalue_name= 'Tây Giang' where code = '504';
update district set mvalue_code = '508', mvalue_name= 'Đông Giang' where code = '505';
update district set mvalue_code = '506', mvalue_name= 'Đại Lộc' where code = '506';
update district set mvalue_code = '507', mvalue_name= 'Điện Bàn' where code = '507';
update district set mvalue_code = '509', mvalue_name= 'Duy Xuyên' where code = '508';
update district set mvalue_code = '517', mvalue_name= 'Quế Sơn' where code = '509';
update district set mvalue_code = '511', mvalue_name= 'Nam Giang' where code = '510';
update district set mvalue_code = '516', mvalue_name= 'Phước Sơn' where code = '511';
update district set mvalue_code = '510', mvalue_name= 'Hiệp Đức' where code = '512';
update district set mvalue_code = '519', mvalue_name= 'Thăng Bình' where code = '513';
update district set mvalue_code = '520', mvalue_name= 'Tiên Phước' where code = '514';
update district set mvalue_code = '505', mvalue_name= 'Bắc Trà My' where code = '515';
update district set mvalue_code = '512', mvalue_name= 'Nam Trà My' where code = '516';
update district set mvalue_code = '514', mvalue_name= 'Núi Thành' where code = '517';
update district set mvalue_code = '515', mvalue_name= 'Phú Ninh' where code = '518';
update district set mvalue_code = '513', mvalue_name= 'Nông Sơn' where code = '519';
update district set mvalue_code = '536', mvalue_name= 'Quảng Ngãi' where code = '522';
update district set mvalue_code = '524', mvalue_name= 'Bình Sơn' where code = '524';
update district set mvalue_code = '534', mvalue_name= 'Trà Bồng' where code = '525';
update district set mvalue_code = '532', mvalue_name= 'Sơn Tịnh' where code = '527';
update district set mvalue_code = '535', mvalue_name= 'Tư Nghĩa' where code = '528';
update district set mvalue_code = '530', mvalue_name= 'Sơn Hà' where code = '529';
update district set mvalue_code = '531', mvalue_name= 'Sơn Tây' where code = '530';
update district set mvalue_code = '527', mvalue_name= 'Minh Long' where code = '531';
update district set mvalue_code = '529', mvalue_name= 'Nghĩa Hành' where code = '532';
update district set mvalue_code = '528', mvalue_name= 'Mộ Đức' where code = '533';
update district set mvalue_code = '525', mvalue_name= 'Đức Phổ' where code = '534';
update district set mvalue_code = '523', mvalue_name= 'Ba Tơ' where code = '535';
update district set mvalue_code = '526', mvalue_name= 'Lý Sơn' where code = '536';
update district set mvalue_code = '126', mvalue_name= 'Quy Nhơn' where code = '540';
update district set mvalue_code = '116', mvalue_name= 'An Lão' where code = '542';
update district set mvalue_code = '119', mvalue_name= 'Hoài Nhơn' where code = '543';
update district set mvalue_code = '118', mvalue_name= 'Hoài Ân' where code = '544';
update district set mvalue_code = '121', mvalue_name= 'Phù Mỹ' where code = '545';
update district set mvalue_code = '125', mvalue_name= 'Huyện Vĩnh Thạnh' where code = '546';
update district set mvalue_code = '122', mvalue_name= 'Tây Sơn' where code = '547';
update district set mvalue_code = '120', mvalue_name= 'Phù Cát' where code = '548';
update district set mvalue_code = '117', mvalue_name= 'An Nhơn' where code = '549';
update district set mvalue_code = '123', mvalue_name= 'Tuy Phước' where code = '550';
update district set mvalue_code = '124', mvalue_name= 'Vân Canh' where code = '551';
update district set mvalue_code = '497', mvalue_name= 'Tuy Hòa' where code = '555';
update district set mvalue_code = '493', mvalue_name= 'Sông Cầu' where code = '557';
update district set mvalue_code = '490', mvalue_name= 'Đồng Xuân' where code = '558';
update district set mvalue_code = '496', mvalue_name= 'Tuy An' where code = '559';
update district set mvalue_code = '492', mvalue_name= 'Sơn Hòa' where code = '560';
update district set mvalue_code = '494', mvalue_name= 'Sông Hinh' where code = '561';
update district set mvalue_code = '495', mvalue_name= 'Tây Hòa' where code = '562';
update district set mvalue_code = '491', mvalue_name= 'Phú Hoà' where code = '563';
update district set mvalue_code = '489', mvalue_name= 'Đông Hòa' where code = '564';
update district set mvalue_code = '353', mvalue_name= 'Nha Trang' where code = '568';
update district set mvalue_code = '354', mvalue_name= 'Cam Ranh' where code = '569';
update district set mvalue_code = '346', mvalue_name= 'Cam Lâm' where code = '570';
update district set mvalue_code = '352', mvalue_name= 'Vạn Ninh' where code = '571';
update district set mvalue_code = '350', mvalue_name= 'Ninh Hòa' where code = '572';
update district set mvalue_code = '749', mvalue_name= 'Khánh Vĩnh' where code = '573';
update district set mvalue_code = '347', mvalue_name= 'Diên Khánh' where code = '574';
update district set mvalue_code = '348', mvalue_name= 'Khánh Sơn' where code = '575';
update district set mvalue_code = '351', mvalue_name= 'Trường Sa' where code = '576';
update district set mvalue_code = '475', mvalue_name= 'Phan Rang - Tháp Chàm' where code = '582';
update district set mvalue_code = '469', mvalue_name= 'Bác ái' where code = '584';
update district set mvalue_code = '472', mvalue_name= 'Ninh Sơn' where code = '585';
update district set mvalue_code = '470', mvalue_name= 'Ninh Hải' where code = '586';
update district set mvalue_code = '471', mvalue_name= 'Ninh Phước' where code = '587';
update district set mvalue_code = '473', mvalue_name= 'Thuận Bắc' where code = '588';
update district set mvalue_code = '474', mvalue_name= 'Thuận Nam' where code = '589';
update district set mvalue_code = '150', mvalue_name= 'Phan Thiết' where code = '593';
update district set mvalue_code = '151', mvalue_name= 'La Gi' where code = '594';
update district set mvalue_code = '149', mvalue_name= 'Tuy Phong' where code = '595';
update district set mvalue_code = '142', mvalue_name= 'Bắc Bình' where code = '596';
update district set mvalue_code = '145', mvalue_name= 'Hàm Thuận Bắc' where code = '597';
update district set mvalue_code = '146', mvalue_name= 'Hàm Thuận Nam' where code = '598';
update district set mvalue_code = '148', mvalue_name= 'Tánh Linh' where code = '599';
update district set mvalue_code = '143', mvalue_name= 'Đức Linh' where code = '600';
update district set mvalue_code = '144', mvalue_name= 'Hàm Tân' where code = '601';
update district set mvalue_code = '147', mvalue_name= 'Phú Quí' where code = '602';
update district set mvalue_code = '377', mvalue_name= 'Kon Tum' where code = '608';
update district set mvalue_code = '369', mvalue_name= 'Đắk Glei' where code = '610';
update district set mvalue_code = '374', mvalue_name= 'Ngọc Hồi' where code = '611';
update district set mvalue_code = '371', mvalue_name= 'Đắk Tô' where code = '612';
update district set mvalue_code = '372', mvalue_name= 'Kon Plông' where code = '613';
update district set mvalue_code = '373', mvalue_name= 'Kon Rẫy' where code = '614';
update district set mvalue_code = '370', mvalue_name= 'Đắk Hà' where code = '615';
update district set mvalue_code = '375', mvalue_name= 'Sa Thầy' where code = '616';
update district set mvalue_code = '376', mvalue_name= 'Tu Mơ Rông' where code = '617';
update district set mvalue_code = '747', mvalue_name= 'Ia H'' Drai' where code = '618';
update district set mvalue_code = '259', mvalue_name= 'Pleiku' where code = '622';
update district set mvalue_code = '260', mvalue_name= 'An Khê' where code = '623';
update district set mvalue_code = '261', mvalue_name= 'Ayun Pa' where code = '624';
update district set mvalue_code = '254', mvalue_name= 'KBang' where code = '625';
update district set mvalue_code = '249', mvalue_name= 'Đăk Đoa' where code = '626';
update district set mvalue_code = '246', mvalue_name= 'Chư Păh' where code = '627';
update district set mvalue_code = '252', mvalue_name= 'Ia Grai' where code = '628';
update district set mvalue_code = '257', mvalue_name= 'Mang Yang' where code = '629';
update district set mvalue_code = '255', mvalue_name= 'Kông Chro' where code = '630';
update district set mvalue_code = '251', mvalue_name= 'Đức Cơ' where code = '631';
update district set mvalue_code = '247', mvalue_name= 'Chư Prông' where code = '632';
update district set mvalue_code = '248', mvalue_name= 'Chư Sê' where code = '633';
update district set mvalue_code = '250', mvalue_name= 'Đăk Pơ' where code = '634';
update district set mvalue_code = '253', mvalue_name= 'Ia Pa' where code = '635';
update district set mvalue_code = '256', mvalue_name= 'Krông Pa' where code = '637';
update district set mvalue_code = '258', mvalue_name= 'Phú Thiện' where code = '638';
update district set mvalue_code = '694', mvalue_name= 'Chư Pưh' where code = '639';
update district set mvalue_code = '204', mvalue_name= 'Buôn Ma Thuột' where code = '643';
update district set mvalue_code = '205', mvalue_name= 'Buôn Hồ' where code = '644';
update district set mvalue_code = '194', mvalue_name= 'Ea H''leo' where code = '645';
update district set mvalue_code = '196', mvalue_name= 'Ea Súp' where code = '646';
update district set mvalue_code = '191', mvalue_name= 'Buôn Đôn' where code = '647';
update district set mvalue_code = '193', mvalue_name= 'Cư M''gar' where code = '648';
update district set mvalue_code = '199', mvalue_name= 'Krông Búk' where code = '649';
update district set mvalue_code = '200', mvalue_name= 'Krông Năng' where code = '650';
update district set mvalue_code = '195', mvalue_name= 'Ea Kar' where code = '651';
update district set mvalue_code = '203', mvalue_name= 'M''Đrắk' where code = '652';
update district set mvalue_code = '198', mvalue_name= 'Krông Bông' where code = '653';
update district set mvalue_code = '201', mvalue_name= 'Krông Pắc' where code = '654';
update district set mvalue_code = '197', mvalue_name= 'Krông A Na' where code = '655';
update district set mvalue_code = '202', mvalue_name= 'Lắk' where code = '656';
update district set mvalue_code = '192', mvalue_name= 'Cư Kuin' where code = '657';
update district set mvalue_code = '213', mvalue_name= 'Gia Nghĩa' where code = '660';
update district set mvalue_code = '824', mvalue_name= 'Đăk Glong' where code = '661';
update district set mvalue_code = '206', mvalue_name= 'Cư Jút' where code = '662';
update district set mvalue_code = '208', mvalue_name= 'Đắk Mil' where code = '663';
update district set mvalue_code = '211', mvalue_name= 'Krông Nô' where code = '664';
update district set mvalue_code = '210', mvalue_name= 'Đắk Song' where code = '665';
update district set mvalue_code = '209', mvalue_name= 'Đắk R''Lấp' where code = '666';
update district set mvalue_code = '212', mvalue_name= 'Tuy Đức' where code = '667';
update district set mvalue_code = '395', mvalue_name= 'Đà Lạt' where code = '672';
update district set mvalue_code = '396', mvalue_name= 'Bảo Lộc' where code = '673';
update district set mvalue_code = '389', mvalue_name= 'Đam Rông' where code = '674';
update district set mvalue_code = '393', mvalue_name= 'Lạc Dương' where code = '675';
update district set mvalue_code = '394', mvalue_name= 'Lâm Hà' where code = '676';
update district set mvalue_code = '391', mvalue_name= 'Đơn Dương' where code = '677';
update district set mvalue_code = '392', mvalue_name= 'Đức Trọng' where code = '678';
update district set mvalue_code = '390', mvalue_name= 'Di Linh' where code = '679';
update district set mvalue_code = '385', mvalue_name= 'Bảo Lâm' where code = '680';
update district set mvalue_code = '387', mvalue_name= 'Đạ Huoai' where code = '681';
update district set mvalue_code = '388', mvalue_name= 'Đạ Tẻh' where code = '682';
update district set mvalue_code = '386', mvalue_name= 'Cát Tiên' where code = '683';
update district set mvalue_code = '140', mvalue_name= 'Thị xã Phước Long' where code = '688';
update district set mvalue_code = '141', mvalue_name= 'Đồng Xoài' where code = '689';
update district set mvalue_code = '134', mvalue_name= 'Bình Long' where code = '690';
update district set mvalue_code = '695', mvalue_name= 'Bù Gia Mập' where code = '691';
update district set mvalue_code = '139', mvalue_name= 'Lộc Ninh' where code = '692';
update district set mvalue_code = '136', mvalue_name= 'Bù Đốp' where code = '693';
update district set mvalue_code = '696', mvalue_name= 'Hớn Quản' where code = '694';
update district set mvalue_code = '746', mvalue_name= 'Đồng Phú' where code = '695';
update district set mvalue_code = '135', mvalue_name= 'Bù Đăng' where code = '696';
update district set mvalue_code = '137', mvalue_name= 'Chơn Thành' where code = '697';
update district set mvalue_code = '755', mvalue_name= 'Phú Riềng' where code = '698';
update district set mvalue_code = '590', mvalue_name= 'Tây Ninh' where code = '703';
update district set mvalue_code = '587', mvalue_name= 'Tân Biên' where code = '705';
update district set mvalue_code = '588', mvalue_name= 'Huyện Tân Châu' where code = '706';
update district set mvalue_code = '584', mvalue_name= 'Dương Minh Châu' where code = '707';
update district set mvalue_code = '583', mvalue_name= 'Huyện Châu Thành' where code = '708';
update district set mvalue_code = '586', mvalue_name= 'Hòa Thành' where code = '709';
update district set mvalue_code = '585', mvalue_name= 'Gò Dầu' where code = '710';
update district set mvalue_code = '582', mvalue_name= 'Bến Cầu' where code = '711';
update district set mvalue_code = '589', mvalue_name= 'Trảng Bàng' where code = '712';
update district set mvalue_code = '133', mvalue_name= 'Thủ Dầu Một' where code = '718';
update district set mvalue_code = '724', mvalue_name= 'Bàu Bàng' where code = '719';
update district set mvalue_code = '128', mvalue_name= 'Dầu Tiếng' where code = '720';
update district set mvalue_code = '127', mvalue_name= 'Bến Cát' where code = '721';
update district set mvalue_code = '130', mvalue_name= 'Phú Giáo' where code = '722';
update district set mvalue_code = '131', mvalue_name= 'Thị xã Tân Uyên' where code = '723';
update district set mvalue_code = '129', mvalue_name= 'Dĩ An' where code = '724';
update district set mvalue_code = '132', mvalue_name= 'Thuận An' where code = '725';
update district set mvalue_code = '745', mvalue_name= 'Bắc Tân Uyên' where code = '726';
update district set mvalue_code = '232', mvalue_name= 'Biên Hòa' where code = '731';
update district set mvalue_code = '233', mvalue_name= 'Long Khánh' where code = '732';
update district set mvalue_code = '227', mvalue_name= 'Huyện Tân Phú' where code = '734';
update district set mvalue_code = '230', mvalue_name= 'Vĩnh Cửu' where code = '735';
update district set mvalue_code = '224', mvalue_name= 'Định Quán' where code = '736';
update district set mvalue_code = '229', mvalue_name= 'Trảng Bom' where code = '737';
update district set mvalue_code = '228', mvalue_name= 'Thống Nhất' where code = '738';
update district set mvalue_code = '223', mvalue_name= 'Cẩm Mỹ' where code = '739';
update district set mvalue_code = '225', mvalue_name= 'Long Thành' where code = '740';
update district set mvalue_code = '231', mvalue_name= 'Xuân Lộc' where code = '741';
update district set mvalue_code = '226', mvalue_name= 'Nhơn Trạch' where code = '742';
update district set mvalue_code = '72', mvalue_name= 'Vũng Tàu' where code = '747';
update district set mvalue_code = '73', mvalue_name= 'Bà Rịa' where code = '748';
update district set mvalue_code = '66', mvalue_name= 'Châu Đức' where code = '750';
update district set mvalue_code = '71', mvalue_name= 'Xuyên Mộc' where code = '751';
update district set mvalue_code = '69', mvalue_name= 'Long Điền' where code = '752';
update district set mvalue_code = '68', mvalue_name= 'Đất Đỏ' where code = '753';
update district set mvalue_code = '70', mvalue_name= 'Tân Thành' where code = '754';
update district set mvalue_code = '67', mvalue_name= 'Côn Đảo' where code = '755';
update district set mvalue_code = '36', mvalue_name= '1' where code = '760';
update district set mvalue_code = '39', mvalue_name= '12' where code = '761';
update district set mvalue_code = '54', mvalue_name= 'Thủ Đức' where code = '762';
update district set mvalue_code = '47', mvalue_name= '9' where code = '763';
update district set mvalue_code = '50', mvalue_name= 'Gò Vấp' where code = '764';
update district set mvalue_code = '49', mvalue_name= 'Bình Thạnh' where code = '765';
update district set mvalue_code = '52', mvalue_name= 'Tân Bình' where code = '766';
update district set mvalue_code = '53', mvalue_name= 'Tân Phú' where code = '767';
update district set mvalue_code = '51', mvalue_name= 'Phú Nhuận' where code = '768';
update district set mvalue_code = '40', mvalue_name= '2' where code = '769';
update district set mvalue_code = '41', mvalue_name= '3' where code = '770';
update district set mvalue_code = '37', mvalue_name= '10' where code = '771';
update district set mvalue_code = '38', mvalue_name= '11' where code = '772';
update district set mvalue_code = '42', mvalue_name= '4' where code = '773';
update district set mvalue_code = '43', mvalue_name= '5' where code = '774';
update district set mvalue_code = '44', mvalue_name= '6' where code = '775';
update district set mvalue_code = '46', mvalue_name= '8' where code = '776';
update district set mvalue_code = '48', mvalue_name= 'Quận Bình Tân' where code = '777';
update district set mvalue_code = '45', mvalue_name= '7' where code = '778';
update district set mvalue_code = '33', mvalue_name= 'Củ Chi' where code = '783';
update district set mvalue_code = '34', mvalue_name= 'Hóc Môn' where code = '784';
update district set mvalue_code = '31', mvalue_name= 'Bình Chánh' where code = '785';
update district set mvalue_code = '35', mvalue_name= 'Nhà Bè' where code = '786';
update district set mvalue_code = '32', mvalue_name= 'Cần Giờ' where code = '787';
update district set mvalue_code = '430', mvalue_name= 'Tân An' where code = '794';
update district set mvalue_code = '748', mvalue_name= 'Kiến Tường' where code = '795';
update district set mvalue_code = '424', mvalue_name= 'Tân Hưng' where code = '796';
update district set mvalue_code = '429', mvalue_name= 'Vĩnh Hưng' where code = '797';
update district set mvalue_code = '423', mvalue_name= 'Mộc Hóa' where code = '798';
update district set mvalue_code = '425', mvalue_name= 'Tân Thạnh' where code = '799';
update district set mvalue_code = '427', mvalue_name= 'Thạnh Hóa' where code = '800';
update district set mvalue_code = '422', mvalue_name= 'Đức Huệ' where code = '801';
update district set mvalue_code = '421', mvalue_name= 'Đức Hòa' where code = '802';
update district set mvalue_code = '417', mvalue_name= 'Bến Lức' where code = '803';
update district set mvalue_code = '428', mvalue_name= 'Thủ Thừa' where code = '804';
update district set mvalue_code = '426', mvalue_name= 'Tân Trụ' where code = '805';
update district set mvalue_code = '418', mvalue_name= 'Cần Đước' where code = '806';
update district set mvalue_code = '419', mvalue_name= 'Cần Giuộc' where code = '807';
update district set mvalue_code = '420', mvalue_name= 'Huyện Châu Thành' where code = '808';
update district set mvalue_code = '652', mvalue_name= 'Mỹ Tho' where code = '815';
update district set mvalue_code = '653', mvalue_name= 'Gò Công' where code = '816';
update district set mvalue_code = '645', mvalue_name= 'Cai Lậy' where code = '817';
update district set mvalue_code = '651', mvalue_name= 'Tân Phước' where code = '818';
update district set mvalue_code = '644', mvalue_name= 'Cái Bè' where code = '819';
update district set mvalue_code = '645', mvalue_name= 'Cai Lậy' where code = '820';
update district set mvalue_code = '646', mvalue_name= 'Huyện Châu Thành' where code = '821';
update district set mvalue_code = '647', mvalue_name= 'Chợ Gạo' where code = '822';
update district set mvalue_code = '649', mvalue_name= 'Gò Công Tây' where code = '823';
update district set mvalue_code = '648', mvalue_name= 'Gò Công Đông' where code = '824';
update district set mvalue_code = '650', mvalue_name= 'Tân Phú Đông' where code = '825';
update district set mvalue_code = '115', mvalue_name= 'Bến Tre' where code = '829';
update district set mvalue_code = '109', mvalue_name= 'Huyện Châu Thành' where code = '831';
update district set mvalue_code = '110', mvalue_name= 'Chợ Lách' where code = '832';
update district set mvalue_code = '113', mvalue_name= 'Mỏ Cày Nam' where code = '833';
update district set mvalue_code = '111', mvalue_name= 'Giồng Trôm' where code = '834';
update district set mvalue_code = '108', mvalue_name= 'Bình Đại' where code = '835';
update district set mvalue_code = '107', mvalue_name= 'Ba Tri' where code = '836';
update district set mvalue_code = '114', mvalue_name= 'Thạnh Phú' where code = '837';
update district set mvalue_code = '112', mvalue_name= 'Mỏ Cày Bắc' where code = '838';
update district set mvalue_code = '661', mvalue_name= 'Trà Vinh' where code = '842';
update district set mvalue_code = '654', mvalue_name= 'Càng Long' where code = '844';
update district set mvalue_code = '655', mvalue_name= 'Cầu Kè' where code = '845';
update district set mvalue_code = '659', mvalue_name= 'Tiểu Cần' where code = '846';
update district set mvalue_code = '657', mvalue_name= 'Huyện Châu Thành' where code = '847';
update district set mvalue_code = '656', mvalue_name= 'Cầu Ngang' where code = '848';
update district set mvalue_code = '660', mvalue_name= 'Trà Cú' where code = '849';
update district set mvalue_code = '658', mvalue_name= 'Duyên Hải' where code = '850';
update district set mvalue_code = '658', mvalue_name= 'Duyên Hải' where code = '851';
update district set mvalue_code = '675', mvalue_name= 'Vĩnh Long' where code = '855';
update district set mvalue_code = '670', mvalue_name= 'Long Hồ' where code = '857';
update district set mvalue_code = '671', mvalue_name= 'Mang Thít' where code = '858';
update district set mvalue_code = '674', mvalue_name= 'Vũng Liêm' where code = '859';
update district set mvalue_code = '672', mvalue_name= 'Tam Bình' where code = '860';
update district set mvalue_code = '668', mvalue_name= 'Bình Minh' where code = '861';
update district set mvalue_code = '673', mvalue_name= 'Trà ôn' where code = '862';
update district set mvalue_code = '669', mvalue_name= 'Bình Tân' where code = '863';
update district set mvalue_code = '234', mvalue_name= 'Thành phố Cao Lãnh' where code = '866';
update district set mvalue_code = '245', mvalue_name= 'Sa Đéc' where code = '867';
update district set mvalue_code = '236', mvalue_name= 'Thị xã Hồng Ngự' where code = '868';
update district set mvalue_code = '240', mvalue_name= 'Tân Hồng' where code = '869';
update district set mvalue_code = '244', mvalue_name= 'Hồng Ngự' where code = '870';
update district set mvalue_code = '239', mvalue_name= 'Huyện Tam Nông' where code = '871';
update district set mvalue_code = '242', mvalue_name= 'Tháp Mười' where code = '872';
update district set mvalue_code = '243', mvalue_name= 'Cao Lãnh' where code = '873';
update district set mvalue_code = '241', mvalue_name= 'Thanh Bình' where code = '874';
update district set mvalue_code = '238', mvalue_name= 'Lấp Vò' where code = '875';
update district set mvalue_code = '237', mvalue_name= 'Lai Vung' where code = '876';
update district set mvalue_code = '235', mvalue_name= 'Huyện Châu Thành' where code = '877';
update district set mvalue_code = '64', mvalue_name= 'Long Xuyên' where code = '883';
update district set mvalue_code = '65', mvalue_name= 'Châu Đốc' where code = '884';
update district set mvalue_code = '55', mvalue_name= 'An Phú' where code = '886';
update district set mvalue_code = '60', mvalue_name= 'Tân Châu' where code = '887';
update district set mvalue_code = '59', mvalue_name= 'Huyện Phú Tân' where code = '888';
update district set mvalue_code = '56', mvalue_name= 'Châu Phú' where code = '889';
update district set mvalue_code = '62', mvalue_name= 'Tịnh Biên' where code = '890';
update district set mvalue_code = '63', mvalue_name= 'Tri Tôn' where code = '891';
update district set mvalue_code = '57', mvalue_name= 'Huyện Châu Thành' where code = '892';
update district set mvalue_code = '58', mvalue_name= 'Chợ Mới' where code = '893';
update district set mvalue_code = '61', mvalue_name= 'Thoại Sơn' where code = '894';
update district set mvalue_code = '367', mvalue_name= 'Rạch Giá' where code = '899';
update district set mvalue_code = '368', mvalue_name= 'Hà Tiên' where code = '900';
update district set mvalue_code = '362', mvalue_name= 'Kiên Lương' where code = '902';
update district set mvalue_code = '360', mvalue_name= 'Hòn Đất' where code = '903';
update district set mvalue_code = '364', mvalue_name= 'Tân Hiệp' where code = '904';
update district set mvalue_code = '357', mvalue_name= 'Huyện Châu Thành' where code = '905';
update district set mvalue_code = '358', mvalue_name= 'Giồng Riềng' where code = '906';
update district set mvalue_code = '359', mvalue_name= 'Gò Quao' where code = '907';
update district set mvalue_code = '355', mvalue_name= 'An Biên' where code = '908';
update district set mvalue_code = '356', mvalue_name= 'An Minh' where code = '909';
update district set mvalue_code = '366', mvalue_name= 'Vĩnh Thuận' where code = '910';
update district set mvalue_code = '363', mvalue_name= 'Phú Quốc' where code = '911';
update district set mvalue_code = '361', mvalue_name= 'Kiên Hải' where code = '912';
update district set mvalue_code = '365', mvalue_name= 'U Minh Thượng' where code = '913';
update district set mvalue_code = '697', mvalue_name= 'Giang Thành' where code = '914';
update district set mvalue_code = '711', mvalue_name= 'Ninh Kiều' where code = '916';
update district set mvalue_code = '168', mvalue_name= 'Ô Môn' where code = '917';
update district set mvalue_code = '165', mvalue_name= 'Bình Thuỷ' where code = '918';
update district set mvalue_code = '166', mvalue_name= 'Cái Răng' where code = '919';
update district set mvalue_code = '169', mvalue_name= 'Thốt Nốt' where code = '923';
update district set mvalue_code = '164', mvalue_name= 'Vĩnh Thạnh' where code = '924';
update district set mvalue_code = '161', mvalue_name= 'Cờ Đỏ' where code = '925';
update district set mvalue_code = '162', mvalue_name= 'Phong Điền' where code = '926';
update district set mvalue_code = '163', mvalue_name= 'Thới Lai' where code = '927';
update district set mvalue_code = '324', mvalue_name= 'Vị Thanh' where code = '930';
update district set mvalue_code = '323', mvalue_name= 'Ngã Bảy' where code = '931';
update district set mvalue_code = '318', mvalue_name= 'Châu Thành A' where code = '932';
update district set mvalue_code = '319', mvalue_name= 'Huyện Châu Thành' where code = '933';
update district set mvalue_code = '321', mvalue_name= 'Phụng Hiệp' where code = '934';
update district set mvalue_code = '322', mvalue_name= 'Vị Thuỷ' where code = '935';
update district set mvalue_code = '320', mvalue_name= 'Long Mỹ' where code = '936';
update district set mvalue_code = '320', mvalue_name= 'Long Mỹ' where code = '937';
update district set mvalue_code = '570', mvalue_name= 'Sóc Trăng' where code = '941';
update district set mvalue_code = '561', mvalue_name= 'Châu Thành' where code = '942';
update district set mvalue_code = '563', mvalue_name= 'Kế Sách' where code = '943';
update district set mvalue_code = '565', mvalue_name= 'Mỹ Tú' where code = '944';
update district set mvalue_code = '562', mvalue_name= 'Cù Lao Dung' where code = '945';
update district set mvalue_code = '564', mvalue_name= 'Long Phú' where code = '946';
update district set mvalue_code = '566', mvalue_name= 'Mỹ Xuyên' where code = '947';
update district set mvalue_code = '567', mvalue_name= 'Ngã Năm' where code = '948';
update district set mvalue_code = '568', mvalue_name= 'Thạnh Trị' where code = '949';
update district set mvalue_code = '569', mvalue_name= 'Vĩnh Châu' where code = '950';
update district set mvalue_code = '698', mvalue_name= 'Trần Đề' where code = '951';
update district set mvalue_code = '98', mvalue_name= 'Bạc Liêu' where code = '954';
update district set mvalue_code = '95', mvalue_name= 'Hồng Dân' where code = '956';
update district set mvalue_code = '96', mvalue_name= 'Phước Long' where code = '957';
update district set mvalue_code = '97', mvalue_name= 'Vĩnh Lợi' where code = '958';
update district set mvalue_code = '93', mvalue_name= 'Giá Rai' where code = '959';
update district set mvalue_code = '92', mvalue_name= 'Đông Hải' where code = '960';
update district set mvalue_code = '94', mvalue_name= 'Hòa Bình' where code = '961';
update district set mvalue_code = '160', mvalue_name= 'Cà Mau' where code = '964';
update district set mvalue_code = '159', mvalue_name= 'U Minh' where code = '966';
update district set mvalue_code = '157', mvalue_name= 'Thới Bình' where code = '967';
update district set mvalue_code = '158', mvalue_name= 'Trần Văn Thời' where code = '968';
update district set mvalue_code = '152', mvalue_name= 'Cái Nước' where code = '969';
update district set mvalue_code = '153', mvalue_name= 'Đầm Dơi' where code = '970';
update district set mvalue_code = '154', mvalue_name= 'Năm Căn' where code = '971';
update district set mvalue_code = '156', mvalue_name= 'Phú Tân' where code = '972';
update district set mvalue_code = '155', mvalue_name= 'Ngọc Hiển' where code = '973';
update district set mvalue_code = '754', mvalue_name= 'Phú Mỹ' where code = '974';
