UPDATE province set mvalue_code = null,mvalue_name= null;

UPDATE province set mvalue_code = '2',mvalue_name= 'Hà Nội' where code = '01';
UPDATE province set mvalue_code = '3',mvalue_name= 'Hồ Chí Minh' where code = '79';
UPDATE province set mvalue_code = '4',mvalue_name= 'An Giang' where code = '89';
UPDATE province set mvalue_code = '5',mvalue_name= 'Bà Rịa - Vũng Tàu' where code = '77';
UPDATE province set mvalue_code = '6',mvalue_name= 'Bắc Kạn' where code = '06';
UPDATE province set mvalue_code = '7',mvalue_name= 'Bắc Giang' where code = '24';
UPDATE province set mvalue_code = '8',mvalue_name= 'Bạc Liêu' where code = '95';
UPDATE province set mvalue_code = '10',mvalue_name= 'Bến Tre' where code = '83';
UPDATE province set mvalue_code = '11',mvalue_name= 'Bình Định' where code = '52';
UPDATE province set mvalue_code = '12',mvalue_name= 'Bình Dương' where code = '74';
UPDATE province set mvalue_code = '13',mvalue_name= 'Bình Phước' where code = '70';
UPDATE province set mvalue_code = '14',mvalue_name= 'Bình Thuận' where code = '60';
UPDATE province set mvalue_code = '15',mvalue_name= 'Cà Mau' where code = '96';
UPDATE province set mvalue_code = '16',mvalue_name= 'Cần Thơ' where code = '92';
UPDATE province set mvalue_code = '17',mvalue_name= 'Cao Bằng' where code = '04';
UPDATE province set mvalue_code = '18',mvalue_name= 'Đà Nẵng' where code = '48';
UPDATE province set mvalue_code = '19',mvalue_name= 'Đắk Lắk' where code = '66';
UPDATE province set mvalue_code = '20',mvalue_name= 'Đắk Nông' where code = '67';
UPDATE province set mvalue_code = '21',mvalue_name= 'Điện Biên' where code = '11';
UPDATE province set mvalue_code = '22',mvalue_name= 'Đồng Nai' where code = '75';
UPDATE province set mvalue_code = '23',mvalue_name= 'Đồng Tháp' where code = '87';
UPDATE province set mvalue_code = '24',mvalue_name= 'Gia Lai' where code = '64';
UPDATE province set mvalue_code = '25',mvalue_name= 'Hà Giang' where code = '02';
UPDATE province set mvalue_code = '26',mvalue_name= 'Hà Nam' where code = '35';
UPDATE province set mvalue_code = '27',mvalue_name= 'Hà Tĩnh' where code = '42';
UPDATE province set mvalue_code = '28',mvalue_name= 'Hải Dương' where code = '30';
UPDATE province set mvalue_code = '29',mvalue_name= 'Hải Phòng' where code = '31';
UPDATE province set mvalue_code = '30',mvalue_name= 'Hậu Giang' where code = '93';
UPDATE province set mvalue_code = '31',mvalue_name= 'Hòa Bình' where code = '17';
UPDATE province set mvalue_code = '32',mvalue_name= 'Hưng Yên' where code = '33';
UPDATE province set mvalue_code = '33',mvalue_name= 'Khánh Hòa' where code = '56';
UPDATE province set mvalue_code = '34',mvalue_name= 'Kiên Giang' where code = '91';
UPDATE province set mvalue_code = '35',mvalue_name= 'Kon Tum' where code = '62';
UPDATE province set mvalue_code = '36',mvalue_name= 'Lai Châu' where code = '12';
UPDATE province set mvalue_code = '37',mvalue_name= 'Lâm Đồng' where code = '68';
UPDATE province set mvalue_code = '38',mvalue_name= 'Lạng Sơn' where code = '20';
UPDATE province set mvalue_code = '39',mvalue_name= 'Lào Cai' where code = '10';
UPDATE province set mvalue_code = '40',mvalue_name= 'Long An' where code = '80';
UPDATE province set mvalue_code = '41',mvalue_name= 'Nam Định' where code = '36';
UPDATE province set mvalue_code = '42',mvalue_name= 'Nghệ An' where code = '40';
UPDATE province set mvalue_code = '43',mvalue_name= 'Ninh Bình' where code = '37';
UPDATE province set mvalue_code = '44',mvalue_name= 'Ninh Thuận' where code = '58';
UPDATE province set mvalue_code = '45',mvalue_name= 'Phú Thọ' where code = '25';
UPDATE province set mvalue_code = '46',mvalue_name= 'Phú Yên' where code = '54';
UPDATE province set mvalue_code = '47',mvalue_name= 'Quảng Bình' where code = '44';
UPDATE province set mvalue_code = '48',mvalue_name= 'Quảng Nam' where code = '49';
UPDATE province set mvalue_code = '49',mvalue_name= 'Quảng Ngãi' where code = '51';
UPDATE province set mvalue_code = '50',mvalue_name= 'Quảng Ninh' where code = '22';
UPDATE province set mvalue_code = '51',mvalue_name= 'Quảng Trị' where code = '45';
UPDATE province set mvalue_code = '52',mvalue_name= 'Sóc Trăng' where code = '94';
UPDATE province set mvalue_code = '53',mvalue_name= 'Sơn La' where code = '14';
UPDATE province set mvalue_code = '54',mvalue_name= 'Tây Ninh' where code = '72';
UPDATE province set mvalue_code = '55',mvalue_name= 'Thái Bình' where code = '34';
UPDATE province set mvalue_code = '56',mvalue_name= 'Thái Nguyên' where code = '19';
UPDATE province set mvalue_code = '57',mvalue_name= 'Thanh Hoá' where code = '38';
UPDATE province set mvalue_code = '58',mvalue_name= 'Thừa Thiên - Huế' where code = '46';
UPDATE province set mvalue_code = '59',mvalue_name= 'Tiền Giang' where code = '82';
UPDATE province set mvalue_code = '60',mvalue_name= 'Trà Vinh' where code = '84';
UPDATE province set mvalue_code = '61',mvalue_name= 'Tuyên Quang' where code = '08';
UPDATE province set mvalue_code = '62',mvalue_name= 'Vĩnh Long' where code = '86';
UPDATE province set mvalue_code = '63',mvalue_name= 'Vĩnh Phúc' where code = '26';
UPDATE province set mvalue_code = '64',mvalue_name= 'Yên Bái' where code = '15';

