UPDATE district set mvalue_code = null,mvalue_name= null,mvalue_province_code=null;



UPDATE district set mvalue_code = '635',mvalue_name= 'A Lưới' ,mvalue_province_code= '58' where code = '481';
UPDATE district set mvalue_code = '636',mvalue_name= 'Hương Thủy' ,mvalue_province_code= '58' where code = '479';
UPDATE district set mvalue_code = '637',mvalue_name= 'Hương Trà' ,mvalue_province_code= '58' where code = '480';
UPDATE district set mvalue_code = '638',mvalue_name= 'Nam Đông' ,mvalue_province_code= '58' where code = '483';
UPDATE district set mvalue_code = '639',mvalue_name= 'Phong Điền' ,mvalue_province_code= '58' where code = '476';
UPDATE district set mvalue_code = '640',mvalue_name= 'Phú Lộc' ,mvalue_province_code= '58' where code = '482';
UPDATE district set mvalue_code = '641',mvalue_name= 'Phú Vang' ,mvalue_province_code= '58' where code = '478';
UPDATE district set mvalue_code = '642',mvalue_name= 'Quảng Điền' ,mvalue_province_code= '58' where code = '477';
UPDATE district set mvalue_code = '643',mvalue_name= 'Huế' ,mvalue_province_code= '58' where code = '474';
UPDATE district set mvalue_code = '644',mvalue_name= 'Cái Bè' ,mvalue_province_code= '59' where code = '819';
UPDATE district set mvalue_code = '645',mvalue_name= 'Cai Lậy' ,mvalue_province_code= '59' where code = '817';
UPDATE district set mvalue_code = '646',mvalue_name= 'Châu Thành' ,mvalue_province_code= '59' where code = '821';
UPDATE district set mvalue_code = '647',mvalue_name= 'Chợ Gạo' ,mvalue_province_code= '59' where code = '822';
UPDATE district set mvalue_code = '648',mvalue_name= 'Gò Công Đông' ,mvalue_province_code= '59' where code = '824';
UPDATE district set mvalue_code = '649',mvalue_name= 'Gò Công Tây' ,mvalue_province_code= '59' where code = '823';
UPDATE district set mvalue_code = '650',mvalue_name= 'Tân Phú Đông' ,mvalue_province_code= '59' where code = '562';
UPDATE district set mvalue_code = '651',mvalue_name= 'Tân Phước' ,mvalue_province_code= '59' where code = '818';
UPDATE district set mvalue_code = '652',mvalue_name= 'Mỹ Tho' ,mvalue_province_code= '59' where code = '555';
UPDATE district set mvalue_code = '653',mvalue_name= 'Gò Công' ,mvalue_province_code= '59' where code = '816';
UPDATE district set mvalue_code = '654',mvalue_name= 'Càng Long' ,mvalue_province_code= '60' where code = '844';
UPDATE district set mvalue_code = '655',mvalue_name= 'Cầu Kè' ,mvalue_province_code= '60' where code = '845';
UPDATE district set mvalue_code = '656',mvalue_name= 'Cầu Ngang' ,mvalue_province_code= '60' where code = '848';
UPDATE district set mvalue_code = '657',mvalue_name= 'Châu Thành' ,mvalue_province_code= '60' where code = '847';
UPDATE district set mvalue_code = '658',mvalue_name= 'Duyên Hải' ,mvalue_province_code= '60' where code = '850';
UPDATE district set mvalue_code = '659',mvalue_name= 'Tiểu Cần' ,mvalue_province_code= '60' where code = '846';
UPDATE district set mvalue_code = '660',mvalue_name= 'Trà Cú' ,mvalue_province_code= '60' where code = '849';
UPDATE district set mvalue_code = '661',mvalue_name= 'Trà Vinh' ,mvalue_province_code= '60' where code = '842';
UPDATE district set mvalue_code = '662',mvalue_name= 'Chiêm Hóa' ,mvalue_province_code= '61' where code = '073';
UPDATE district set mvalue_code = '663',mvalue_name= 'Hàm Yên' ,mvalue_province_code= '61' where code = '074';
UPDATE district set mvalue_code = '665',mvalue_name= 'Sơn Dương' ,mvalue_province_code= '61' where code = '076';
UPDATE district set mvalue_code = '666',mvalue_name= 'Yên Sơn' ,mvalue_province_code= '61' where code = '075';
UPDATE district set mvalue_code = '667',mvalue_name= 'Tuyên Quang' ,mvalue_province_code= '61' where code = '070';
UPDATE district set mvalue_code = '668',mvalue_name= 'Bình Minh' ,mvalue_province_code= '62' where code = '861';
UPDATE district set mvalue_code = '669',mvalue_name= 'Bình Tân' ,mvalue_province_code= '62' where code = '863';
UPDATE district set mvalue_code = '670',mvalue_name= 'Long Hồ' ,mvalue_province_code= '62' where code = '857';
UPDATE district set mvalue_code = '671',mvalue_name= 'Mang Thít' ,mvalue_province_code= '62' where code = '858';
UPDATE district set mvalue_code = '672',mvalue_name= 'Tam Bình' ,mvalue_province_code= '62' where code = '860';
UPDATE district set mvalue_code = '673',mvalue_name= 'Trà ôn' ,mvalue_province_code= '62' where code = '862';
UPDATE district set mvalue_code = '674',mvalue_name= 'Vũng Liêm' ,mvalue_province_code= '62' where code = '859';
UPDATE district set mvalue_code = '675',mvalue_name= 'Vĩnh Long' ,mvalue_province_code= '62' where code = '855';
UPDATE district set mvalue_code = '676',mvalue_name= 'Bình Xuyên' ,mvalue_province_code= '63' where code = '249';
UPDATE district set mvalue_code = '677',mvalue_name= 'Lập Thạch' ,mvalue_province_code= '63' where code = '246';
UPDATE district set mvalue_code = '678',mvalue_name= 'Sông Lô' ,mvalue_province_code= '63' where code = '253';
UPDATE district set mvalue_code = '679',mvalue_name= 'Tam Đảo' ,mvalue_province_code= '63' where code = '248';
UPDATE district set mvalue_code = '680',mvalue_name= 'Tam Dương' ,mvalue_province_code= '63' where code = '247';
UPDATE district set mvalue_code = '681',mvalue_name= 'Vĩnh Tường' ,mvalue_province_code= '63' where code = '252';
UPDATE district set mvalue_code = '682',mvalue_name= 'Yên Lạc' ,mvalue_province_code= '63' where code = '251';
UPDATE district set mvalue_code = '683',mvalue_name= 'Vĩnh Yên' ,mvalue_province_code= '63' where code = '243';
UPDATE district set mvalue_code = '684',mvalue_name= 'Phúc Yên' ,mvalue_province_code= '63' where code = '244';
UPDATE district set mvalue_code = '685',mvalue_name= 'Lục Yên' ,mvalue_province_code= '64' where code = '135';
UPDATE district set mvalue_code = '686',mvalue_name= 'Mù Cang Chải' ,mvalue_province_code= '64' where code = '137';
UPDATE district set mvalue_code = '687',mvalue_name= 'Trạm Tấu' ,mvalue_province_code= '64' where code = '139';
UPDATE district set mvalue_code = '688',mvalue_name= 'Trấn Yên' ,mvalue_province_code= '64' where code = '138';
UPDATE district set mvalue_code = '689',mvalue_name= 'Văn Chấn' ,mvalue_province_code= '64' where code = '140';
UPDATE district set mvalue_code = '690',mvalue_name= 'Văn Yên' ,mvalue_province_code= '64' where code = '136';
UPDATE district set mvalue_code = '691',mvalue_name= 'Yên Bình' ,mvalue_province_code= '64' where code = '141';
UPDATE district set mvalue_code = '692',mvalue_name= 'Yên Bái' ,mvalue_province_code= '64' where code = '132';
UPDATE district set mvalue_code = '693',mvalue_name= 'Nghĩa Lộ' ,mvalue_province_code= '64' where code = '133';
UPDATE district set mvalue_code = '694',mvalue_name= 'Chư Pưh' ,mvalue_province_code= '24' where code = '639';
UPDATE district set mvalue_code = '695',mvalue_name= 'Bù Gia Mập' ,mvalue_province_code= '13' where code = '691';
UPDATE district set mvalue_code = '696',mvalue_name= 'Hớn Quản' ,mvalue_province_code= '13' where code = '694';
UPDATE district set mvalue_code = '697',mvalue_name= 'Giang Thành' ,mvalue_province_code= '34' where code = '914';
UPDATE district set mvalue_code = '698',mvalue_name= 'Trần Đề' ,mvalue_province_code= '52' where code = '951';
UPDATE district set mvalue_code = '707',mvalue_name= 'Nam Từ Liêm' ,mvalue_province_code= '2' where code = '019';
UPDATE district set mvalue_code = '717',mvalue_name= 'Bắc Từ Liêm' ,mvalue_province_code= '2' where code = '021';
UPDATE district set mvalue_code = '718',mvalue_name= 'Dương Kinh' ,mvalue_province_code= '29' where code = '309';
UPDATE district set mvalue_code = '2',mvalue_name= 'Ba Vì' ,mvalue_province_code= '2' where code = '271';
UPDATE district set mvalue_code = '3',mvalue_name= 'Chương Mỹ' ,mvalue_province_code= '2' where code = '277';
UPDATE district set mvalue_code = '4',mvalue_name= 'Đan Phượng' ,mvalue_province_code= '2' where code = '273';
UPDATE district set mvalue_code = '5',mvalue_name= 'Đông Anh' ,mvalue_province_code= '2' where code = '017';
UPDATE district set mvalue_code = '6',mvalue_name= 'Gia Lâm' ,mvalue_province_code= '2' where code = '018';
UPDATE district set mvalue_code = '7',mvalue_name= 'Hoài Đức' ,mvalue_province_code= '2' where code = '274';
UPDATE district set mvalue_code = '8',mvalue_name= 'Mê Linh' ,mvalue_province_code= '2' where code = '250';
UPDATE district set mvalue_code = '10',mvalue_name= 'Phú Xuyên' ,mvalue_province_code= '2' where code = '280';
UPDATE district set mvalue_code = '11',mvalue_name= 'Phúc Thọ' ,mvalue_province_code= '2' where code = '272';
UPDATE district set mvalue_code = '12',mvalue_name= 'Quốc Oai' ,mvalue_province_code= '2' where code = '275';
UPDATE district set mvalue_code = '13',mvalue_name= 'Sóc Sơn' ,mvalue_province_code= '2' where code = '016';
UPDATE district set mvalue_code = '14',mvalue_name= 'Thạch Thất' ,mvalue_province_code= '2' where code = '276';
UPDATE district set mvalue_code = '15',mvalue_name= 'Thanh Oai' ,mvalue_province_code= '2' where code = '278';
UPDATE district set mvalue_code = '16',mvalue_name= 'Thanh Trì' ,mvalue_province_code= '2' where code = '020';
UPDATE district set mvalue_code = '17',mvalue_name= 'Thường Tín' ,mvalue_province_code= '2' where code = '279';
UPDATE district set mvalue_code = '19',mvalue_name= 'Ứng Hòa' ,mvalue_province_code= '2' where code = '281';
UPDATE district set mvalue_code = '20',mvalue_name= 'Ba Đình' ,mvalue_province_code= '2' where code = '001';
UPDATE district set mvalue_code = '21',mvalue_name= 'Cầu Giấy' ,mvalue_province_code= '2' where code = '005';
UPDATE district set mvalue_code = '22',mvalue_name= 'Đống Đa' ,mvalue_province_code= '2' where code = '006';
UPDATE district set mvalue_code = '23',mvalue_name= 'Hà Đông' ,mvalue_province_code= '2' where code = '268';
UPDATE district set mvalue_code = '24',mvalue_name= 'Hai Bà Trưng' ,mvalue_province_code= '2' where code = '007';
UPDATE district set mvalue_code = '25',mvalue_name= 'Hoàn Kiếm' ,mvalue_province_code= '2' where code = '002';
UPDATE district set mvalue_code = '26',mvalue_name= 'Hoàng Mai' ,mvalue_province_code= '2' where code = '008';
UPDATE district set mvalue_code = '27',mvalue_name= 'Long Biên' ,mvalue_province_code= '2' where code = '004';
UPDATE district set mvalue_code = '28',mvalue_name= 'Tây Hồ' ,mvalue_province_code= '2' where code = '003';
UPDATE district set mvalue_code = '29',mvalue_name= 'Thanh Xuân' ,mvalue_province_code= '2' where code = '009';
UPDATE district set mvalue_code = '30',mvalue_name= 'Sơn Tây' ,mvalue_province_code= '2' where code = '269';
UPDATE district set mvalue_code = '31',mvalue_name= 'Bình Chánh' ,mvalue_province_code= '3' where code = '785';
UPDATE district set mvalue_code = '32',mvalue_name= 'Cần Giờ' ,mvalue_province_code= '3' where code = '787';
UPDATE district set mvalue_code = '33',mvalue_name= 'Củ Chi' ,mvalue_province_code= '3' where code = '783';
UPDATE district set mvalue_code = '34',mvalue_name= 'Hóc Môn' ,mvalue_province_code= '3' where code = '784';
UPDATE district set mvalue_code = '35',mvalue_name= 'Nhà Bè' ,mvalue_province_code= '3' where code = '786';
UPDATE district set mvalue_code = '36',mvalue_name= '1' ,mvalue_province_code= '3' where code = '760';
UPDATE district set mvalue_code = '37',mvalue_name= '10' ,mvalue_province_code= '3' where code = '771';
UPDATE district set mvalue_code = '38',mvalue_name= '11' ,mvalue_province_code= '3' where code = '772';
UPDATE district set mvalue_code = '39',mvalue_name= '12' ,mvalue_province_code= '3' where code = '761';
UPDATE district set mvalue_code = '40',mvalue_name= '2' ,mvalue_province_code= '3' where code = '769';
UPDATE district set mvalue_code = '41',mvalue_name= '3' ,mvalue_province_code= '3' where code = '770';
UPDATE district set mvalue_code = '42',mvalue_name= '4' ,mvalue_province_code= '3' where code = '773';
UPDATE district set mvalue_code = '43',mvalue_name= '5' ,mvalue_province_code= '3' where code = '774';
UPDATE district set mvalue_code = '44',mvalue_name= '6' ,mvalue_province_code= '3' where code = '775';
UPDATE district set mvalue_code = '45',mvalue_name= '7' ,mvalue_province_code= '3' where code = '778';
UPDATE district set mvalue_code = '46',mvalue_name= '8' ,mvalue_province_code= '3' where code = '776';
UPDATE district set mvalue_code = '47',mvalue_name= '9' ,mvalue_province_code= '3' where code = '763';
UPDATE district set mvalue_code = '48',mvalue_name= 'Bình Tân' ,mvalue_province_code= '3' where code = '777';
UPDATE district set mvalue_code = '49',mvalue_name= 'Bình Thạnh' ,mvalue_province_code= '3' where code = '765';
UPDATE district set mvalue_code = '50',mvalue_name= 'Gò Vấp' ,mvalue_province_code= '3' where code = '764';
UPDATE district set mvalue_code = '51',mvalue_name= 'Phú Nhuận' ,mvalue_province_code= '3' where code = '768';
UPDATE district set mvalue_code = '52',mvalue_name= 'Tân Bình' ,mvalue_province_code= '3' where code = '766';
UPDATE district set mvalue_code = '53',mvalue_name= 'Tân Phú' ,mvalue_province_code= '3' where code = '767';
UPDATE district set mvalue_code = '54',mvalue_name= 'Thủ Đức' ,mvalue_province_code= '3' where code = '762';
UPDATE district set mvalue_code = '55',mvalue_name= 'An Phú' ,mvalue_province_code= '4' where code = '886';
UPDATE district set mvalue_code = '56',mvalue_name= 'Châu Phú' ,mvalue_province_code= '4' where code = '889';
UPDATE district set mvalue_code = '57',mvalue_name= 'Châu Thành' ,mvalue_province_code= '4' where code = '892';
UPDATE district set mvalue_code = '58',mvalue_name= 'Chợ Mới' ,mvalue_province_code= '4' where code = '893';
UPDATE district set mvalue_code = '59',mvalue_name= 'Phú Tân' ,mvalue_province_code= '4' where code = '888';
UPDATE district set mvalue_code = '60',mvalue_name= 'Tân Châu' ,mvalue_province_code= '4' where code = '887';
UPDATE district set mvalue_code = '61',mvalue_name= 'Thoại Sơn' ,mvalue_province_code= '4' where code = '894';
UPDATE district set mvalue_code = '62',mvalue_name= 'Tịnh Biên' ,mvalue_province_code= '4' where code = '890';
UPDATE district set mvalue_code = '63',mvalue_name= 'Tri Tôn' ,mvalue_province_code= '4' where code = '891';
UPDATE district set mvalue_code = '64',mvalue_name= 'Long Xuyên' ,mvalue_province_code= '4' where code = '883';
UPDATE district set mvalue_code = '65',mvalue_name= 'Châu Đốc' ,mvalue_province_code= '4' where code = '884';
UPDATE district set mvalue_code = '66',mvalue_name= 'Châu Đức' ,mvalue_province_code= '5' where code = '750';
UPDATE district set mvalue_code = '67',mvalue_name= 'Côn Đảo' ,mvalue_province_code= '5' where code = '755';
UPDATE district set mvalue_code = '68',mvalue_name= 'Đất Đỏ' ,mvalue_province_code= '5' where code = '753';
UPDATE district set mvalue_code = '69',mvalue_name= 'Long Điền' ,mvalue_province_code= '5' where code = '752';
UPDATE district set mvalue_code = '70',mvalue_name= 'Tân Thành' ,mvalue_province_code= '5' where code = '754';
UPDATE district set mvalue_code = '71',mvalue_name= 'Xuyên Mộc' ,mvalue_province_code= '5' where code = '751';
UPDATE district set mvalue_code = '72',mvalue_name= 'Vũng Tàu' ,mvalue_province_code= '5' where code = '747';
UPDATE district set mvalue_code = '73',mvalue_name= 'Bà Rịa' ,mvalue_province_code= '5' where code = '748';
UPDATE district set mvalue_code = '74',mvalue_name= 'Ba Bể' ,mvalue_province_code= '6' where code = '061';
UPDATE district set mvalue_code = '75',mvalue_name= 'Bạch Thông' ,mvalue_province_code= '6' where code = '063';
UPDATE district set mvalue_code = '76',mvalue_name= 'Chợ Đồn' ,mvalue_province_code= '6' where code = '064';
UPDATE district set mvalue_code = '77',mvalue_name= 'Chợ Mới' ,mvalue_province_code= '6' where code = '065';
UPDATE district set mvalue_code = '78',mvalue_name= 'Na Rì' ,mvalue_province_code= '6' where code = '066';
UPDATE district set mvalue_code = '79',mvalue_name= 'Ngân Sơn' ,mvalue_province_code= '6' where code = '062';
UPDATE district set mvalue_code = '80',mvalue_name= 'Pác Nặm' ,mvalue_province_code= '6' where code = '060';
UPDATE district set mvalue_code = '81',mvalue_name= 'Bắc Kạn' ,mvalue_province_code= '6' where code = '058';
UPDATE district set mvalue_code = '82',mvalue_name= 'Hiệp Hòa' ,mvalue_province_code= '7' where code = '223';
UPDATE district set mvalue_code = '83',mvalue_name= 'Lạng Giang' ,mvalue_province_code= '7' where code = '217';
UPDATE district set mvalue_code = '84',mvalue_name= 'Lục Nam' ,mvalue_province_code= '7' where code = '218';
UPDATE district set mvalue_code = '85',mvalue_name= 'Lục Ngạn' ,mvalue_province_code= '7' where code = '219';
UPDATE district set mvalue_code = '86',mvalue_name= 'Sơn Động' ,mvalue_province_code= '7' where code = '220';
UPDATE district set mvalue_code = '87',mvalue_name= 'Tân Yên' ,mvalue_province_code= '7' where code = '216';
UPDATE district set mvalue_code = '88',mvalue_name= 'Việt Yên' ,mvalue_province_code= '7' where code = '222';
UPDATE district set mvalue_code = '89',mvalue_name= 'Yên Dũng' ,mvalue_province_code= '7' where code = '221';
UPDATE district set mvalue_code = '90',mvalue_name= 'Yên Thế' ,mvalue_province_code= '7' where code = '215';
UPDATE district set mvalue_code = '91',mvalue_name= 'Bắc Giang' ,mvalue_province_code= '7' where code = '213';
UPDATE district set mvalue_code = '92',mvalue_name= 'Đông Hải' ,mvalue_province_code= '8' where code = '960';
UPDATE district set mvalue_code = '93',mvalue_name= 'Giá Rai' ,mvalue_province_code= '8' where code = '959';
UPDATE district set mvalue_code = '95',mvalue_name= 'Hồng Dân' ,mvalue_province_code= '8' where code = '956';
UPDATE district set mvalue_code = '96',mvalue_name= 'Phước Long' ,mvalue_province_code= '8' where code = '957';
UPDATE district set mvalue_code = '97',mvalue_name= 'Vĩnh Lợi' ,mvalue_province_code= '8' where code = '958';
UPDATE district set mvalue_code = '98',mvalue_name= 'Bạc Liêu' ,mvalue_province_code= '8' where code = '954';
UPDATE district set mvalue_code = '107',mvalue_name= 'Ba Tri' ,mvalue_province_code= '10' where code = '836';
UPDATE district set mvalue_code = '108',mvalue_name= 'Bình Đại' ,mvalue_province_code= '10' where code = '835';
UPDATE district set mvalue_code = '109',mvalue_name= 'Châu Thành' ,mvalue_province_code= '10' where code = '831';
UPDATE district set mvalue_code = '110',mvalue_name= 'Chợ Lách' ,mvalue_province_code= '10' where code = '832';
UPDATE district set mvalue_code = '111',mvalue_name= 'Giồng Trôm' ,mvalue_province_code= '10' where code = '834';
UPDATE district set mvalue_code = '112',mvalue_name= 'Mỏ Cày Bắc' ,mvalue_province_code= '10' where code = '838';
UPDATE district set mvalue_code = '113',mvalue_name= 'Mỏ Cày Nam' ,mvalue_province_code= '10' where code = '833';
UPDATE district set mvalue_code = '114',mvalue_name= 'Thạnh Phú' ,mvalue_province_code= '10' where code = '837';
UPDATE district set mvalue_code = '115',mvalue_name= 'Bến Tre' ,mvalue_province_code= '10' where code = '829';
UPDATE district set mvalue_code = '116',mvalue_name= 'An Lão' ,mvalue_province_code= '11' where code = '542';
UPDATE district set mvalue_code = '117',mvalue_name= 'An Nhơn' ,mvalue_province_code= '11' where code = '549';
UPDATE district set mvalue_code = '118',mvalue_name= 'Hoài Ân' ,mvalue_province_code= '11' where code = '544';
UPDATE district set mvalue_code = '119',mvalue_name= 'Hoài Nhơn' ,mvalue_province_code= '11' where code = '543';
UPDATE district set mvalue_code = '120',mvalue_name= 'Phù Cát' ,mvalue_province_code= '11' where code = '548';
UPDATE district set mvalue_code = '121',mvalue_name= 'Phù Mỹ' ,mvalue_province_code= '11' where code = '545';
UPDATE district set mvalue_code = '122',mvalue_name= 'Tây Sơn' ,mvalue_province_code= '11' where code = '547';
UPDATE district set mvalue_code = '123',mvalue_name= 'Tuy Phước' ,mvalue_province_code= '11' where code = '550';
UPDATE district set mvalue_code = '124',mvalue_name= 'Vân Canh' ,mvalue_province_code= '11' where code = '551';
UPDATE district set mvalue_code = '125',mvalue_name= 'Vĩnh Thạnh' ,mvalue_province_code= '11' where code = '546';
UPDATE district set mvalue_code = '126',mvalue_name= 'Quy Nhơn' ,mvalue_province_code= '11' where code = 'CJ5_52_016';
UPDATE district set mvalue_code = '127',mvalue_name= 'Bến Cát' ,mvalue_province_code= '12' where code = '721';
UPDATE district set mvalue_code = '128',mvalue_name= 'Dầu Tiếng' ,mvalue_province_code= '12' where code = '720';
UPDATE district set mvalue_code = '129',mvalue_name= 'Dĩ An' ,mvalue_province_code= '12' where code = '724';
UPDATE district set mvalue_code = '130',mvalue_name= 'Phú Giáo' ,mvalue_province_code= '12' where code = '722';
UPDATE district set mvalue_code = '131',mvalue_name= 'Tân Uyên' ,mvalue_province_code= '12' where code = '723';
UPDATE district set mvalue_code = '132',mvalue_name= 'Thuận An' ,mvalue_province_code= '12' where code = '725';
UPDATE district set mvalue_code = '133',mvalue_name= 'Thủ Dầu Một' ,mvalue_province_code= '12' where code = '718';
UPDATE district set mvalue_code = '134',mvalue_name= 'Bình Long' ,mvalue_province_code= '13' where code = '690';
UPDATE district set mvalue_code = '135',mvalue_name= 'Bù Đăng' ,mvalue_province_code= '13' where code = '696';
UPDATE district set mvalue_code = '136',mvalue_name= 'Bù Đốp' ,mvalue_province_code= '13' where code = '137';
UPDATE district set mvalue_code = '137',mvalue_name= 'Chơn Thành' ,mvalue_province_code= '13' where code = '697';
UPDATE district set mvalue_code = '139',mvalue_name= 'Lộc Ninh' ,mvalue_province_code= '13' where code = '692';
UPDATE district set mvalue_code = '140',mvalue_name= 'Phước Long' ,mvalue_province_code= '13' where code = '688';
UPDATE district set mvalue_code = '141',mvalue_name= 'Đồng Xoài' ,mvalue_province_code= '13' where code = '689';
UPDATE district set mvalue_code = '142',mvalue_name= 'Bắc Bình' ,mvalue_province_code= '14' where code = '596';
UPDATE district set mvalue_code = '143',mvalue_name= 'Đức Linh' ,mvalue_province_code= '14' where code = '600';
UPDATE district set mvalue_code = '144',mvalue_name= 'Hàm Tân' ,mvalue_province_code= '14' where code = '601';
UPDATE district set mvalue_code = '145',mvalue_name= 'Hàm Thuận Bắc' ,mvalue_province_code= '14' where code = '597';
UPDATE district set mvalue_code = '146',mvalue_name= 'Hàm Thuận Nam' ,mvalue_province_code= '14' where code = '598';
UPDATE district set mvalue_code = '147',mvalue_name= 'Phú Quí' ,mvalue_province_code= '14' where code = '602';
UPDATE district set mvalue_code = '148',mvalue_name= 'Tánh Linh' ,mvalue_province_code= '14' where code = '599';
UPDATE district set mvalue_code = '149',mvalue_name= 'Tuy Phong' ,mvalue_province_code= '14' where code = '595';
UPDATE district set mvalue_code = '150',mvalue_name= 'Phan Thiết' ,mvalue_province_code= '14' where code = '593';
UPDATE district set mvalue_code = '151',mvalue_name= 'La Gi' ,mvalue_province_code= '14' where code = '594';
UPDATE district set mvalue_code = '152',mvalue_name= 'Cái Nước' ,mvalue_province_code= '15' where code = '969';
UPDATE district set mvalue_code = '153',mvalue_name= 'Đầm Dơi' ,mvalue_province_code= '15' where code = '970';
UPDATE district set mvalue_code = '154',mvalue_name= 'Năm Căn' ,mvalue_province_code= '15' where code = '971';
UPDATE district set mvalue_code = '155',mvalue_name= 'Ngọc Hiển' ,mvalue_province_code= '15' where code = '973';
UPDATE district set mvalue_code = '156',mvalue_name= 'Phú Tân' ,mvalue_province_code= '15' where code = '972';
UPDATE district set mvalue_code = '157',mvalue_name= 'Thới Bình' ,mvalue_province_code= '15' where code = '967';
UPDATE district set mvalue_code = '158',mvalue_name= 'Trần Văn Thời' ,mvalue_province_code= '15' where code = '968';
UPDATE district set mvalue_code = '159',mvalue_name= 'U Minh' ,mvalue_province_code= '15' where code = '966';
UPDATE district set mvalue_code = '160',mvalue_name= 'Cà Mau' ,mvalue_province_code= '15' where code = '964';
UPDATE district set mvalue_code = '161',mvalue_name= 'Cờ Đỏ' ,mvalue_province_code= '16' where code = '925';
UPDATE district set mvalue_code = '162',mvalue_name= 'Phong Điền' ,mvalue_province_code= '16' where code = '926';
UPDATE district set mvalue_code = '163',mvalue_name= 'Thới Lai' ,mvalue_province_code= '16' where code = '927';
UPDATE district set mvalue_code = '164',mvalue_name= 'Vĩnh Thạnh' ,mvalue_province_code= '16' where code = '924';
UPDATE district set mvalue_code = '165',mvalue_name= 'Bình Thuỷ' ,mvalue_province_code= '16' where code = '918';
UPDATE district set mvalue_code = '166',mvalue_name= 'Cái Răng' ,mvalue_province_code= '16' where code = '919';
UPDATE district set mvalue_code = '167',mvalue_name= 'Ninh Kiều' ,mvalue_province_code= '16' where code = '916';
UPDATE district set mvalue_code = '168',mvalue_name= 'Ô Môn' ,mvalue_province_code= '16' where code = '917';
UPDATE district set mvalue_code = '169',mvalue_name= 'Thốt Nốt' ,mvalue_province_code= '16' where code = '923';
UPDATE district set mvalue_code = '170',mvalue_name= 'Bảo Lạc' ,mvalue_province_code= '17' where code = '043';
UPDATE district set mvalue_code = '171',mvalue_name= 'Hạ Lang' ,mvalue_province_code= '17' where code = '048';
UPDATE district set mvalue_code = '172',mvalue_name= 'Hà Quảng' ,mvalue_province_code= '17' where code = '045';
UPDATE district set mvalue_code = '173',mvalue_name= 'Hoà An' ,mvalue_province_code= '17' where code = '051';
UPDATE district set mvalue_code = '174',mvalue_name= 'Nguyên Bình' ,mvalue_province_code= '17' where code = '052';
UPDATE district set mvalue_code = '176',mvalue_name= 'Quảng Uyên' ,mvalue_province_code= '17' where code = '049';
UPDATE district set mvalue_code = '177',mvalue_name= 'Thạch An' ,mvalue_province_code= '17' where code = '053';
UPDATE district set mvalue_code = '180',mvalue_name= 'Trùng Khánh' ,mvalue_province_code= '17' where code = '047';
UPDATE district set mvalue_code = '181',mvalue_name= 'Bảo Lâm' ,mvalue_province_code= '17' where code = '042';
UPDATE district set mvalue_code = '182',mvalue_name= 'Cao Bằng' ,mvalue_province_code= '17' where code = '040';
UPDATE district set mvalue_code = '183',mvalue_name= 'Hoà Vang' ,mvalue_province_code= '18' where code = '497';
UPDATE district set mvalue_code = '184',mvalue_name= 'Hoàng Sa' ,mvalue_province_code= '18' where code = '498';
UPDATE district set mvalue_code = '185',mvalue_name= 'Cẩm Lệ' ,mvalue_province_code= '18' where code = '495';
UPDATE district set mvalue_code = '186',mvalue_name= 'Hải Châu' ,mvalue_province_code= '18' where code = '492';
UPDATE district set mvalue_code = '187',mvalue_name= 'Liên Chiểu' ,mvalue_province_code= '18' where code = '490';
UPDATE district set mvalue_code = '188',mvalue_name= 'Ngũ Hành Sơn' ,mvalue_province_code= '18' where code = '494';
UPDATE district set mvalue_code = '189',mvalue_name= 'Sơn Trà' ,mvalue_province_code= '18' where code = '493';
UPDATE district set mvalue_code = '190',mvalue_name= 'Thanh Khê' ,mvalue_province_code= '18' where code = '491';
UPDATE district set mvalue_code = '191',mvalue_name= 'Buôn Đôn' ,mvalue_province_code= '19' where code = '647';
UPDATE district set mvalue_code = '192',mvalue_name= 'Cư Kuin' ,mvalue_province_code= '19' where code = '657';
UPDATE district set mvalue_code = '193',mvalue_name= 'Cư M''gar' ,mvalue_province_code= '19' where code = '648';
UPDATE district set mvalue_code = '194',mvalue_name= 'Ea H''leo' ,mvalue_province_code= '19' where code = '645';
UPDATE district set mvalue_code = '195',mvalue_name= 'Ea Kar' ,mvalue_province_code= '19' where code = '651';
UPDATE district set mvalue_code = '196',mvalue_name= 'Ea Súp' ,mvalue_province_code= '19' where code = '646';
UPDATE district set mvalue_code = '197',mvalue_name= 'Krông A Na' ,mvalue_province_code= '19' where code = '655';
UPDATE district set mvalue_code = '198',mvalue_name= 'Krông Bông' ,mvalue_province_code= '19' where code = '653';
UPDATE district set mvalue_code = '199',mvalue_name= 'Krông Búk' ,mvalue_province_code= '19' where code = '649';
UPDATE district set mvalue_code = '200',mvalue_name= 'Krông Năng' ,mvalue_province_code= '19' where code = '650';
UPDATE district set mvalue_code = '201',mvalue_name= 'Krông Pắc' ,mvalue_province_code= '19' where code = '654';
UPDATE district set mvalue_code = '202',mvalue_name= 'Lắk' ,mvalue_province_code= '19' where code = '656';
UPDATE district set mvalue_code = '203',mvalue_name= 'M''Đrắk' ,mvalue_province_code= '19' where code = '652';
UPDATE district set mvalue_code = '204',mvalue_name= 'Buôn Ma Thuột' ,mvalue_province_code= '19' where code = '643';
UPDATE district set mvalue_code = '205',mvalue_name= 'Buôn Hồ' ,mvalue_province_code= '19' where code = '644';
UPDATE district set mvalue_code = '206',mvalue_name= 'Cư Jút' ,mvalue_province_code= '20' where code = '662';
UPDATE district set mvalue_code = '207',mvalue_name= 'Đắk Glong' ,mvalue_province_code= '20' where code = '661';
UPDATE district set mvalue_code = '208',mvalue_name= 'Đắk Mil' ,mvalue_province_code= '20' where code = '663';
UPDATE district set mvalue_code = '209',mvalue_name= 'Đắk R''Lấp' ,mvalue_province_code= '20' where code = '666';
UPDATE district set mvalue_code = '210',mvalue_name= 'Đắk Song' ,mvalue_province_code= '20' where code = '665';
UPDATE district set mvalue_code = '211',mvalue_name= 'Krông Nô' ,mvalue_province_code= '20' where code = '664';
UPDATE district set mvalue_code = '212',mvalue_name= 'Tuy Đức' ,mvalue_province_code= '20' where code = '667';
UPDATE district set mvalue_code = '213',mvalue_name= 'Gia Nghĩa' ,mvalue_province_code= '20' where code = '660';
UPDATE district set mvalue_code = '214',mvalue_name= 'Điện Biên' ,mvalue_province_code= '21' where code = '100';
UPDATE district set mvalue_code = '215',mvalue_name= 'Điện Biên Đông' ,mvalue_province_code= '21' where code = '101';
UPDATE district set mvalue_code = '216',mvalue_name= 'Mường ảng' ,mvalue_province_code= '21' where code = '102';
UPDATE district set mvalue_code = '217',mvalue_name= 'Mường Chà' ,mvalue_province_code= '21' where code = '097';
UPDATE district set mvalue_code = '218',mvalue_name= 'Mường Nhé' ,mvalue_province_code= '21' where code = '096';
UPDATE district set mvalue_code = '219',mvalue_name= 'Tủa Chùa' ,mvalue_province_code= '21' where code = '098';
UPDATE district set mvalue_code = '220',mvalue_name= 'Tuần Giáo' ,mvalue_province_code= '21' where code = '099';
UPDATE district set mvalue_code = '221',mvalue_name= 'Điện Biên Phủ' ,mvalue_province_code= '21' where code = '094';
UPDATE district set mvalue_code = '222',mvalue_name= 'Mường Lay' ,mvalue_province_code= '21' where code = '095';
UPDATE district set mvalue_code = '223',mvalue_name= 'Cẩm Mỹ' ,mvalue_province_code= '22' where code = '739';
UPDATE district set mvalue_code = '224',mvalue_name= 'Định Quán' ,mvalue_province_code= '22' where code = '736';
UPDATE district set mvalue_code = '225',mvalue_name= 'Long Thành' ,mvalue_province_code= '22' where code = '740';
UPDATE district set mvalue_code = '226',mvalue_name= 'Nhơn Trạch' ,mvalue_province_code= '22' where code = '742';
UPDATE district set mvalue_code = '227',mvalue_name= 'Tân Phú' ,mvalue_province_code= '22' where code = '734';
UPDATE district set mvalue_code = '228',mvalue_name= 'Thống Nhất' ,mvalue_province_code= '22' where code = '738';
UPDATE district set mvalue_code = '229',mvalue_name= 'Trảng Bom' ,mvalue_province_code= '22' where code = '737';
UPDATE district set mvalue_code = '230',mvalue_name= 'Vĩnh Cửu' ,mvalue_province_code= '22' where code = '735';
UPDATE district set mvalue_code = '231',mvalue_name= 'Xuân Lộc' ,mvalue_province_code= '22' where code = '741';
UPDATE district set mvalue_code = '232',mvalue_name= 'Biên Hòa' ,mvalue_province_code= '22' where code = '731';
UPDATE district set mvalue_code = '233',mvalue_name= 'Long Khánh' ,mvalue_province_code= '22' where code = '732';
UPDATE district set mvalue_code = '234',mvalue_name= 'Cao Lãnh' ,mvalue_province_code= '23' where code = '866';
UPDATE district set mvalue_code = '235',mvalue_name= 'Châu Thành' ,mvalue_province_code= '23' where code = '877';
UPDATE district set mvalue_code = '236',mvalue_name= 'Hồng Ngự' ,mvalue_province_code= '23' where code = '868';
UPDATE district set mvalue_code = '237',mvalue_name= 'Lai Vung' ,mvalue_province_code= '23' where code = '876';
UPDATE district set mvalue_code = '238',mvalue_name= 'Lấp Vò' ,mvalue_province_code= '23' where code = '875';
UPDATE district set mvalue_code = '239',mvalue_name= 'Tam Nông' ,mvalue_province_code= '23' where code = '871';
UPDATE district set mvalue_code = '240',mvalue_name= 'Tân Hồng' ,mvalue_province_code= '23' where code = '869';
UPDATE district set mvalue_code = '241',mvalue_name= 'Thanh Bình' ,mvalue_province_code= '23' where code = '874';
UPDATE district set mvalue_code = '242',mvalue_name= 'Tháp Mười' ,mvalue_province_code= '23' where code = '872';
UPDATE district set mvalue_code = '243',mvalue_name= 'Cao Lãnh' ,mvalue_province_code= '23' where code = '866';
UPDATE district set mvalue_code = '244',mvalue_name= 'Hồng Ngự' ,mvalue_province_code= '23' where code = '868';
UPDATE district set mvalue_code = '245',mvalue_name= 'Sa Đéc' ,mvalue_province_code= '23' where code = '867';
UPDATE district set mvalue_code = '246',mvalue_name= 'Chư Păh' ,mvalue_province_code= '24' where code = '627';
UPDATE district set mvalue_code = '247',mvalue_name= 'Chư Prông' ,mvalue_province_code= '24' where code = '632';
UPDATE district set mvalue_code = '248',mvalue_name= 'Chư Sê' ,mvalue_province_code= '24' where code = '633';
UPDATE district set mvalue_code = '249',mvalue_name= 'Đăk Đoa' ,mvalue_province_code= '24' where code = '626';
UPDATE district set mvalue_code = '250',mvalue_name= 'Đăk Pơ' ,mvalue_province_code= '24' where code = '634';
UPDATE district set mvalue_code = '251',mvalue_name= 'Đức Cơ' ,mvalue_province_code= '24' where code = '631';
UPDATE district set mvalue_code = '252',mvalue_name= 'Ia Grai' ,mvalue_province_code= '24' where code = '628';
UPDATE district set mvalue_code = '253',mvalue_name= 'Ia Pa' ,mvalue_province_code= '24' where code = '635';
UPDATE district set mvalue_code = '254',mvalue_name= 'KBang' ,mvalue_province_code= '24' where code = '625';
UPDATE district set mvalue_code = '255',mvalue_name= 'Kông Chro' ,mvalue_province_code= '24' where code = '630';
UPDATE district set mvalue_code = '256',mvalue_name= 'Krông Pa' ,mvalue_province_code= '24' where code = '637';
UPDATE district set mvalue_code = '257',mvalue_name= 'Mang Yang' ,mvalue_province_code= '24' where code = '629';
UPDATE district set mvalue_code = '258',mvalue_name= 'Phú Thiện' ,mvalue_province_code= '24' where code = '638';
UPDATE district set mvalue_code = '259',mvalue_name= 'Pleiku' ,mvalue_province_code= '24' where code = '622';
UPDATE district set mvalue_code = '260',mvalue_name= 'An Khê' ,mvalue_province_code= '24' where code = '623';
UPDATE district set mvalue_code = '261',mvalue_name= 'Ayun Pa' ,mvalue_province_code= '24' where code = '624';
UPDATE district set mvalue_code = '262',mvalue_name= 'Bắc Mê' ,mvalue_province_code= '25' where code = '031';
UPDATE district set mvalue_code = '263',mvalue_name= 'Bắc Quang' ,mvalue_province_code= '25' where code = '034';
UPDATE district set mvalue_code = '264',mvalue_name= 'Đồng Văn' ,mvalue_province_code= '25' where code = '026';
UPDATE district set mvalue_code = '265',mvalue_name= 'Hoàng Su Phì' ,mvalue_province_code= '25' where code = '032';
UPDATE district set mvalue_code = '266',mvalue_name= 'Mèo Vạc' ,mvalue_province_code= '25' where code = '027';
UPDATE district set mvalue_code = '267',mvalue_name= 'Quản Bạ' ,mvalue_province_code= '25' where code = '029';
UPDATE district set mvalue_code = '268',mvalue_name= 'Quang Bình' ,mvalue_province_code= '25' where code = '035';
UPDATE district set mvalue_code = '269',mvalue_name= 'Vị Xuyên' ,mvalue_province_code= '25' where code = '030';
UPDATE district set mvalue_code = '270',mvalue_name= 'Xín Mần' ,mvalue_province_code= '25' where code = '033';
UPDATE district set mvalue_code = '271',mvalue_name= 'Yên Minh' ,mvalue_province_code= '25' where code = '028';
UPDATE district set mvalue_code = '272',mvalue_name= 'Hà Giang' ,mvalue_province_code= '25' where code = '024';
UPDATE district set mvalue_code = '273',mvalue_name= 'Bình Lục' ,mvalue_province_code= '26' where code = '352';
UPDATE district set mvalue_code = '274',mvalue_name= 'Duy Tiên' ,mvalue_province_code= '26' where code = '349';
UPDATE district set mvalue_code = '275',mvalue_name= 'Kim Bảng' ,mvalue_province_code= '26' where code = '350';
UPDATE district set mvalue_code = '276',mvalue_name= 'Lý Nhân' ,mvalue_province_code= '26' where code = '353';
UPDATE district set mvalue_code = '277',mvalue_name= 'Thanh Liêm' ,mvalue_province_code= '26' where code = '351';
UPDATE district set mvalue_code = '278',mvalue_name= 'Phủ Lý' ,mvalue_province_code= '26' where code = '347';
UPDATE district set mvalue_code = '279',mvalue_name= 'Cẩm Xuyên' ,mvalue_province_code= '27' where code = '446';
UPDATE district set mvalue_code = '280',mvalue_name= 'Can Lộc' ,mvalue_province_code= '27' where code = '443';
UPDATE district set mvalue_code = '281',mvalue_name= 'Đức Thọ' ,mvalue_province_code= '27' where code = '440';
UPDATE district set mvalue_code = '282',mvalue_name= 'Hương Khê' ,mvalue_province_code= '27' where code = '444';
UPDATE district set mvalue_code = '283',mvalue_name= 'Hương Sơn' ,mvalue_province_code= '27' where code = '439';
UPDATE district set mvalue_code = '284',mvalue_name= 'Kỳ Anh' ,mvalue_province_code= '27' where code = '447';
UPDATE district set mvalue_code = '285',mvalue_name= 'Lộc Hà' ,mvalue_province_code= '27' where code = '448';
UPDATE district set mvalue_code = '286',mvalue_name= 'Nghi Xuân' ,mvalue_province_code= '27' where code = '442';
UPDATE district set mvalue_code = '287',mvalue_name= 'Thạch Hà' ,mvalue_province_code= '27' where code = '445';
UPDATE district set mvalue_code = '288',mvalue_name= 'Vũ Quang' ,mvalue_province_code= '27' where code = '441';
UPDATE district set mvalue_code = '289',mvalue_name= 'Hà Tĩnh' ,mvalue_province_code= '27' where code = '436';
UPDATE district set mvalue_code = '290',mvalue_name= 'Hồng Lĩnh' ,mvalue_province_code= '27' where code = '437';
UPDATE district set mvalue_code = '291',mvalue_name= 'Bình Giang' ,mvalue_province_code= '28' where code = '296';
UPDATE district set mvalue_code = '292',mvalue_name= 'Cẩm Giàng' ,mvalue_province_code= '28' where code = '295';
UPDATE district set mvalue_code = '293',mvalue_name= 'Chí Linh' ,mvalue_province_code= '28' where code = '290';
UPDATE district set mvalue_code = '294',mvalue_name= 'Gia Lộc' ,mvalue_province_code= '28' where code = '297';
UPDATE district set mvalue_code = '295',mvalue_name= 'Kim Thành' ,mvalue_province_code= '28' where code = '293';
UPDATE district set mvalue_code = '296',mvalue_name= 'Kinh Môn' ,mvalue_province_code= '28' where code = '292';
UPDATE district set mvalue_code = '297',mvalue_name= 'Nam Sách' ,mvalue_province_code= '28' where code = '291';
UPDATE district set mvalue_code = '298',mvalue_name= 'Ninh Giang' ,mvalue_province_code= '28' where code = '299';
UPDATE district set mvalue_code = '299',mvalue_name= 'Thanh Hà' ,mvalue_province_code= '28' where code = '294';
UPDATE district set mvalue_code = '300',mvalue_name= 'Thanh Miện' ,mvalue_province_code= '28' where code = '300';
UPDATE district set mvalue_code = '301',mvalue_name= 'Tứ Kỳ' ,mvalue_province_code= '28' where code = '298';
UPDATE district set mvalue_code = '302',mvalue_name= 'Hải Dương' ,mvalue_province_code= '28' where code = '288';
UPDATE district set mvalue_code = '303',mvalue_name= 'An Dương' ,mvalue_province_code= '29' where code = '312';
UPDATE district set mvalue_code = '304',mvalue_name= 'An Lão' ,mvalue_province_code= '29' where code = '313';
UPDATE district set mvalue_code = '305',mvalue_name= 'Bạch Long Vĩ' ,mvalue_province_code= '29' where code = '318';
UPDATE district set mvalue_code = '306',mvalue_name= 'Cát Hải' ,mvalue_province_code= '29' where code = '317';
UPDATE district set mvalue_code = '307',mvalue_name= 'Kiến Thuỵ' ,mvalue_province_code= '29' where code = '314';
UPDATE district set mvalue_code = '308',mvalue_name= 'Thuỷ Nguyên' ,mvalue_province_code= '29' where code = '311';
UPDATE district set mvalue_code = '309',mvalue_name= 'Tiên Lãng' ,mvalue_province_code= '29' where code = '315';
UPDATE district set mvalue_code = '310',mvalue_name= 'Vĩnh Bảo' ,mvalue_province_code= '29' where code = '316';
UPDATE district set mvalue_code = '311',mvalue_name= 'Đồ Sơn' ,mvalue_province_code= '29' where code = '308';
UPDATE district set mvalue_code = '313',mvalue_name= 'Hải An' ,mvalue_province_code= '29' where code = '306';
UPDATE district set mvalue_code = '314',mvalue_name= 'Hồng Bàng' ,mvalue_province_code= '29' where code = '303';
UPDATE district set mvalue_code = '315',mvalue_name= 'Kiến An' ,mvalue_province_code= '29' where code = '307';
UPDATE district set mvalue_code = '316',mvalue_name= 'Lê Chân' ,mvalue_province_code= '29' where code = '305';
UPDATE district set mvalue_code = '317',mvalue_name= 'Ngô Quyền' ,mvalue_province_code= '29' where code = '304';
UPDATE district set mvalue_code = '318',mvalue_name= 'Châu Thành A' ,mvalue_province_code= '30' where code = '932';
UPDATE district set mvalue_code = '319',mvalue_name= 'Châu Thành' ,mvalue_province_code= '30' where code = '933';
UPDATE district set mvalue_code = '320',mvalue_name= 'Long Mỹ' ,mvalue_province_code= '30' where code = '936';
UPDATE district set mvalue_code = '321',mvalue_name= 'Phụng Hiệp' ,mvalue_province_code= '30' where code = '934';
UPDATE district set mvalue_code = '322',mvalue_name= 'Vị Thuỷ' ,mvalue_province_code= '30' where code = '935';
UPDATE district set mvalue_code = '323',mvalue_name= 'Ngã Bảy' ,mvalue_province_code= '30' where code = '931';
UPDATE district set mvalue_code = '324',mvalue_name= 'Vị Thanh' ,mvalue_province_code= '30' where code = '930';
UPDATE district set mvalue_code = '325',mvalue_name= 'Cao Phong' ,mvalue_province_code= '31' where code = '497';
UPDATE district set mvalue_code = '326',mvalue_name= 'Đà Bắc' ,mvalue_province_code= '31' where code = '150';
UPDATE district set mvalue_code = '327',mvalue_name= 'Kim Bôi' ,mvalue_province_code= '31' where code = '153';
UPDATE district set mvalue_code = '329',mvalue_name= 'Lạc Sơn' ,mvalue_province_code= '31' where code = '157';
UPDATE district set mvalue_code = '330',mvalue_name= 'Lạc Thủy' ,mvalue_province_code= '31' where code = '159';
UPDATE district set mvalue_code = '331',mvalue_name= 'Lương Sơn' ,mvalue_province_code= '31' where code = '152';
UPDATE district set mvalue_code = '332',mvalue_name= 'Mai Châu' ,mvalue_province_code= '31' where code = '156';
UPDATE district set mvalue_code = '333',mvalue_name= 'Tân Lạc' ,mvalue_province_code= '31' where code = '155';
UPDATE district set mvalue_code = '334',mvalue_name= 'Yên Thủy' ,mvalue_province_code= '31' where code = '158';
UPDATE district set mvalue_code = '335',mvalue_name= 'Hòa Bình' ,mvalue_province_code= '31' where code = '148';
UPDATE district set mvalue_code = '336',mvalue_name= 'Ân Thi' ,mvalue_province_code= '32' where code = '329';
UPDATE district set mvalue_code = '337',mvalue_name= 'Khoái Châu' ,mvalue_province_code= '32' where code = '330';
UPDATE district set mvalue_code = '338',mvalue_name= 'Kim Động' ,mvalue_province_code= '32' where code = '331';
UPDATE district set mvalue_code = '339',mvalue_name= 'Mỹ Hào' ,mvalue_province_code= '32' where code = '328';
UPDATE district set mvalue_code = '340',mvalue_name= 'Phù Cừ' ,mvalue_province_code= '32' where code = '333';
UPDATE district set mvalue_code = '341',mvalue_name= 'Tiên Lữ' ,mvalue_province_code= '32' where code = '332';
UPDATE district set mvalue_code = '342',mvalue_name= 'Văn Giang' ,mvalue_province_code= '32' where code = '326';
UPDATE district set mvalue_code = '343',mvalue_name= 'Văn Lâm' ,mvalue_province_code= '32' where code = '325';
UPDATE district set mvalue_code = '344',mvalue_name= 'Yên Mỹ' ,mvalue_province_code= '32' where code = '327';
UPDATE district set mvalue_code = '345',mvalue_name= 'Hưng Yên' ,mvalue_province_code= '32' where code = '323';
UPDATE district set mvalue_code = '346',mvalue_name= 'Cam Lâm' ,mvalue_province_code= '33' where code = '570';
UPDATE district set mvalue_code = '347',mvalue_name= 'Diên Khánh' ,mvalue_province_code= '33' where code = '574';
UPDATE district set mvalue_code = '348',mvalue_name= 'Khánh Sơn' ,mvalue_province_code= '33' where code = '575';
UPDATE district set mvalue_code = '350',mvalue_name= 'Ninh Hòa' ,mvalue_province_code= '33' where code = '572';
UPDATE district set mvalue_code = '351',mvalue_name= 'Trường Sa' ,mvalue_province_code= '33' where code = '576';
UPDATE district set mvalue_code = '352',mvalue_name= 'Vạn Ninh' ,mvalue_province_code= '33' where code = '571';
UPDATE district set mvalue_code = '353',mvalue_name= 'Nha Trang' ,mvalue_province_code= '33' where code = '568';
UPDATE district set mvalue_code = '354',mvalue_name= 'Cam Ranh' ,mvalue_province_code= '33' where code = '569';
UPDATE district set mvalue_code = '355',mvalue_name= 'An Biên' ,mvalue_province_code= '34' where code = '908';
UPDATE district set mvalue_code = '356',mvalue_name= 'An Minh' ,mvalue_province_code= '34' where code = '909';
UPDATE district set mvalue_code = '357',mvalue_name= 'Châu Thành' ,mvalue_province_code= '34' where code = '905';
UPDATE district set mvalue_code = '358',mvalue_name= 'Giồng Riềng' ,mvalue_province_code= '34' where code = '906';
UPDATE district set mvalue_code = '359',mvalue_name= 'Gò Quao' ,mvalue_province_code= '34' where code = '907';
UPDATE district set mvalue_code = '360',mvalue_name= 'Hòn Đất' ,mvalue_province_code= '34' where code = '903';
UPDATE district set mvalue_code = '361',mvalue_name= 'Kiên Hải' ,mvalue_province_code= '34' where code = '912';
UPDATE district set mvalue_code = '362',mvalue_name= 'Kiên Lương' ,mvalue_province_code= '34' where code = '902';
UPDATE district set mvalue_code = '363',mvalue_name= 'Phú Quốc' ,mvalue_province_code= '34' where code = '911';
UPDATE district set mvalue_code = '364',mvalue_name= 'Tân Hiệp' ,mvalue_province_code= '34' where code = '904';
UPDATE district set mvalue_code = '365',mvalue_name= 'U Minh Thượng' ,mvalue_province_code= '34' where code = '913';
UPDATE district set mvalue_code = '366',mvalue_name= 'Vĩnh Thuận' ,mvalue_province_code= '34' where code = '910';
UPDATE district set mvalue_code = '367',mvalue_name= 'Rạch Giá' ,mvalue_province_code= '34' where code = '899';
UPDATE district set mvalue_code = '368',mvalue_name= 'Hà Tiên' ,mvalue_province_code= '34' where code = '900';
UPDATE district set mvalue_code = '369',mvalue_name= 'Đắk Glei' ,mvalue_province_code= '35' where code = '610';
UPDATE district set mvalue_code = '370',mvalue_name= 'Đắk Hà' ,mvalue_province_code= '35' where code = '615';
UPDATE district set mvalue_code = '371',mvalue_name= 'Đắk Tô' ,mvalue_province_code= '35' where code = '612';
UPDATE district set mvalue_code = '372',mvalue_name= 'Kon Plông' ,mvalue_province_code= '35' where code = '613';
UPDATE district set mvalue_code = '373',mvalue_name= 'Kon Rẫy' ,mvalue_province_code= '35' where code = '614';
UPDATE district set mvalue_code = '374',mvalue_name= 'Ngọc Hồi' ,mvalue_province_code= '35' where code = '611';
UPDATE district set mvalue_code = '375',mvalue_name= 'Sa Thầy' ,mvalue_province_code= '35' where code = '616';
UPDATE district set mvalue_code = '376',mvalue_name= 'Tu Mơ Rông' ,mvalue_province_code= '35' where code = '617';
UPDATE district set mvalue_code = '377',mvalue_name= 'Kon Tum' ,mvalue_province_code= '35' where code = '608';
UPDATE district set mvalue_code = '378',mvalue_name= 'Mường Tè' ,mvalue_province_code= '36' where code = '107';
UPDATE district set mvalue_code = '379',mvalue_name= 'Phong Thổ' ,mvalue_province_code= '36' where code = '109';
UPDATE district set mvalue_code = '380',mvalue_name= 'Sìn Hồ' ,mvalue_province_code= '36' where code = '108';
UPDATE district set mvalue_code = '381',mvalue_name= 'Tam Đường' ,mvalue_province_code= '36' where code = '106';
UPDATE district set mvalue_code = '382',mvalue_name= 'Tân Uyên' ,mvalue_province_code= '36' where code = '111';
UPDATE district set mvalue_code = '383',mvalue_name= 'Than Uyên' ,mvalue_province_code= '36' where code = '110';
UPDATE district set mvalue_code = '384',mvalue_name= 'Lai Châu' ,mvalue_province_code= '36' where code = '105';
UPDATE district set mvalue_code = '385',mvalue_name= 'Bảo Lâm' ,mvalue_province_code= '37' where code = '680';
UPDATE district set mvalue_code = '386',mvalue_name= 'Cát Tiên' ,mvalue_province_code= '37' where code = '683';
UPDATE district set mvalue_code = '387',mvalue_name= 'Đạ Huoai' ,mvalue_province_code= '37' where code = '681';
UPDATE district set mvalue_code = '388',mvalue_name= 'Đạ Tẻh' ,mvalue_province_code= '37' where code = '682';
UPDATE district set mvalue_code = '389',mvalue_name= 'Đam Rông' ,mvalue_province_code= '37' where code = '674';
UPDATE district set mvalue_code = '390',mvalue_name= 'Di Linh' ,mvalue_province_code= '37' where code = '679';
UPDATE district set mvalue_code = '391',mvalue_name= 'Đơn Dương' ,mvalue_province_code= '37' where code = '677';
UPDATE district set mvalue_code = '392',mvalue_name= 'Đức Trọng' ,mvalue_province_code= '37' where code = '678';
UPDATE district set mvalue_code = '393',mvalue_name= 'Lạc Dương' ,mvalue_province_code= '37' where code = '675';
UPDATE district set mvalue_code = '394',mvalue_name= 'Lâm Hà' ,mvalue_province_code= '37' where code = '676';
UPDATE district set mvalue_code = '395',mvalue_name= 'Đà Lạt' ,mvalue_province_code= '37' where code = '672';
UPDATE district set mvalue_code = '396',mvalue_name= 'Bảo Lộc' ,mvalue_province_code= '37' where code = '673';
UPDATE district set mvalue_code = '397',mvalue_name= 'Bắc Sơn' ,mvalue_province_code= '38' where code = '185';
UPDATE district set mvalue_code = '398',mvalue_name= 'Bình Gia' ,mvalue_province_code= '38' where code = '181';
UPDATE district set mvalue_code = '399',mvalue_name= 'Cao Lộc' ,mvalue_province_code= '38' where code = '183';
UPDATE district set mvalue_code = '400',mvalue_name= 'Chi Lăng' ,mvalue_province_code= '38' where code = '187';
UPDATE district set mvalue_code = '401',mvalue_name= 'Đình Lập' ,mvalue_province_code= '38' where code = '189';
UPDATE district set mvalue_code = '402',mvalue_name= 'Hữu Lũng' ,mvalue_province_code= '38' where code = '186';
UPDATE district set mvalue_code = '403',mvalue_name= 'Lộc Bình' ,mvalue_province_code= '38' where code = '188';
UPDATE district set mvalue_code = '404',mvalue_name= 'Tràng Định' ,mvalue_province_code= '38' where code = '180';
UPDATE district set mvalue_code = '405',mvalue_name= 'Văn Lãng' ,mvalue_province_code= '38' where code = '182';
UPDATE district set mvalue_code = '406',mvalue_name= 'Văn Quan' ,mvalue_province_code= '38' where code = '184';
UPDATE district set mvalue_code = '407',mvalue_name= 'Lạng Sơn' ,mvalue_province_code= '38' where code = '178';
UPDATE district set mvalue_code = '408',mvalue_name= 'Bắc Hà' ,mvalue_province_code= '39' where code = '085';
UPDATE district set mvalue_code = '409',mvalue_name= 'Bảo Thắng' ,mvalue_province_code= '39' where code = '086';
UPDATE district set mvalue_code = '410',mvalue_name= 'Bảo Yên' ,mvalue_province_code= '39' where code = '087';
UPDATE district set mvalue_code = '411',mvalue_name= 'Bát Xát' ,mvalue_province_code= '39' where code = '082';
UPDATE district set mvalue_code = '412',mvalue_name= 'Mường Khương' ,mvalue_province_code= '39' where code = '083';
UPDATE district set mvalue_code = '413',mvalue_name= 'Sa Pa' ,mvalue_province_code= '39' where code = '088';
UPDATE district set mvalue_code = '414',mvalue_name= 'Si Ma Cai' ,mvalue_province_code= '39' where code = '084';
UPDATE district set mvalue_code = '415',mvalue_name= 'Văn Bàn' ,mvalue_province_code= '39' where code = '089';
UPDATE district set mvalue_code = '416',mvalue_name= 'Lào Cai' ,mvalue_province_code= '39' where code = '080';
UPDATE district set mvalue_code = '417',mvalue_name= 'Bến Lức' ,mvalue_province_code= '40' where code = '803';
UPDATE district set mvalue_code = '418',mvalue_name= 'Cần Đước' ,mvalue_province_code= '40' where code = '806';
UPDATE district set mvalue_code = '419',mvalue_name= 'Cần Giuộc' ,mvalue_province_code= '40' where code = '807';
UPDATE district set mvalue_code = '420',mvalue_name= 'Châu Thành' ,mvalue_province_code= '40' where code = '808';
UPDATE district set mvalue_code = '421',mvalue_name= 'Đức Hòa' ,mvalue_province_code= '40' where code = '802';
UPDATE district set mvalue_code = '422',mvalue_name= 'Đức Huệ' ,mvalue_province_code= '40' where code = '801';
UPDATE district set mvalue_code = '423',mvalue_name= 'Mộc Hóa' ,mvalue_province_code= '40' where code = '798';
UPDATE district set mvalue_code = '424',mvalue_name= 'Tân Hưng' ,mvalue_province_code= '40' where code = '796';
UPDATE district set mvalue_code = '425',mvalue_name= 'Tân Thạnh' ,mvalue_province_code= '40' where code = '799';
UPDATE district set mvalue_code = '426',mvalue_name= 'Tân Trụ' ,mvalue_province_code= '40' where code = '805';
UPDATE district set mvalue_code = '427',mvalue_name= 'Thạnh Hóa' ,mvalue_province_code= '40' where code = '800';
UPDATE district set mvalue_code = '428',mvalue_name= 'Thủ Thừa' ,mvalue_province_code= '40' where code = '804';
UPDATE district set mvalue_code = '429',mvalue_name= 'Vĩnh Hưng' ,mvalue_province_code= '40' where code = '797';
UPDATE district set mvalue_code = '430',mvalue_name= 'Tân An' ,mvalue_province_code= '40' where code = '794';
UPDATE district set mvalue_code = '431',mvalue_name= 'Giao Thủy' ,mvalue_province_code= '41' where code = '365';
UPDATE district set mvalue_code = '432',mvalue_name= 'Hải Hậu' ,mvalue_province_code= '41' where code = '366';
UPDATE district set mvalue_code = '433',mvalue_name= 'Mỹ Lộc' ,mvalue_province_code= '41' where code = '358';
UPDATE district set mvalue_code = '434',mvalue_name= 'Nam Trực' ,mvalue_province_code= '41' where code = '362';
UPDATE district set mvalue_code = '435',mvalue_name= 'Nghĩa Hưng' ,mvalue_province_code= '41' where code = '361';
UPDATE district set mvalue_code = '436',mvalue_name= 'Trực Ninh' ,mvalue_province_code= '41' where code = '363';
UPDATE district set mvalue_code = '437',mvalue_name= 'Vụ Bản' ,mvalue_province_code= '41' where code = '359';
UPDATE district set mvalue_code = '438',mvalue_name= 'Xuân Trường' ,mvalue_province_code= '41' where code = '364';
UPDATE district set mvalue_code = '439',mvalue_name= 'Ý Yên' ,mvalue_province_code= '41' where code = '360';
UPDATE district set mvalue_code = '440',mvalue_name= 'Nam Định' ,mvalue_province_code= '41' where code = '356';
UPDATE district set mvalue_code = '441',mvalue_name= 'Anh Sơn' ,mvalue_province_code= '42' where code = '424';
UPDATE district set mvalue_code = '442',mvalue_name= 'Con Cuông' ,mvalue_province_code= '42' where code = '422';
UPDATE district set mvalue_code = '443',mvalue_name= 'Diễn Châu' ,mvalue_province_code= '42' where code = '425';
UPDATE district set mvalue_code = '444',mvalue_name= 'Đô Lương' ,mvalue_province_code= '42' where code = '427';
UPDATE district set mvalue_code = '445',mvalue_name= 'Hưng Nguyên' ,mvalue_province_code= '42' where code = '431';
UPDATE district set mvalue_code = '446',mvalue_name= 'Kỳ Sơn' ,mvalue_province_code= '42' where code = '417';
UPDATE district set mvalue_code = '447',mvalue_name= 'Nam Đàn' ,mvalue_province_code= '42' where code = '430';
UPDATE district set mvalue_code = '448',mvalue_name= 'Nghi Lộc' ,mvalue_province_code= '42' where code = '429';
UPDATE district set mvalue_code = '449',mvalue_name= 'Nghĩa Đàn' ,mvalue_province_code= '42' where code = '419';
UPDATE district set mvalue_code = '450',mvalue_name= 'Quế Phong' ,mvalue_province_code= '42' where code = '415';
UPDATE district set mvalue_code = '451',mvalue_name= 'Quỳ Châu' ,mvalue_province_code= '42' where code = '416';
UPDATE district set mvalue_code = '452',mvalue_name= 'Quỳ Hợp' ,mvalue_province_code= '42' where code = '420';
UPDATE district set mvalue_code = '453',mvalue_name= 'Quỳnh Lưu' ,mvalue_province_code= '42' where code = '421';
UPDATE district set mvalue_code = '454',mvalue_name= 'Tân Kỳ' ,mvalue_province_code= '42' where code = '423';
UPDATE district set mvalue_code = '455',mvalue_name= 'Thanh Chương' ,mvalue_province_code= '42' where code = '428';
UPDATE district set mvalue_code = '456',mvalue_name= 'Tương Dương' ,mvalue_province_code= '42' where code = '418';
UPDATE district set mvalue_code = '457',mvalue_name= 'Yên Thành' ,mvalue_province_code= '42' where code = '426';
UPDATE district set mvalue_code = '458',mvalue_name= 'Vinh' ,mvalue_province_code= '42' where code = '412';
UPDATE district set mvalue_code = '459',mvalue_name= 'Cửa Lò' ,mvalue_province_code= '42' where code = '413';
UPDATE district set mvalue_code = '460',mvalue_name= 'Thái Hoà' ,mvalue_province_code= '42' where code = '414';
UPDATE district set mvalue_code = '461',mvalue_name= 'Gia Viễn' ,mvalue_province_code= '43' where code = '373';
UPDATE district set mvalue_code = '462',mvalue_name= 'Hoa Lư' ,mvalue_province_code= '43' where code = '374';
UPDATE district set mvalue_code = '463',mvalue_name= 'Kim Sơn' ,mvalue_province_code= '43' where code = '376';
UPDATE district set mvalue_code = '464',mvalue_name= 'Nho Quan' ,mvalue_province_code= '43' where code = '372';
UPDATE district set mvalue_code = '465',mvalue_name= 'Yên Khánh' ,mvalue_province_code= '43' where code = '375';
UPDATE district set mvalue_code = '466',mvalue_name= 'Yên Mô' ,mvalue_province_code= '43' where code = '377';
UPDATE district set mvalue_code = '467',mvalue_name= 'Ninh Bình' ,mvalue_province_code= '43' where code = '369';
UPDATE district set mvalue_code = '468',mvalue_name= 'Tam Điệp' ,mvalue_province_code= '43' where code = '370';
UPDATE district set mvalue_code = '469',mvalue_name= 'Bác ái' ,mvalue_province_code= '44' where code = '584';
UPDATE district set mvalue_code = '470',mvalue_name= 'Ninh Hải' ,mvalue_province_code= '44' where code = '586';
UPDATE district set mvalue_code = '471',mvalue_name= 'Ninh Phước' ,mvalue_province_code= '44' where code = '587';
UPDATE district set mvalue_code = '472',mvalue_name= 'Ninh Sơn' ,mvalue_province_code= '44' where code = '585';
UPDATE district set mvalue_code = '473',mvalue_name= 'Thuận Bắc' ,mvalue_province_code= '44' where code = '588';
UPDATE district set mvalue_code = '474',mvalue_name= 'Thuận Nam' ,mvalue_province_code= '44' where code = '589';
UPDATE district set mvalue_code = '475',mvalue_name= 'Phan Rang - Tháp Chàm' ,mvalue_province_code= '44' where code = '582';
UPDATE district set mvalue_code = '476',mvalue_name= 'Cẩm Khê' ,mvalue_province_code= '45' where code = '235';
UPDATE district set mvalue_code = '477',mvalue_name= 'Đoan Hùng' ,mvalue_province_code= '45' where code = '230';
UPDATE district set mvalue_code = '478',mvalue_name= 'Hạ Hoà' ,mvalue_province_code= '45' where code = '231';
UPDATE district set mvalue_code = '479',mvalue_name= 'Lâm Thao' ,mvalue_province_code= '45' where code = '237';
UPDATE district set mvalue_code = '480',mvalue_name= 'Phù Ninh' ,mvalue_province_code= '45' where code = '233';
UPDATE district set mvalue_code = '481',mvalue_name= 'Tam Nông' ,mvalue_province_code= '45' where code = '236';
UPDATE district set mvalue_code = '482',mvalue_name= 'Tân Sơn' ,mvalue_province_code= '45' where code = '240';
UPDATE district set mvalue_code = '483',mvalue_name= 'Thanh Ba' ,mvalue_province_code= '45' where code = '232';
UPDATE district set mvalue_code = '484',mvalue_name= 'Thanh Sơn' ,mvalue_province_code= '45' where code = '238';
UPDATE district set mvalue_code = '485',mvalue_name= 'Thanh Thuỷ' ,mvalue_province_code= '45' where code = '239';
UPDATE district set mvalue_code = '486',mvalue_name= 'Yên Lập' ,mvalue_province_code= '45' where code = '234';
UPDATE district set mvalue_code = '487',mvalue_name= 'Việt Trì' ,mvalue_province_code= '45' where code = '227';
UPDATE district set mvalue_code = '488',mvalue_name= 'Phú Thọ' ,mvalue_province_code= '45' where code = '228';
UPDATE district set mvalue_code = '489',mvalue_name= 'Đông Hòa' ,mvalue_province_code= '46' where code = '564';
UPDATE district set mvalue_code = '490',mvalue_name= 'Đồng Xuân' ,mvalue_province_code= '46' where code = '558';
UPDATE district set mvalue_code = '491',mvalue_name= 'Phú Hoà' ,mvalue_province_code= '46' where code = '563';
UPDATE district set mvalue_code = '492',mvalue_name= 'Sơn Hòa' ,mvalue_province_code= '46' where code = '560';
UPDATE district set mvalue_code = '493',mvalue_name= 'Sông Cầu' ,mvalue_province_code= '46' where code = '557';
UPDATE district set mvalue_code = '494',mvalue_name= 'Sông Hinh' ,mvalue_province_code= '46' where code = '561';
UPDATE district set mvalue_code = '495',mvalue_name= 'Tây Hòa' ,mvalue_province_code= '46' where code = '562';
UPDATE district set mvalue_code = '496',mvalue_name= 'Tuy An' ,mvalue_province_code= '46' where code = '559';
UPDATE district set mvalue_code = '497',mvalue_name= 'Tuy Hòa' ,mvalue_province_code= '46' where code = '555';
UPDATE district set mvalue_code = '498',mvalue_name= 'Bố Trạch' ,mvalue_province_code= '47' where code = '455';
UPDATE district set mvalue_code = '499',mvalue_name= 'Lệ Thủy' ,mvalue_province_code= '47' where code = '457';
UPDATE district set mvalue_code = '500',mvalue_name= 'Minh Hóa' ,mvalue_province_code= '47' where code = '452';
UPDATE district set mvalue_code = '501',mvalue_name= 'Quảng Ninh' ,mvalue_province_code= '47' where code = '456';
UPDATE district set mvalue_code = '502',mvalue_name= 'Quảng Trạch' ,mvalue_province_code= '47' where code = '454';
UPDATE district set mvalue_code = '503',mvalue_name= 'Tuyên Hóa' ,mvalue_province_code= '47' where code = '453';
UPDATE district set mvalue_code = '504',mvalue_name= 'Đồng Hới' ,mvalue_province_code= '47' where code = '450';
UPDATE district set mvalue_code = '505',mvalue_name= 'Bắc Trà My' ,mvalue_province_code= '48' where code = '515';
UPDATE district set mvalue_code = '506',mvalue_name= 'Đại Lộc' ,mvalue_province_code= '48' where code = '506';
UPDATE district set mvalue_code = '507',mvalue_name= 'Điện Bàn' ,mvalue_province_code= '48' where code = '507';
UPDATE district set mvalue_code = '508',mvalue_name= 'Đông Giang' ,mvalue_province_code= '48' where code = '505';
UPDATE district set mvalue_code = '509',mvalue_name= 'Duy Xuyên' ,mvalue_province_code= '48' where code = '508';
UPDATE district set mvalue_code = '510',mvalue_name= 'Hiệp Đức' ,mvalue_province_code= '48' where code = '512';
UPDATE district set mvalue_code = '511',mvalue_name= 'Nam Giang' ,mvalue_province_code= '48' where code = '510';
UPDATE district set mvalue_code = '512',mvalue_name= 'Nam Trà My' ,mvalue_province_code= '48' where code = '516';
UPDATE district set mvalue_code = '513',mvalue_name= 'Nông Sơn' ,mvalue_province_code= '48' where code = '519';
UPDATE district set mvalue_code = '514',mvalue_name= 'Núi Thành' ,mvalue_province_code= '48' where code = '517';
UPDATE district set mvalue_code = '515',mvalue_name= 'Phú Ninh' ,mvalue_province_code= '48' where code = '518';
UPDATE district set mvalue_code = '516',mvalue_name= 'Phước Sơn' ,mvalue_province_code= '48' where code = '511';
UPDATE district set mvalue_code = '517',mvalue_name= 'Quế Sơn' ,mvalue_province_code= '48' where code = '509';
UPDATE district set mvalue_code = '518',mvalue_name= 'Tây Giang' ,mvalue_province_code= '48' where code = '504';
UPDATE district set mvalue_code = '519',mvalue_name= 'Thăng Bình' ,mvalue_province_code= '48' where code = '513';
UPDATE district set mvalue_code = '520',mvalue_name= 'Tiên Phước' ,mvalue_province_code= '48' where code = '514';
UPDATE district set mvalue_code = '521',mvalue_name= 'Hội An' ,mvalue_province_code= '48' where code = '503';
UPDATE district set mvalue_code = '522',mvalue_name= 'Tam Kỳ' ,mvalue_province_code= '48' where code = '502';
UPDATE district set mvalue_code = '523',mvalue_name= 'Ba Tơ' ,mvalue_province_code= '49' where code = '535';
UPDATE district set mvalue_code = '524',mvalue_name= 'Bình Sơn' ,mvalue_province_code= '49' where code = '524';
UPDATE district set mvalue_code = '525',mvalue_name= 'Đức Phổ' ,mvalue_province_code= '49' where code = '534';
UPDATE district set mvalue_code = '526',mvalue_name= 'Lý Sơn' ,mvalue_province_code= '49' where code = '536';
UPDATE district set mvalue_code = '527',mvalue_name= 'Minh Long' ,mvalue_province_code= '49' where code = '531';
UPDATE district set mvalue_code = '528',mvalue_name= 'Mộ Đức' ,mvalue_province_code= '49' where code = '533';
UPDATE district set mvalue_code = '529',mvalue_name= 'Nghĩa Hành' ,mvalue_province_code= '49' where code = '532';
UPDATE district set mvalue_code = '530',mvalue_name= 'Sơn Hà' ,mvalue_province_code= '49' where code = '529';
UPDATE district set mvalue_code = '531',mvalue_name= 'Sơn Tây' ,mvalue_province_code= '49' where code = '530';
UPDATE district set mvalue_code = '532',mvalue_name= 'Sơn Tịnh' ,mvalue_province_code= '49' where code = '527';
UPDATE district set mvalue_code = '534',mvalue_name= 'Trà Bồng' ,mvalue_province_code= '49' where code = '525';
UPDATE district set mvalue_code = '535',mvalue_name= 'Tư Nghĩa' ,mvalue_province_code= '49' where code = '528';
UPDATE district set mvalue_code = '536',mvalue_name= 'Quảng Ngãi' ,mvalue_province_code= '49' where code = '522';
UPDATE district set mvalue_code = '537',mvalue_name= 'Ba Chẽ' ,mvalue_province_code= '50' where code = '202';
UPDATE district set mvalue_code = '538',mvalue_name= 'Bình Liêu' ,mvalue_province_code= '50' where code = '198';
UPDATE district set mvalue_code = '539',mvalue_name= 'Cô Tô' ,mvalue_province_code= '50' where code = '207';
UPDATE district set mvalue_code = '540',mvalue_name= 'Đầm Hà' ,mvalue_province_code= '50' where code = '200';
UPDATE district set mvalue_code = '541',mvalue_name= 'Đông Triều' ,mvalue_province_code= '50' where code = '205';
UPDATE district set mvalue_code = '542',mvalue_name= 'Hải Hà' ,mvalue_province_code= '50' where code = '201';
UPDATE district set mvalue_code = '544',mvalue_name= 'Tiên Yên' ,mvalue_province_code= '50' where code = '199';
UPDATE district set mvalue_code = '545',mvalue_name= 'Vân Đồn' ,mvalue_province_code= '50' where code = '203';
UPDATE district set mvalue_code = '547',mvalue_name= 'Hạ Long' ,mvalue_province_code= '50' where code = '193';
UPDATE district set mvalue_code = '548',mvalue_name= 'Móng Cái' ,mvalue_province_code= '50' where code = '194';
UPDATE district set mvalue_code = '549',mvalue_name= 'Cẩm Phả' ,mvalue_province_code= '50' where code = '195';
UPDATE district set mvalue_code = '550',mvalue_name= 'Uông Bí' ,mvalue_province_code= '50' where code = '196';
UPDATE district set mvalue_code = '551',mvalue_name= 'Cam Lộ' ,mvalue_province_code= '51' where code = '468';
UPDATE district set mvalue_code = '552',mvalue_name= 'Đa Krông' ,mvalue_province_code= '51' where code = '467';
UPDATE district set mvalue_code = '553',mvalue_name= 'Cồn Cỏ' ,mvalue_province_code= '51' where code = '471';
UPDATE district set mvalue_code = '554',mvalue_name= 'Gio Linh' ,mvalue_province_code= '51' where code = '466';
UPDATE district set mvalue_code = '555',mvalue_name= 'Hải Lăng' ,mvalue_province_code= '51' where code = '470';
UPDATE district set mvalue_code = '556',mvalue_name= 'Hướng Hóa' ,mvalue_province_code= '51' where code = '465';
UPDATE district set mvalue_code = '557',mvalue_name= 'Triệu Phong' ,mvalue_province_code= '51' where code = '469';
UPDATE district set mvalue_code = '558',mvalue_name= 'Vĩnh Linh' ,mvalue_province_code= '51' where code = '464';
UPDATE district set mvalue_code = '559',mvalue_name= 'Đông Hà' ,mvalue_province_code= '51' where code = '461';
UPDATE district set mvalue_code = '560',mvalue_name= 'Quảng Trị' ,mvalue_province_code= '51' where code = '462';
UPDATE district set mvalue_code = '561',mvalue_name= 'Châu Thành' ,mvalue_province_code= '52' where code = '942';
UPDATE district set mvalue_code = '562',mvalue_name= 'Cù Lao Dung' ,mvalue_province_code= '52' where code = '945';
UPDATE district set mvalue_code = '563',mvalue_name= 'Kế Sách' ,mvalue_province_code= '52' where code = '943';
UPDATE district set mvalue_code = '564',mvalue_name= 'Long Phú' ,mvalue_province_code= '52' where code = '946';
UPDATE district set mvalue_code = '565',mvalue_name= 'Mỹ Tú' ,mvalue_province_code= '52' where code = '944';
UPDATE district set mvalue_code = '566',mvalue_name= 'Mỹ Xuyên' ,mvalue_province_code= '52' where code = '947';
UPDATE district set mvalue_code = '567',mvalue_name= 'Ngã Năm' ,mvalue_province_code= '52' where code = '948';
UPDATE district set mvalue_code = '568',mvalue_name= 'Thạnh Trị' ,mvalue_province_code= '52' where code = '949';
UPDATE district set mvalue_code = '569',mvalue_name= 'Vĩnh Châu' ,mvalue_province_code= '52' where code = '950';
UPDATE district set mvalue_code = '570',mvalue_name= 'Sóc Trăng' ,mvalue_province_code= '52' where code = '941';
UPDATE district set mvalue_code = '571',mvalue_name= 'Bắc Yên' ,mvalue_province_code= '53' where code = '121';
UPDATE district set mvalue_code = '572',mvalue_name= 'Mai Sơn' ,mvalue_province_code= '53' where code = '125';
UPDATE district set mvalue_code = '573',mvalue_name= 'Mộc Châu' ,mvalue_province_code= '53' where code = '123';
UPDATE district set mvalue_code = '574',mvalue_name= 'Mường La' ,mvalue_province_code= '53' where code = '120';
UPDATE district set mvalue_code = '575',mvalue_name= 'Phù Yên' ,mvalue_province_code= '53' where code = '122';
UPDATE district set mvalue_code = '576',mvalue_name= 'Quỳnh Nhai' ,mvalue_province_code= '53' where code = '118';
UPDATE district set mvalue_code = '577',mvalue_name= 'Sông Mã' ,mvalue_province_code= '53' where code = '126';
UPDATE district set mvalue_code = '578',mvalue_name= 'Sốp Cộp' ,mvalue_province_code= '53' where code = '127';
UPDATE district set mvalue_code = '579',mvalue_name= 'Thuận Châu' ,mvalue_province_code= '53' where code = '119';
UPDATE district set mvalue_code = '580',mvalue_name= 'Yên Châu' ,mvalue_province_code= '53' where code = '124';
UPDATE district set mvalue_code = '581',mvalue_name= 'Sơn La' ,mvalue_province_code= '53' where code = '116';
UPDATE district set mvalue_code = '582',mvalue_name= 'Bến Cầu' ,mvalue_province_code= '54' where code = '711';
UPDATE district set mvalue_code = '583',mvalue_name= 'Châu Thành' ,mvalue_province_code= '54' where code = '708';
UPDATE district set mvalue_code = '584',mvalue_name= 'Dương Minh Châu' ,mvalue_province_code= '54' where code = '707';
UPDATE district set mvalue_code = '585',mvalue_name= 'Gò Dầu' ,mvalue_province_code= '54' where code = '710';
UPDATE district set mvalue_code = '586',mvalue_name= 'Hòa Thành' ,mvalue_province_code= '54' where code = '709';
UPDATE district set mvalue_code = '587',mvalue_name= 'Tân Biên' ,mvalue_province_code= '54' where code = '705';
UPDATE district set mvalue_code = '588',mvalue_name= 'Tân Châu' ,mvalue_province_code= '54' where code = '706';
UPDATE district set mvalue_code = '589',mvalue_name= 'Trảng Bàng' ,mvalue_province_code= '54' where code = '712';
UPDATE district set mvalue_code = '590',mvalue_name= 'Tây Ninh' ,mvalue_province_code= '54' where code = '703';
UPDATE district set mvalue_code = '591',mvalue_name= 'Đông Hưng' ,mvalue_province_code= '55' where code = '340';
UPDATE district set mvalue_code = '592',mvalue_name= 'Hưng Hà' ,mvalue_province_code= '55' where code = '339';
UPDATE district set mvalue_code = '593',mvalue_name= 'Kiến Xương' ,mvalue_province_code= '55' where code = '343';
UPDATE district set mvalue_code = '594',mvalue_name= 'Quỳnh Phụ' ,mvalue_province_code= '55' where code = '338';
UPDATE district set mvalue_code = '595',mvalue_name= 'Thái Thụy' ,mvalue_province_code= '55' where code = '341';
UPDATE district set mvalue_code = '596',mvalue_name= 'Tiền Hải' ,mvalue_province_code= '55' where code = '342';
UPDATE district set mvalue_code = '597',mvalue_name= 'Vũ Thư' ,mvalue_province_code= '55' where code = '344';
UPDATE district set mvalue_code = '598',mvalue_name= 'Thái Bình' ,mvalue_province_code= '55' where code = '336';
UPDATE district set mvalue_code = '599',mvalue_name= 'Đại Từ' ,mvalue_province_code= '56' where code = '171';
UPDATE district set mvalue_code = '600',mvalue_name= 'Định Hóa' ,mvalue_province_code= '56' where code = '167';
UPDATE district set mvalue_code = '601',mvalue_name= 'Đồng Hỷ' ,mvalue_province_code= '56' where code = '169';
UPDATE district set mvalue_code = '602',mvalue_name= 'Phổ Yên' ,mvalue_province_code= '56' where code = '172';
UPDATE district set mvalue_code = '603',mvalue_name= 'Phú Bình' ,mvalue_province_code= '56' where code = '173';
UPDATE district set mvalue_code = '604',mvalue_name= 'Phú Lương' ,mvalue_province_code= '56' where code = '168';
UPDATE district set mvalue_code = '605',mvalue_name= 'Võ Nhai' ,mvalue_province_code= '56' where code = '170';
UPDATE district set mvalue_code = '606',mvalue_name= 'Thái Nguyên' ,mvalue_province_code= '56' where code = '164';
UPDATE district set mvalue_code = '607',mvalue_name= 'Sông Công' ,mvalue_province_code= '56' where code = '165';
UPDATE district set mvalue_code = '608',mvalue_name= 'Bá Thước' ,mvalue_province_code= '57' where code = '386';
UPDATE district set mvalue_code = '609',mvalue_name= 'Cẩm Thủy' ,mvalue_province_code= '57' where code = '390';
UPDATE district set mvalue_code = '610',mvalue_name= 'Đông Sơn' ,mvalue_province_code= '57' where code = '405';
UPDATE district set mvalue_code = '611',mvalue_name= 'Hà Trung' ,mvalue_province_code= '57' where code = '392';
UPDATE district set mvalue_code = '612',mvalue_name= 'Hậu Lộc' ,mvalue_province_code= '57' where code = '400';
UPDATE district set mvalue_code = '613',mvalue_name= 'Hoằng Hóa' ,mvalue_province_code= '57' where code = '399';
UPDATE district set mvalue_code = '614',mvalue_name= 'Lang Chánh' ,mvalue_province_code= '57' where code = '388';
UPDATE district set mvalue_code = '615',mvalue_name= 'Mường Lát' ,mvalue_province_code= '57' where code = '384';
UPDATE district set mvalue_code = '616',mvalue_name= 'Nga Sơn' ,mvalue_province_code= '57' where code = '401';
UPDATE district set mvalue_code = '617',mvalue_name= 'Ngọc Lặc' ,mvalue_province_code= '57' where code = '582';
UPDATE district set mvalue_code = '618',mvalue_name= 'Như Thanh' ,mvalue_province_code= '57' where code = '403';
UPDATE district set mvalue_code = '619',mvalue_name= 'Như Xuân' ,mvalue_province_code= '57' where code = '402';
UPDATE district set mvalue_code = '620',mvalue_name= 'Nông Cống' ,mvalue_province_code= '57' where code = '404';
UPDATE district set mvalue_code = '621',mvalue_name= 'Quan Hóa' ,mvalue_province_code= '57' where code = '385';
UPDATE district set mvalue_code = '622',mvalue_name= 'Quan Sơn' ,mvalue_province_code= '57' where code = '387';
UPDATE district set mvalue_code = '623',mvalue_name= 'Quảng Xương' ,mvalue_province_code= '57' where code = '406';
UPDATE district set mvalue_code = '624',mvalue_name= 'Thạch Thành' ,mvalue_province_code= '57' where code = '391';
UPDATE district set mvalue_code = '625',mvalue_name= 'Thiệu Hoá' ,mvalue_province_code= '57' where code = '398';
UPDATE district set mvalue_code = '626',mvalue_name= 'Thọ Xuân' ,mvalue_province_code= '57' where code = '395';
UPDATE district set mvalue_code = '627',mvalue_name= 'Thường Xuân' ,mvalue_province_code= '57' where code = '396';
UPDATE district set mvalue_code = '628',mvalue_name= 'Tĩnh Gia' ,mvalue_province_code= '57' where code = '407';
UPDATE district set mvalue_code = '629',mvalue_name= 'Triệu Sơn' ,mvalue_province_code= '57' where code = '397';
UPDATE district set mvalue_code = '630',mvalue_name= 'Vĩnh Lộc' ,mvalue_province_code= '57' where code = '393';
UPDATE district set mvalue_code = '631',mvalue_name= 'Yên Định' ,mvalue_province_code= '57' where code = '394';
UPDATE district set mvalue_code = '632',mvalue_name= 'Thanh Hóa' ,mvalue_province_code= '57' where code = '380';
UPDATE district set mvalue_code = '633',mvalue_name= 'Bỉm Sơn' ,mvalue_province_code= '57' where code = '381';
UPDATE district set mvalue_code = '634',mvalue_name= 'Sầm Sơn' ,mvalue_province_code= '57' where code = '382';


INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-664','Nà Hang','664','Nà Hang','61');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-710','Loa Thành','710','Loa Thành','2');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-711','Ninh Kiều','711','Ninh Kiều','2');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-719','Hội An','719','Hội An','18');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-720','Hòa Quý','720','Hòa Quý','18');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-721','Hòa Châu','721','Hòa Châu','18');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-722','Thất Khê','722','Thất Khê','29');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-18','Từ Liêm','18','Từ Liêm','2');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-94','Hòa Bình','94','Hòa Bình','8');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-99','Gia Bình','99','Gia Bình','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-100','Lương Tài','100','Lương Tài','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-101','Quế Võ','101','Quế Võ','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-102','Thuận Thành','102','Thuận Thành','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-103','Tiên Du','103','Tiên Du','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-104','Yên Phong','104','Yên Phong','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-105','Bắc Ninh','105','Bắc Ninh','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-106','Từ Sơn','106','Từ Sơn','9');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-138','Đồng Phù','138','Đồng Phù','13');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-175','Phục Hoà','175','Phục Hoà','17');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-178','Thông Nông','178','Thông Nông','17');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-179','Trà Lĩnh','179','Trà Lĩnh','17');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-312','Kinh Dương','312','Kinh Dương','29');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-328','Kỳ Sơn','328','Kỳ Sơn','31');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-533','Tây Trà','533','Tây Trà','49');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-543','Hoành Bồ','543','Hoành Bồ','50');
INSERT INTO district (code,name,mvalue_code,mvalue_name,mvalue_province_code) VALUES('MVALUE-546','Yên Hưng','546','Yên Hưng','50');
