create TABLE IF NOT EXISTS `loan_applications`
(
    `uuid`         VARCHAR(36)  NOT NULL,
    `created_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP,
    `profile_id`       VARCHAR(36) NOT NULL,
    `phone`       VARCHAR(50) NOT NULL,
    `full_name`       VARCHAR(150) NULL,
    `gender`    VARCHAR(20) NULL,
    `nationality`     VARCHAR(100) NULL,
    `email`     VARCHAR(100) NULL,
    `id_no`     VARCHAR(20) NULL,
    `issued_on`     VARCHAR(100) NULL,
    `place_of_issue`     VARCHAR(100) NULL,
    `old_id_no`     VARCHAR(20) NULL,
    `province`     VARCHAR(30),
    `province_name`     VARCHAR(250),
    `district`     VARCHAR(30),
    `district_name`     VARCHAR(250),
    `ward`     VARCHAR(30),
    `ward_name`     VARCHAR(250),
    `address`     VARCHAR(250) NULL,
    `ref_code`     VARCHAR(50) NULL,
    `marital_status`     VARCHAR(50) NULL,
    `number_of_dependents`     INT(2) NULL,
    `loan_purpose`     VARCHAR(250) NULL,
    `loan_asset_value`     BIGINT(20) NULL,
    `loan_amount`     BIGINT(20) NULL,
    `loan_time`     INT(3) NULL,
    `status`     VARCHAR(20) NULL,
    PRIMARY KEY (`uuid`)
);