create TABLE IF NOT EXISTS `organization`
(
    `created_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP,
    `code`       VARCHAR(30) NOT NULL,
    `name`  VARCHAR(150) NOT NULL,
    `specialized_bank`  VARCHAR(30)  NULL,
    `parent`       VARCHAR(30) NULL,
    `type`    VARCHAR(30) NULL,
    `ecm_code`       VARCHAR(30) NULL,
    `status`       VARCHAR(30) NULL,
    PRIMARY KEY (`code`)
);

insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('KB_TTR', 'RB', 'Kênh bán tập trung', 'MSB', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100NS', 'RB', 'Kênh bán North Star', 'KB_THAYTHE', 'DVKD', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100MPR1', 'RB', 'Đội bán MPR Miền Bắc', 'KB_THAYTHE', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100MPR2', 'RB', 'Đội bán MPR Miền Nam', 'KB_THAYTHE', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('SOUTH', 'RB', 'Miền Nam', 'MSB', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('HUB', 'RB', 'HUB', 'MSB', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3200', 'RB', 'MSB Thanh Xuân', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3201', 'RB', 'MSB Thanh Xuân Nam', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3204', 'RB', 'MSB Vạn Xuân', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3205', 'RB', 'MSB Trung Yên', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3206', 'RB', 'MSB Xa La', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3208', 'RB', 'MSB Văn Quán', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3209', 'RB', 'MSB Văn Khê', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3210', 'RB', 'MSB Lê Văn Lương', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3212', 'RB', 'MSB Hoàng Văn Thái', '320', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3213', 'RB', 'MSB Văn Phú', '320', 'DVKD', '3213','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3300', 'RB', 'MSB Cầu Giấy', '330', 'DVKD', '33','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3500', 'RB', 'MSB Phương Liệt', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3501', 'RB', 'MSB Bắc Linh Đàm', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3502', 'RB', 'MSB Kim Đồng', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3503', 'RB', 'MSB Định Công', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3504', 'RB', 'MSB Vương Thừa Vũ', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3505', 'RB', 'MSB Nhân Hòa', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3506', 'RB', 'MSB Hoàng Mai', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3507', 'RB', 'MSB Hoàng Liệt', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3607', 'RB', 'MSB Tây Hồ Tây', '300', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3801', 'RB', 'MSB Mễ Trì', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3802', 'RB', 'MSB Mỹ Đình', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3803', 'RB', 'MSB Thăng Long', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3804', 'RB', 'MSB Tràng An', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3805', 'RB', 'MSB Phan Văn Trường', '110', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3806', 'RB', 'MSB Hà Thành', '11000', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3807', 'RB', 'MSB Nguyễn Khánh Toàn', '11000', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3808', 'RB', 'MSB Hoàng Quốc Việt', '110', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3809', 'RB', 'MSB Goldmark', '110', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3810', 'RB', 'MSB Sơn Tây', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11000', 'RB', 'MSB Sở Giao Dịch', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3000', 'RB', 'MSB Hà Nội', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3001', 'RB', 'MSB Đội Cấn', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3003', 'RB', 'MSB Hoàng Hoa Thám', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('34100', 'RB', 'MSB Long An', '3410', 'DVKD', '341','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('34101', 'RB', 'MSB Bến Lức', '3410', 'DVKD', '34100','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('35000', 'RB', 'MSB Tiền Giang', '3500', 'DVKD', '350','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('35001', 'RB', 'MSB Tân Hiệp', '3500', 'DVKD', '35001','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('39000', 'RB', 'MSB Cà Mau', '3900', 'DVKD', '390','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('43000', 'RB', 'MSB Bến Tre', '4300', 'DVKD', '430','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('44000', 'RB', 'MSB Trà Vinh', '4400', 'DVKD', '440','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('47000', 'RB', 'MSB Hậu Giang', '4700', 'DVKD', '470','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('48000', 'RB', 'MSB Bạc Liêu', '4800', 'DVKD', '480','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('50000', 'RB', 'MSB Vĩnh Long', '5000', 'DVKD', '50001','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7000', 'RB', 'MSB Cần Thơ', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7001', 'RB', 'MSB An Thới', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7002', 'RB', 'MSB Hưng Lợi', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7003', 'RB', 'MSB Thốt Nốt', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7005', 'RB', 'MSB Ô Môn', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7006', 'RB', 'MSB Cái Răng', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('7007', 'RB', 'MSB Ninh Kiều', '700', 'DVKD', '70','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('36100', 'RB', 'MSB Kiên Giang', '3610', 'DVKD', '361','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37100', 'RB', 'MSB Châu Đốc', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37101', 'RB', 'MSB Tân Châu', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37102', 'RB', 'MSB Châu Phú', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37103', 'RB', 'MSB Phú Tân', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('NORTH', 'RB', 'Miền Bắc', 'MSB', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37104', 'RB', 'MSB Xuân Tô', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37105', 'RB', 'MSB An Phú', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37106', 'RB', 'MSB Châu Quới', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37108', 'RB', 'MSB Long Bình', '3710', 'DVKD', '371','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37200', 'RB', 'MSB An Giang', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37201', 'RB', 'MSB Mỹ Bình', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37202', 'RB', 'MSB Chợ Mới', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37203', 'RB', 'MSB Châu Thành', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37204', 'RB', 'MSB Mỹ Luông', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37205', 'RB', 'MSB Thoại Sơn', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37206', 'RB', 'MSB Tri Tôn', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37207', 'RB', 'MSB Vĩnh An', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37208', 'RB', 'MSB Long Xuyên', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37209', 'RB', 'MSB Óc Eo', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37210', 'RB', 'MSB Phú Hòa', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('37212', 'RB', 'MSB Ba Chúc', '3720', 'DVKD', '372','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('38000', 'RB', 'MSB Đồng Tháp', '3800', 'DVKD', '380','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('38001', 'RB', 'MSB Lấp Vò', '3800', 'DVKD', '380','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('38002', 'RB', 'MSB Lai Vung', '3800', 'DVKD', '380','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('38003', 'RB', 'MSB Tam Nông', '3800', 'DVKD', '380','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('23000', 'RB', 'MSB Đắk Lắk', '2300', 'DVKD', '230','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('23001', 'RB', 'MSB Tân An', '2300', 'DVKD', '230','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('23002', 'RB', 'MSB Buôn Ma Thuột', '2300', 'DVKD', '230','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('26000', 'RB', 'MSB Huế', '2600', 'DVKD', '260','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('26002', 'RB', 'MSB Xuân Phú', '2600', 'DVKD', '26002','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('27000', 'RB', 'MSB Bình Định', '2700', 'DVKD', '270','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('27001', 'RB', 'MSB Quy Nhơn', '2700', 'DVKD', '270','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3006', 'RB', 'MSB Kim Mã', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3007', 'RB', 'MSB Thủ Đô', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3008', 'RB', 'MSB Giang Văn Minh', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3011', 'RB', 'MSB Cửa Nam', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3100', 'RB', 'MSB Đống Đa', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3107', 'RB', 'MSB Đông Đô', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3109', 'RB', 'MSB Kim Liên', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3110', 'RB', 'MSB Láng Hạ', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3111', 'RB', 'MSB Nguyễn Chí Thanh', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3112', 'RB', 'MSB Vạn Phúc', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3113', 'RB', 'MSB Hoàng Cầu', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3114', 'RB', 'MSB Thái Thịnh', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3115', 'RB', 'MSB Hùng Vương', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11001', 'RB', 'MSB Bà Triệu', '1103', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11006', 'RB', 'MSB Trần Khát Chân', '1103', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11007', 'RB', 'MSB Nguyễn Du', '1103', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11008', 'RB', 'MSB Phan Chu Trinh', '1103', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11009', 'RB', 'MSB Lạc Trung', '1103', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11010', 'RB', 'MSB Times City', '1103', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('11011', 'RB', 'MSB Phố Huế', '1100', 'DVKD', '110','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3400', 'RB', 'MSB Long Biên', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3401', 'RB', 'MSB Đức Giang', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3403', 'RB', 'MSB Hà Huy Tập', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3406', 'RB', 'MSB Đông Anh', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3409', 'RB', 'MSB Việt Hưng', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3410', 'RB', 'MSB Ninh Hiệp', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3411', 'RB', 'MSB Ngọc Lâm', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3600', 'RB', 'MSB Hồ Gươm', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3603', 'RB', 'MSB Hoàn Kiếm', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3604', 'RB', 'MSB Lý Thái Tổ', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3605', 'RB', 'MSB Hàng Da', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3606', 'RB', 'MSB Đồng Xuân', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3608', 'RB', 'MSB Quán Thánh', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3609', 'RB', 'MSB Phố Cổ', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('12000', 'RB', 'MSB Vĩnh Phúc', '1200', 'DVKD', '120','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('12001', 'RB', 'MSB Kim Ngọc', '1200', 'DVKD', '120','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('12002', 'RB', 'MSB Phúc Yên', '1200', 'DVKD', '120','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('12004', 'RB', 'MSB Vĩnh Yên', '1200', 'DVKD', '120','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('18000', 'RB', 'MSB Phú Thọ', '1800', 'DVKD', '180','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('18001', 'RB', 'MSB Tiên Cát', '1800', 'DVKD', '180','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('18002', 'RB', 'MSB Lâm Thao', '1800', 'DVKD', '180','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('19000', 'RB', 'MSB Bắc Ninh', '1900', 'DVKD', '190','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('19001', 'RB', 'MSB Từ sơn', '1900', 'DVKD', '190','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('19002', 'RB', 'MSB Quế Võ', '1900', 'DVKD', '190','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('19100', 'RB', 'MSB Bắc Giang', '1910', 'DVKD', '191','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('24000', 'RB', 'MSB Thái Nguyên', '2400', 'DVKD', '240','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('24001', 'RB', 'MSB Bắc Nam', '2400', 'DVKD', '240','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('24002', 'RB', 'MSB Chợ Thái', '2400', 'DVKD', '240','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3407', 'RB', 'MSB Phù Lỗ', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3408', 'RB', 'MSB Nội Bài', '340', 'DVKD', '34','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('41000', 'RB', 'MSB Hưng Yên', '4100', 'DVKD', '410','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('45000', 'RB', 'MSB Lạng Sơn', '4500', 'DVKD', '450','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('49000', 'RB', 'MSB Lào Cai', '4900', 'DVKD', '49001','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2000', 'RB', 'MSB Hải Phòng', '200', 'DVKD', '20','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('20000', 'RB', 'MSB Hải Dương', '2000', 'DVKD', '200','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3601', 'RB', 'MSB Hàng Đậu', '360', 'DVKD', '36','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('20001', 'RB', 'MSB Chí Linh', '2000', 'DVKD', '200','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('20002', 'RB', 'MSB Hải Tân', '2000', 'DVKD', '200','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('20003', 'RB', 'MSB Gia Lộc', '2000', 'DVKD', '200','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('20004', 'RB', 'MSB Ninh Giang', '2000', 'DVKD', '200','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2001', 'RB', 'MSB Phan Bội Châu', '200', 'DVKD', '20','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2002', 'RB', 'MSB Lê Chân', '200', 'DVKD', '20','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2003', 'RB', 'MSB Lạch Tray', '200', 'DVKD', '20','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2006', 'RB', 'MSB Quán Toan', '200', 'DVKD', '20','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2008', 'RB', 'MSB Ngô Quyền', '200', 'DVKD', '20','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2100', 'RB', 'MSB Hồng Bàng', '210', 'DVKD', '21','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2101', 'RB', 'MSB An Dương', '210', 'DVKD', '21','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2102', 'RB', 'MSB An Biên', '210', 'DVKD', '21','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2103', 'RB', 'MSB Văn Cao', '210', 'DVKD', '21','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5000', 'RB', 'MSB Quảng Ninh', '500', 'DVKD', '50','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5001', 'RB', 'MSB Hồng Hải', '500', 'DVKD', '50','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5002', 'RB', 'MSB Uông Bí', '500', 'DVKD', '50','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5004', 'RB', 'MSB Móng Cái', '500', 'DVKD', '50','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5005', 'RB', 'MSB Quảng Yên', '500', 'DVKD', '50','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5100', 'RB', 'MSB Bãi Cháy', '500', 'DVKD', '51','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5101', 'RB', 'MSB Vườn Đào', '500', 'DVKD', '51','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5102', 'RB', 'MSB Giếng Đáy', '500', 'DVKD', '51','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5200', 'RB', 'MSB Cẩm Phả', '500', 'DVKD', '52','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5201', 'RB', 'MSB Cửa Ông', '500', 'DVKD', '52','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('5202', 'RB', 'MSB Vân Đồn', '500', 'DVKD', '52','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('13000', 'RB', 'MSB Nam Định', '1300', 'DVKD', '130','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('13001', 'RB', 'MSB Nghĩa Hưng', '1300', 'DVKD', '130','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('13002', 'RB', 'MSB Hải Hậu', '1300', 'DVKD', '130','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('13005', 'RB', 'MSB Vụ Bản', '1300', 'DVKD', '130','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('13006', 'RB', 'MSB Hòa Vượng', '1300', 'DVKD', '130','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('15000', 'RB', 'MSB Thái Bình', '1500', 'DVKD', '150','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('15001', 'RB', 'MSB Bồ Xuyên', '1500', 'DVKD', '150','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('15002', 'RB', 'MSB Kỳ Bá', '1500', 'DVKD', '150','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('15003', 'RB', 'MSB Quỳnh Phụ', '1500', 'DVKD', '150','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('16000', 'RB', 'MSB Hà Nam', '1600', 'DVKD', '160','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('16001', 'RB', 'MSB Phủ Lý', '1600', 'DVKD', '160','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('16002', 'RB', 'MSB Đồng Văn', '1600', 'DVKD', '160','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('17000', 'RB', 'MSB Ninh Bình', '1700', 'DVKD', '170','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('17001', 'RB', 'MSB Tam Điệp', '1700', 'DVKD', '170','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('21000', 'RB', 'MSB Thanh Hóa', '2100', 'DVKD', '210','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('21001', 'RB', 'MSB Bỉm Sơn', '2100', 'DVKD', '210','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('21003', 'RB', 'MSB Trường Thi', '2100', 'DVKD', '210','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('22000', 'RB', 'MSB Nghệ An', '2200', 'DVKD', '220','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('22001', 'RB', 'MSB Nguyễn Sỹ Sách', '2200', 'DVKD', '220','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('22002', 'RB', 'MSB Thành Vinh', '2200', 'DVKD', '220','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('22003', 'RB', 'MSB Quán Bàu', '2200', 'DVKD', '220','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('22004', 'RB', 'MSB Thái Hòa', '2200', 'DVKD', '220','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('30000', 'RB', 'MSB Hà Tĩnh', '3000', 'DVKD', '300','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4000LH', 'RB', 'LH Hồ Chí Minh', '4000', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4017LH', 'RB', 'LH Thủ Đức', '4017', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4109LH', 'RB', 'LH Lê Đại Hành', '4109', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4200LH', 'RB', 'LH Hưng Đạo', '4200', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4205LH', 'RB', 'LH Đô Thành', '4200', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4206LH', 'RB', 'LH Tô Hiến Thành', '430', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3011LH', 'RB', 'LH Nam Hà Nội', '3011', 'DVKD', '3505LH','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3110LH', 'RB', 'LH Láng Hạ', '3110', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100LH', 'RB', 'LH Thái Thịnh', '110', 'DVKD', '11014LH','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3209LH', 'RB', 'LH Vạn Phúc', '3209', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3804LH', 'RB', 'LH Tràng An', '3300', 'DVKD', '33','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3000LH', 'RB', 'LH Hà Nội', '300', 'DVKD', '30','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3110L3', 'RB', 'LH Thăng Long', '310', 'DVKD', '31','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3206LH', 'RB', 'LH Hà Đông', '3206', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3212LH', 'RB', 'LH Hoàng Văn Thái', '3212', 'DVKD', '32','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('KBTTMB', 'RB', 'Kênh bán thay thế Miền Bắc', 'KB_THAYTHE', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('KBTTMN', 'RB', 'Kênh bán thay thế Miền Nam', 'KB_THAYTHE', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('28000', 'RB', 'MSB Lâm Đồng', '2800', 'DVKD', '280','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('31000', 'RB', 'MSB Quảng Bình', '3100', 'DVKD', '310','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('31001', 'RB', 'MSB Ba Đồn', '3100', 'DVKD', '310','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('31002', 'RB', 'MSB Đồng Hới', '3100', 'DVKD', '31002','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('32000', 'RB', 'MSB Phú Yên', '3200', 'DVKD', '320','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('40000', 'RB', 'MSB Gia Lai', '4000', 'DVKD', '400','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('46000', 'RB', 'MSB Ninh Thuận', '4600', 'DVKD', '460','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('51000', 'RB', 'MSB Kon Tum', '5100', 'DVKD', '5108','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('52000', 'RB', 'MSB Quảng Ngãi', '5200', 'DVKD', '52000','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('6000', 'RB', 'MSB Đà Nẵng', '600', 'DVKD', '60','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('6001', 'RB', 'MSB Chợ Cồn', '600', 'DVKD', '60','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('6002', 'RB', 'MSB Hoàng Diệu', '600', 'DVKD', '60','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('6004', 'RB', 'MSB Hải Châu', '600', 'DVKD', '6101','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('6005', 'RB', 'MSB Liên Chiểu', '600', 'DVKD', '60','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('6200', 'RB', 'MSB Quảng Nam', '620', 'DVKD', '62','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('9000', 'RB', 'MSB Khánh Hòa', '900', 'DVKD', '90','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('9001', 'RB', 'MSB Nha Trang', '900', 'DVKD', '90','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('9002', 'RB', 'MSB Vĩnh Nguyên', '900', 'DVKD', '90','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('9003', 'RB', 'MSB Vĩnh Phước', '900', 'DVKD', '90','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('9004', 'RB', 'MSB Cam Ranh', '900', 'DVKD', '90','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4000', 'RB', 'MSB Hồ Chí Minh', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4002', 'RB', 'MSB Thị Nghè', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4004', 'RB', 'MSB Quận 9', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4006', 'RB', 'MSB Thảo Điền', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4010', 'RB', 'MSB Bình Thạnh', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4011', 'RB', 'MSB Quận 7', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4012', 'RB', 'MSB Khánh Hội', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4014', 'RB', 'MSB Mỹ Toàn', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4015', 'RB', 'MSB Nguyễn Sơn', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4016', 'RB', 'MSB Yoko', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4017', 'RB', 'MSB Thủ Đức', '400', 'DVKD', '40','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4100', 'RB', 'MSB Sài Gòn', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4101', 'RB', 'MSB Quận 6', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4104', 'RB', 'MSB Nguyễn Tri Phương', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4105', 'RB', 'MSB Trần Hưng Đạo', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4107', 'RB', 'MSB Bình Tân', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4108', 'RB', 'MSB Bến Thành', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4109', 'RB', 'MSB Lê Đại Hành', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4110', 'RB', 'MSB Lãnh Bình Thăng', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4111', 'RB', 'MSB Bùi Thị Xuân', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4112', 'RB', 'MSB Bình Chánh', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4300', 'RB', 'MSB Tân Bình', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4303', 'RB', 'MSB Lữ Gia', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4304', 'RB', 'MSB Hòa Bình', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4305', 'RB', 'MSB Lê Thị Riêng', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4306', 'RB', 'MSB An Sương', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4307', 'RB', 'MSB Tam Bình', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4308', 'RB', 'MSB Mũi Tàu', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4309', 'RB', 'MSB Ba Tháng Hai', '430', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('14000', 'RB', 'MSB Bình Dương', '1400', 'DVKD', '140','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('14001', 'RB', 'MSB Mỹ phước', '1400', 'DVKD', '140','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('14002', 'RB', 'MSB Phú Cường', '1400', 'DVKD', '140','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('14003', 'RB', 'MSB Thuận An', '1400', 'DVKD', '140','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('25000', 'RB', 'MSB Đồng Nai', '2500', 'DVKD', '250','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('25001', 'RB', 'MSB Phạm Văn Thuận', '2500', 'DVKD', '250','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('25002', 'RB', 'MSB Tân Biên', '2500', 'DVKD', '250','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('29000', 'RB', 'MSB Tây Ninh', '2900', 'DVKD', '290','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('33000', 'RB', 'MSB Bình Thuận', '3300', 'DVKD', '330','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4200', 'RB', 'MSB Quận 3', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('42000', 'RB', 'MSB Bình Phước', '4200', 'DVKD', '420','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4202', 'RB', 'MSB Nguyễn Oanh', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4203', 'RB', 'MSB Phú Nhuận', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4204', 'RB', 'MSB Đinh Tiên Hoàng', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4205', 'RB', 'MSB Đô Thành', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4206', 'RB', 'MSB Bàn Cờ', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4412', 'RB', 'MSB Tân Thuận', '440', 'DVKD', '4412','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4210', 'RB', 'MSB Võ Trường Toản', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4212', 'RB', 'MSB Nhà Bè', '420', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4400', 'RB', 'MSB Cộng Hòa', '440', 'DVKD', '44','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4402', 'RB', 'MSB Tân Phú', '440', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4403', 'RB', 'MSB Trường Sơn', '440', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4404', 'RB', 'MSB Gò Vấp', '440', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4405', 'RB', 'MSB Phổ Quang', '440', 'DVKD', '44','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4406', 'RB', 'MSB Bàu Cát', '440', 'DVKD', '43','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4407', 'RB', 'MSB Lê Trọng Tấn', '440', 'DVKD', '42','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4410', 'RB', 'MSB Củ Chi', '440', 'DVKD', '44','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4411', 'RB', 'MSB Hóc Môn', '440', 'DVKD', '44','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('8000', 'RB', 'MSB Vũng Tàu', '800', 'DVKD', '80','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('8001', 'RB', 'MSB Đông Xuyên', '800', 'DVKD', '80','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('8002', 'RB', 'MSB Bà Rịa', '800', 'DVKD', '80','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('8003', 'RB', 'MSB Nguyễn Thái Học', '800', 'DVKD', '80','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('8004', 'RB', 'MSB Ba Cu', '800', 'DVKD', '80','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('8005', 'RB', 'MSB Phước Trung', '800', 'DVKD', '80','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('KB_THAYTHE', 'RB', 'Kênh bán thay thế', 'KB_TTR', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100T1', 'RB', 'Telesales Miền Bắc', '3110', 'DVKD', 'TSFB','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100T2', 'RB', 'Telesales Miền Nam', '', 'DVKD', 'TSFN','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('MSB', 'RB', 'MSB', '', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA1', 'RB', 'AREA 1', 'NORTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA2', 'RB', 'AREA 2', 'NORTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA3', 'RB', 'AREA 3', 'NORTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA5', 'RB', 'AREA 5', 'NORTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA6A', 'RB', 'AREA 6A', 'NORTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA6B', 'RB', 'AREA 6B', 'NORTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA7', 'RB', 'AREA 7', 'SOUTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA8', 'RB', 'AREA 8', 'SOUTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA9', 'RB', 'AREA 9', 'SOUTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA10', 'RB', 'AREA 10', 'SOUTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('AREA11', 'RB', 'AREA 11', 'SOUTH', 'AREA', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('HUBHN1', 'RB', 'Lending Hub HN 1', 'HUB', 'DVKD', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('HUBHN2', 'RB', 'Lending Hub HN 2', 'HUB', 'DVKD', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('HUBHCM', 'RB', 'Lending Hub HCM', 'HUB', 'DVKD', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('KB_THAYTHE1', 'RB', 'Kênh bán thay thế', '', '', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('Directsales miền Bắc', 'RB', 'Directsales miền Bắc', '3110', 'DVKD', 'DSFB','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100DSMN', 'RB', 'Directsales miền Nam', '4200', 'DVKD', 'DSFN','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('4106', 'RB', 'MSB Gold View', '410', 'DVKD', '41','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('TNTDHO', 'RB', 'TNTD HO', '', 'DVKD', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('19101', 'RB', 'MSB Lục Nam', '1910', 'DVKD', '191','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('2104', 'RB', 'MSB Lê Lai', '210', 'DVKD', '21','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100SSEMB', 'RB', 'Vùng  Kinh doanh Hà Nội', '320', 'DVKD', '','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('1100SSEMN', 'RB', 'Vùng kinh doanh HCM', '430', 'DVKD', '1100SSEMN','ACTIVE');
insert into organization(code, specialized_bank, name, parent, type, ecm_code, status) values('3106', 'RB', 'MSB Hào Nam', '310', 'DVKD', '31','ACTIVE');

